### ISSUE TITLE
More problems with representative points

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#10]
I noticed that the representative point for http://pleiades.stoa.org/places/857018/ is in the Black Sea, a good distance away from the locations provided. This is from the nightly .csv dumps
Steps to reproduce:
SImply download the nightly .csv dumps and locate the coordinates for the place

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/59, where it was originally opened by @rmhorne

**Comment by davisagli** [comment]
This appears to have a reasonable representative point now, so was probably fixed as a side effect of something else we did.
