### ISSUE TITLE
verify alternate serializations from upgraded version match those from p3 production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#107]
The following export files match exactly between P3 production and P4 staging (with the exception of domain self-reference in URLs, which is not a problem):

- Atom
- KML
- Neighborhood KML

There are some apparent differences showing up in JSON and in the two RDF serializations. I'm going to look into those some more.

**Comment by paregorios** [comment]
The only apparent difference in the JSON serializations is that P4 production adds a JSON-LD ```@context``` that's not there on production:

```
   "@context": {
        "Feature": "http://geovocab.org/spatial#Feature",
        "FeatureCollection": "_:n1",
        "GeometryCollection": "http://geovocab.org/geometry#GeometryCollection",
        "LineString": "http://geovocab.org/geometry#LineString",
        "MultiLineString": "http://geovocab.org/geometry#MultiLineString",
        "MultiPoint": "http://geovocab.org/geometry#MultiPoint",
        "MultiPolygon": "http://geovocab.org/geometry#MultiPolygon",
        "Point": "http://geovocab.org/geometry#Point",
        "Polygon": "http://geovocab.org/geometry#Polygon",
        "bbox": "http://geovocab.org/geometry#bbox",
        "connectsWith": "_:n8",
        "coordinates": "_:n5",
        "description": "http://purl.org/dc/terms/description",
        "features": "_:n3",
        "geometry": "http://geovocab.org/geometry#geometry",
        "id": "@id",
        "link": "_:n6",
        "location_precision": "_:n7",
        "names": "_:n9",
        "properties": "_:n4",
        "recent_changes": "_:n10",
        "reprPoint": "_:n11",
        "snippet": "http://purl.org/dc/terms/abstract",
        "title": "http://purl.org/dc/terms/title",
        "type": "@type"
    },
```
This shouldn't cause any problems (and is, in fact, a good thing), but I think we should figure out whether this crept in magically by virtue of some upgrade in the JSON tooling or one of our products, or if it was intentionally added by @davisagli or @alecpm .

In any case, we'll also want to look at cleaning up the namespace declarations in same so that all terms are properly associated with their parent vocabulary.

**Comment by davisagli** [comment]
It's not something we changed intentionally. Could it be a change that was made in the source repository but not deployed?

**Comment by paregorios** [comment]
Possibly. I'll investigate.

**Comment by paregorios** [comment]
I've observed the following differences in the RDF/TTL serializations:

## Datetime formatting

In P3 production exports, datetime strings look like "2014-03-22 11:21:50" but in P4 production they look like "2014-03-22T11:21:50-04:00". The latter string looks right as I read the Dublin Core and W3C guidance (i.e., there must be a "T" separating date and time). Apparently, this fixes a bug in the P3 serialization and therefore should be left alone.

## References sort order

In both versions, there is an empty list included in the series of triples for a reference serialization, e.g. in the P4 staging triples:

```
cito:citesForInformation <http://atlantides.org/bibliography/a.html#André-1980>,
        <http://openlibrary.org/works/OL8327792W>,
        [ ];
```

In P3 production serializations, this empty-list triple appears before the two triples with URI objects:

```
cito:citesForInformation [ ],
        <http://atlantides.org/bibliography/a.html#André-1980>,
        <http://openlibrary.org/works/OL8327792W>;
```

The sort order of these triples is completely irrelevant, but we should find out why this empty list is there in the first place and probably suppress it. I will investigate and, if warranted, open a separate ticket for action.

## Significant digits on ```osgeo:asGeoJSON```

On P3 production, coordinates seem to have a huge number of significant digits, e.g.:

```
osgeo:asGeoJSON "{\"type\": \"Point\", \"coordinates\": [73.700000000000003, 37.450000000000003]}";
```

but on P4 staging, these have been truncated:

```
osgeo:asGeoJSON "{\"type\": \"Point\", \"coordinates\": [73.7, 37.45]}";
```

This P4 truncation may reflect some underlying library that is dealing more sensibly with what appears in P3 with a spurious level of precision, but one wonders why ```osgeo:asWKT``` doesn't receive the same treatment (it's got identically excess precision in both versions). 

Here's another case where a nervous person would like to see the code involved identified.

**Comment by davisagli** [comment]
The last one is due to a change in how Python itself represents floating point numbers (in Python 2.7). I'd have to take a look at what it's doing with `osgeo:asWKT`

**Comment by paregorios** [comment]
I'm still working on comparing the RDF/XML files. Elements appear in different orders throughout the files, so a text-or-xml-based diff is inadequate. Jena's rdfcompare reports "models are unequal", but by design doesn't say how.

**Comment by paregorios** [comment]
Use of rdflib/compare.py demonstrates that the only semantic differences between the two RDF/XML files are the same datetime and float formatting issues [identified above](https://github.com/isawnyu/pleiades-gazetteer/issues/107#issuecomment-203129702) for the RDF/TTL.

**Comment by paregorios** [comment]
I have verified that the appearance of ```@context``` in JSON exports is (as @davisagli suspected) due to code changes that were committed to the pleiades.json module. The corresponding egg (pleiades.json 0.16) was deployed to production, but the version pin in the buildout config was never updated from 0.15.2.

**Comment by paregorios** [comment]
I have split out the remaining thread item on geojson upgrades to #108.

**Comment by paregorios** [comment]
There are, in my opinion, no further tasks to undertake on this ticket, so closing.
