### ISSUE TITLE
lock down server replacement schedule

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#111]

**Comment by alecpm** [comment]
The server configuration scripts and documentation should be comprehensive and ready to create and deploy to both staging and production environments. See here:

https://github.com/isawnyu/pleiades-ansible

Once there's a plan for #106 we can potentially incorporate the concordia repository and configuration into the server setup if needed.

**Comment by paregorios** [comment]
New production server is ready.
