### ISSUE TITLE
Prevent plone.app.iterate from asking where to put working copy

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#112]
Currently in p4 checking out a working copy shows this screen:

![screen shot 2016-04-05 at 12 10 14 pm](https://cloud.githubusercontent.com/assets/49014/14294764/790f6896-fb27-11e5-961c-e3c3a1887936.png)

In p3 I think plone.app.iterate was patched to avoid giving this option (and always check out into the parent folder). Am I correct that we'd like to keep that customization?

**Comment by paregorios** [comment]
Yes please keep that customization.

On Tuesday, April 5, 2016, David Glick <notifications@github.com> wrote:

> Currently in p4 checking out a working copy shows this screen:
>
> [image: screen shot 2016-04-05 at 12 10 14 pm]
> <https://cloud.githubusercontent.com/assets/49014/14294764/790f6896-fb27-11e5-961c-e3c3a1887936.png>
>
> In p3 I think plone.app.iterate was patched to avoid giving this option
> (and always check out into the parent folder). Am I correct that we'd like
> to keep that customization?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/isawnyu/pleiades-gazetteer/issues/112>
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Okay, this should work correctly now.
