### ISSUE TITLE
make full review list faster

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#116]
When the review list is large, it takes a lot of time to generate it and a lot of resources get used in the process. Investigation documented at #97 led to the conclusion that we might be able to rewrite how this works to use the catalog instead of accessing actual objects. Other optimizations might be possible as well. 

Other review list enhancement request: #98

**Comment by cguardia** [comment]
I changed the review list to use the catalog. It will be interesting to try it out on staging (not deployed yet).

**Comment by davisagli** [comment]
This is a good candidate for contributing upstream to Plone.

**Comment by cguardia** [comment]
Deployed. It does appear to be a lot faster (but still not *fast*).

**Comment by paregorios** [comment]
Is this deployed to production or just to staging?

**Comment by paregorios** [comment]
This is remarkably faster on staging. I assume it has not yet been deployed to production, where one encounters a 503 when trying to view the full review list. So, I'm going to label this for deployment to production and ask @cguardia to make that happen when he has time.

**Comment by cguardia** [comment]
This is on the staging branch, which also has the registry vocabulary. Should I cherry pick the change and put it on master?

**Comment by davisagli** [comment]
@cguardia please do if it's not too hard

**Comment by cguardia** [comment]
Deployed to production.

**Comment by paregorios** [comment]
This is *sooooo* much better. Closing as resolved.
