### ISSUE TITLE
test deploy scripts on Ubuntu 16.04

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#120]
Per @alecpm in email: 

> I think it won't be a significant issue to start on 16.04, but we'll need to do a little additional testing of our deploy scripts on that platform. I think the current scripts are pretty tied to 14.04, but that's primarily because of the hoops we had to jump through to get Plone 3.x and Python 2.4 running.  We can disable those bits easily and I expect the remainder should work on 16.04 without issue (the vaytroux service is the primary area of uncertainty, though we can test moving that from Python 2.6 to 2.7 in advance).

**Comment by alecpm** [comment]
The Ubuntu 16.04 test site is up at: http://52.39.101.112 and ready for testing. It should be identical to the deploy on the staging server.

**Comment by paregorios** [comment]
Places, names, and locations appear to be in good shape, including ```/places``` but I'm seeing (as an anonymous user) 502 errors on at least the following:

- ```/news/blog```
- ```/credits```
- ```/docs```
- ```/vocabularies```
- ```/help```

**Comment by alecpm** [comment]
The segfault that occurs when running under the OS python (2.7.11-7ubuntu1) appears to go away when running under a self compiled python. So at this point we could have the ansible scripts compile a python and use that if we want to run on 16.04 or we could stick with 14.04 until the issue is definitively resolved. I've attached a full stack trace for the segfault.
[stack-trace.gz](https://github.com/isawnyu/pleiades-gazetteer/files/230506/stack-trace.gz)

**Comment by alecpm** [comment]
@paregorios Do you have an opinion on whether we should go with a custom python on 16.04 or stick with 14.04? Updating our ansible playbook to build a custom python shouldn't more than an hour.

**Comment by paregorios** [comment]
Unless there are other factors that might complicate things, I am
comfortable going with the custom python in order to go with 16.04.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
The scripts are updated and the server is deployed with the new python. Let me know when we have access to the new Tummy server so we can do an initial deploy and test there. The new test server for 16.04 is up at:

http://52.38.6.139/
