### ISSUE TITLE
Hide Language and Location fields from Place?

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#121]
When editing a Place, on the categorization tab we show the standard Plone Language and Location metadata fields. These seem potentially confusing since they are unused but called the same thing as Pleiades concepts that we do use. Is there any reason not to hide them?

**Comment by paregorios** [comment]
Yes, please hide them. They should probably also be hidden on locations and names, for the same reason.

**Comment by davisagli** [comment]
Since I wrote that I discovered that on Locations the 'location' field is being co-opted to store a reference to CAP grids. So we probably don't want to hide that one.

**Comment by paregorios** [comment]
:)

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott
