### ISSUE TITLE
flickr portlet not longer displays anything

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#125]
It's been removed from place pages through-the-plone because it was no longer displaying anything and we didn't have time or resources to troubleshoot, but there is a lot of useful content out there, and people would like to see it.

https://github.com/isawnyu/pleiades-portlet.flickr

**Comment by atomrab** [comment]
It might make sense to consider something that could also be configured to pull in images with Pleiades tags expressed in RDF or JSON-LD. I'm working on a student-sourced LD image tagger (https://github.com/utls/django-nanosourcer) that applies Pleiades and PeriodO URIs, with images to be published with RDF descriptions through a Fedora repository at the UT libraries, and it would be cool if those images could be pulled into Pleiades pages.

**Comment by witekdev** [comment]
@paregorios fixed, the issue was that we were not using ssl.
but I need commit rights to the repo (and maybe to other repos too?) to push my fix.
```remote: Permission to isawnyu/pleiades-portlet.flickr.git denied to witekdev```

**Comment by davisagli** [comment]
@witekdev the Pleiades team didn't have access to that repository; should work now.

**Comment by witekdev** [comment]
@paregorios the fix is on staging. Just add the portlet somewhere to see it in action. I added it to "Browse Places" section.

**Comment by paregorios** [comment]
Flickr portlet tested on staging. I think this fix is ready to deploy to production. I think we should address the RDF/JSON-LD feature request from @atomrab (above) in a separate story, which I will undertake to create in scrumdo.

**Comment by witekdev** [comment]
This has been deployed to production.

**Comment by paregorios** [comment]
Looks great! I've reassigned the portlet to the /places folder instead of the default page so that it propagates down to all the place content items.
