### ISSUE TITLE
pressing enter in quicksearch behavior has changed

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#127]
On P3 production, typing a string and pressing the enter key executes an advanced search for the string with a wildcard search operator appended. On P4, the advanced search form is presented, with the search text box prefilled with the string and asterisk, but the search does not execute without additional input from the user (i.e., clicking the "advanced search" button on the advanced search form).

**Comment by davisagli** [comment]
Right, this broke when I changed the advanced search link on the search portlet to go to the advanced search form; I didn't realize that that value is also used for the form action.

**Comment by alecpm** [comment]
Should be working properly now with advanced search going to advanced search and regular search going to regular search.
