### ISSUE TITLE
RDF/TTL dumps lack proper URI domains

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#128]
In working to verify implementation of #103 on the incoming production server (isaw1), I discovered that URIs in the RDF/TTL files that should begin ```http://pleiades.stoa.org``` are starting instead with ```http://nohost/plone/```. Is this a condition that will magically clear up when we shift the DNS over, or is specific intervention required?

**Comment by davisagli** [comment]
Looks like the RDF dump script expects to find SERVER_NAME in the OS environment, and we need to set that up.

**Comment by alecpm** [comment]
Hm, the script already sets the SERVER_NAME environment variable, so something else appears to be happening here.

**Comment by davisagli** [comment]
Here's what I'm doing in the new dump script:

    app.REQUEST.setServerURL('http', 'pleiades.stoa.org')
    app.REQUEST.other['VirtualRootPhysicalPath'] = site.getPhysicalPath()

**Comment by alecpm** [comment]
This fix is in place. Check the dump on isaw1.atlantides.org, the corrected dump on 52.38.6.139 should be finished soon as well.
