### ISSUE TITLE
Connections Byline Has Dead Links

### ISSUE THREAD

**Issue by alecpm** [isawnyu/pleiades-gazetteer#130]
Links to the author page in the bylines of the folder_listing template (used for place Connections) do not attempt to determine if the author name corresponds to a member. The result is often a 404 link to a non-existent author page. See:

http://isaw1.atlantides.org/places/423025

**Comment by alecpm** [comment]
This should be fixed on staging and will be fixed on the next production deploy:

http://52.38.6.139/places/579885

**Comment by paregorios** [comment]
looks good to me
