### ISSUE TITLE
Pleiades site returning 503 errors for all ploneish pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#132]
This seems to have started around 22:27 US EDT on 16 May.

**Comment by paregorios** [comment]
It seems likely this is in the aftermath of the server updates and reboots, see email earlier today.

**Comment by alecpm** [comment]
Taking a look now.

**Comment by alecpm** [comment]
Looks like @davisagli got to it a minute before I did.

**Comment by paregorios** [comment]
Everything looks good now. Thanks for the quick response!

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
It appears the supervisor service (which runs all the Plone related services) wasn't starting at boot. On past Ubuntu versions, installing supervisor via apt automatically enabled it, that does not appear to be the case on 16.04. I'm updating and testing the install scripts to ensure the service is enabled after it is installed.

**Comment by alecpm** [comment]
This should be fixed now.
