### ISSUE TITLE
newly published place demands authentication

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#133]
I have just recently published the following pages:

- http://pleiades.stoa.org/places/246984898
- http://pleiades.stoa.org/places/237861811

But when visited anonymously with a browser that is not logged in, the user is confronted with http://pleiades.stoa.org/acl_users/credentials_cookie_auth/require_login

I tried visiting ```@@caching-controlpanel-purge``` and entering one of the above URLs. I got a response indicating that various associated views had been purged, but this did not change the authentication behavior.

**Comment by paregorios** [comment]
I note that, though purging is enabled in the "caching proxies" tab on `@@caching-controlpanel`, the "place", "name", and "location" types are *not* selected in the "content types to purge" list box.

**Comment by davisagli** [comment]
@paregorios because Places are containers whose view aggregates multiple objects, they use the "content folder view" cache ruleset, which is associated with the "weak caching" operation. "Weak caching" allows proxy servers to store the resource, but requires that they validate it is up to date before serving the cached response to clients. So purging is not required.

I should double check how caching is working for locations and names. Can you add a new ticket for that since it's not really related to the authentication problem you reported here?

**Comment by davisagli** [comment]
The published state in the workflow used for places was not granting one of the necessary permissions for anonymous users to be able to view items. I'm not quite sure how that happened and/or why it wasn't a problem in Plone 3, but I fixed it to be in line with how Plone workflows usually manage that permission.

**Comment by paregorios** [comment]
This seems still to be happening on production, e.g. http://pleiades.stoa.org/places/386745968

Are we waiting just to deploy code updates, or is there something else going on?

**Comment by davisagli** [comment]
I didn't fix the permissions for any existing places aside from the two you mentioned. This is a place that was created some time ago so I guess we need to run a script to make sure the permissions are correct for all places.

**Comment by paregorios** [comment]
Alternatively, if you can teach me how to make the changes manually, I'll
make that part of the process of publishing items that have been hanging
around in the queue since before yesterday ...

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
The permissions should be set correctly for anything that changes to published after I made the fix. So the easiest workaround is to retract and then re-publish the item. Although that'll add extra entries in the history.

**Comment by alecpm** [comment]
We could use the update workflow permissions button from the ZMI to ensure all workflowed content has the appropriate permissions. That will take some time to run, and should probably be done at a low traffic time, but should address the issue if I understand it correctly.

**Comment by davisagli** [comment]
Yeah that's more or less the script I was intending to run.

**Comment by paregorios** [comment]
Honestly, I suspect there are not many (if any) additional places that have
been migrated to "published" since the fix was put in. If that's the only
factor, it may not be worth the trouble to try to hunt them down
comprehensively.

I am understanding this right, aren't I, that the issue is not the creation
date of the content item in question, but rather the date at which it was
transferred from "pending" to "published"?

Tom

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
That is correct, the date of transition to published would determine the current permission settings.

**Comment by paregorios** [comment]
OK, let's not worry about this further.
