### ISSUE TITLE
production is using wrong robots.txt

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#137]
A number of disallows are missing, plus there's no reference to the google sitemap.

**Comment by paregorios** [comment]
Here's what we used to have:

```
User-agent: *
Crawl-delay: 100
Disallow: /search
Disallow: /collections/
Disallow: /names/
Disallow: /features/
Disallow: /recently_modified
Disallow: /Members/sgillies/topic-testing/
Disallow: /Members/collections/
Disallow: /browse_names
Sitemap: http://pleiades.stoa.org/sitemap.xml

User-agent: XoviBot
Disallow: /

```

**Comment by paregorios** [comment]
We probably don't need the high crawl-delay any more, but the exclusions and the sitemap reference are still valid, it seems to me.

**Comment by davisagli** [comment]
Not quite sure what happened here...the file was still there in the root of the Plone site with the correct contents, and once I re-saved it it started serving the correct contents again.

**Comment by paregorios** [comment]
So, this is what I'm seeing now, which includes the sitemap reference:

```
$ !curl
curl http://pleiades.stoa.org/robots.txt
User-agent: XoviBot
Disallow: /

Sitemap: http://pleiades.stoa.org/sitemap.xml
```

I can't seem to find out where that's located on the production filesystem though. Can you point me in the right direction?

**Comment by paregorios** [comment]
Google claims they can't see it, which must be because of #139

**Comment by davisagli** [comment]
It's at http://pleiades.stoa.org/robots.txt/manage_workspace in the ZMI. That obviously has the full file. However when I first looked at it yesterday, and again today, the first part of the file was not being served. I added an initial blank line, resaved, and it ended up the same (no initial line) but started serving correctly...until it didn't again. Something weird's going on.

**Comment by paregorios** [comment]
I wonder if we were seeing some kind of caching artefact. In any case, curl just returned the right thing. I'll keep this file open so that I can check it again a few more times in coming days, but I'm pulling the priority label.

**Comment by paregorios** [comment]
I have been getting the correct file reliably for several days now via curl, and the Google webmaster tools (or whatever they're calling that functionality this week) is no longer complaining. Closing as resolved.
