### ISSUE TITLE
use New Relic to identify worst performance bottlenecks

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#138]
For example:
https://rpm.newrelic.com/accounts/1332365/applications/17811158/transactions#id=5b225765625472616e73616374696f6e2f5a6f7065322f76657273696f6e735f686973746f72795f666f726d2e7074222c22225d&app_trace_id=10fc6d8-cdc485b6-20b6-11e6-85b6-f8bc124250a8

**Comment by alecpm** [comment]
The credits page could perhaps use some optimizations as well:

https://rpm.newrelic.com/accounts/1332365/applications/17811158/transactions#id=5b225765625472616e73616374696f6e2f5a6f7065322f637265646974732e7074222c22225d&sort_by=slowest

**Comment by skleinfeldt** [comment]
On hold until after more story work.
