### ISSUE TITLE
apache conf currently denies even good bots

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#139]
Need to modify rewrite rules in https://github.com/isawnyu/pleiades-ansible/blob/master/templates/pleiades.stoa.org.j2 , which I will do shortly and submit a pull request.

**Comment by paregorios** [comment]
Please merge and deploy isawnyu/pleiades-ansible#4

**Comment by paregorios** [comment]
please merge isawnyu/pleiades-ansible#4

**Comment by davisagli** [comment]
Okay, deployed that.
