### ISSUE TITLE
Show drafting-state locations and names on Place pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#14]
To head off duplication of effort, we'll surface information about drafting-state content subordinate to a Place, but not allow traversal to the content itself.

This may be accomplished with little more than a little bit of permission tweaking.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/44, where it was originally opened by @sgillies

**Comment by atomrab** [comment]
I would consider this priority:high at this point.

**Comment by paregorios** [comment]
This was implemented with [Scrumdo Story 52](https://www.scrumdo.com/projects/project/pleiades/iteration/133485#story_1095151), which has been reviewed and deployed to production. Closing as resolved.
