### ISSUE TITLE
Prevent and remove \r\n from summary field on all content objects - 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#140]
ticket opened by @Jmuccigr in https://github.com/isawnyu/pleiades-dump/issues/4; migrated here. 

Some records in the dump have new lines inside fields. This is ok when you load the whole CSV as a spreadsheet in order to work on it, but it means that lots of command-line tools will have trouble with the file. For example, I was using grep to select entries that had a featureType of temple and the new lines meant that those entries got split mid-field.

For example, pleiades place 786059 has a new line in the description field, which shows up as \r\n in the json.

Any way to represent the new line in a different way inside fields in the dump to allow use of such tools? (It's not clear to me that the new lines are needed/desirable anyway.)

**Comment by davisagli** [comment]
The fields have newlines in them, and this is how newlines are represented in CSV (with the entire field contained in double quotes). My first inclination is to recommend using a tool that fully understands CSV to process CSV files, or alternately to run the file through a script to convert it to your desired format before working with it with other tools.

We could decide to dump the Python string literal representation of the field contents (which represents newlines as \n, etc) rather than the actual bytes stored in the field, but it'll be a backward incompatible change for other consumers of the dumps.

**Comment by Jmuccigr** [comment]
The newlines inside fields are so rare (I think I see 5), I thought they might be deprecated in the CSV (though of course that's one of the things the quotation of values is for). They don't seem to serve any obvious purpose that a space couldn't handle.

**Comment by davisagli** [comment]
Actually now that I think about it, newlines in the description get rendered as spaces when shown in HTML. So I don't see much downside to cleaning up those rare occurrences and adding a constraint on the description field to disallow newlines. I'll let @paregorios make the call as to whether to do that and where to prioritize this.

**Comment by paregorios** [comment]
I will hunt down and kill these cases manually.

**Comment by paregorios** [comment]
This has been reported again, by other users. It chokes the standard Java CSV reading library. Need to bump priority on a permanent fix.

**Comment by paregorios** [comment]
Now in work in https://github.com/isawnyu/PleiadesEntity/tree/issue140

**Comment by paregorios** [comment]
Blocked by #319

**Comment by paregorios** [comment]
I ran a batch update on all ~40 descriptions that contained a newline character to ensure that every whitespace sequence therein had been normalized to a single, plain space character. This should cleanup the CSV export the next time it runs (tonight), but it won't prevent the introduction of weird whitespace during user editing sessions. Therefore, this ticket remains open until we have expanded tests on PleiadesEntity content and have a mutator in place for the description field that polices whitespace.

**Comment by paregorios** [comment]
To do:

 - [ ] on changing the summary (description) field, run the filtering described below
 - [ ] write and run a whitespace normalization script over the summary fields on all content items in the plone such that:
      1. ```ur'\s+'``` gets replaced by a single space. 
      2. Leading and trailing whitespace is removed.

**Comment by alecpm** [comment]
Tasks:

* [x] Implement event handler that processes all `description` fields with a regex substitution to strip newlines and eliminate duplicate and trailing spaces.
* [x] Implement script to run above whitespace stripping on all `description` fields.
* [x] Run script on all content.

**Comment by alecpm** [comment]
This is deployed to staging, and the upgrade step has been run to update all content. It took about 63 seconds to run (and required disabling the memmon to prevent it from killing the instance running the script). I'm leaving the last task unchecked though, to save if for running the step on production.

**Comment by paregorios** [comment]
This looks good. Please merge to master, deploy to production, and run the upgrade step on production.

**Comment by alecpm** [comment]
The script has been run on production (95 seconds)

**Comment by paregorios** [comment]
Looks good! Thanks.
