### ISSUE TITLE
"site setup" appears twice in page header for authenticated users

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#141]
![screen shot 2016-05-26 at 10 07 35 am](https://cloud.githubusercontent.com/assets/263285/15579327/c4a50f2a-2329-11e6-92f0-8e25c50bc2ae.png)

**Comment by davisagli** [comment]
Which should stay?

**Comment by paregorios** [comment]
I think the one in the second line, between "dashboard" and "log out" should be kept, since those are all actions available only to authenticated users, whereas stuff in the top line should be available to anonymous.

**Comment by davisagli** [comment]
Cool, you picked the same one using the same logic as Plone's default. :) Fixed.
