### ISSUE TITLE
add bing ownership verification to ansible playlists

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#142]
In order for us to use Bing's Webmaster tools, we must return a particular file from this URI: `http://pleiades.stoa.org/BingSiteAuth.xml`. P3 production had this, but we didn't get it into the ansible playbook, so it needs to be added.

Note that the apache config file in the ansible playbook already has a rewrite rule that addresses this path. The `BingSiteAuth.xml` file needs to be placed at `/var/www/pleiades.stoa.org/BingSiteAuth.xml` on the production server.

**Comment by paregorios** [comment]
I'm taking ownership of this ticket, since to get the file in question I have to authenticate against the bing webmaster tools.

**Comment by alecpm** [comment]
Do we have a copy of this file somewhere?

**Comment by paregorios** [comment]
Let's not bother with this. It dates back to the pre-upgrade days when bots would routinely hammer us into 5xx land and I wanted to be able to tell Bing to back off. We haven't had a problem in years. Closing as "won't fix".
