### ISSUE TITLE
escapes and UTF8 in new JSON strings

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#144]
Our new JSON (as the old JSON) currently uses escape sequences for characters outside the base ASCII range (a default setting of [```json.dump```](https://docs.python.org/2/library/json.html#basic-usage) in Python). For example:

> "name": "Johan \u00c5hlfeldt"

These escapes are valid per [RFC 7159](https://tools.ietf.org/html/rfc7159#section-7); however, human readability would be enhanced if these characters were all rendered in pure UTF8 encodings without escapes (which is also valid per the RFC). Some defective JSON tools (e.g., https://jsonformatter.curiousconcept.com/) might also stop erroneously complaining that our JSON is invalid.

It's my impression that passing ```ensure_ascii=False``` to ```json.dump()``` ought to address this issue. Is this correct, or would we need to do something more time-consuming?

**Comment by alecpm** [comment]
I'll take this as it's a quick fix in the updated exporter.

**Comment by alecpm** [comment]
This should be fixed on staging. And the latest dump there should reflect the change.

**Comment by paregorios** [comment]
Both the JSON retrieved from /newjson URL slugs and the 2015-05-30 json dump on production still seem to be using escapes.

**Comment by paregorios** [comment]
@alecpm please disregard earlier comment; I was looking in the wrong place.

**Comment by paregorios** [comment]
This looks good on staging in both the JSON dump and the in the individual JSON resources returned from Pleiades URIs with the appended "/newjson" slug. Please deploy to production when convenient.

**Comment by davisagli** [comment]
This was deployed to production when I made the new json dump the default.
