### ISSUE TITLE
Time periods appearing in pick lists but not vocab page

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#15]
"Foo" and "Test" time periods show (for me) in the select list when editing a location, but not in http://pleiades.stoa.org/vocabularies/time-periods/view. It's confusing and a sure sign of other trouble.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/36, where it was originally opened by @sgillies

**Comment by paregorios** [comment]
Per third party developers, this is a bug associated with ATVocabularyManager, which most think we should ditch for something with better performance.

**Comment by atomrab** [comment]
And again, if @periodo can help with this by serving you back your own periods with URIs (which, incidentally, it would be great for us if you could actually implement in Pleiades), please let us know!

**Comment by paregorios** [comment]
All time periods in the vocab show up on the appropriate page in the upgraded P4 staging version of the site. Closing this issue. Note that issues #28 and #53 are relevant to time periods and remain open.
