### ISSUE TITLE
isaw1.atlantides.org urls are publicly browseable and google-bottable

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#150]
Is there any way we can prevent this? It's going to confuse users and muddle the google index.

**Comment by davisagli** [comment]
We could completely stop all access to domains other than pleiades.stoa.org, or we could let the server serve other domains that happen to point at it but set up robots.txt so that it will only allow indexing of the official domain. Any preference?

**Comment by paregorios** [comment]
I'd prefer that port 80 on isaw1.atlantides.org not be accessible from
outside at all. There used to be an uncached instance accessible from
atlantides.org on another port number for administrative purposes. This
still seems to be active and serves up a robots.txt as follows:

User-agent: *
Disallow: /

It seems to me that leaving the latter setup on the alternative port
number might be useful?



-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by alecpm** [comment]
I've setup a permanent redirect from any non "pleiades.*" domain hitting the default virtualhost to the canonical pleiades.stoa.org domain. So requests to http://isaw1.atlantides.org/... will all get a 301 to http://pleiades.stoa.org/...

**Comment by paregorios** [comment]
Looks great, thanks.
