### ISSUE TITLE
CSS problems on the insert/edit image dialog

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#151]
Layout of icons is wonky and form fields flow off and are truncated at the end of the dialog. 

It doesn't need to be pretty, but It's nearly useless at present.

**Comment by paregorios** [comment]
## steps to reproduce:

- edit an item with a rich text field
- select/focus rich text field and select the "insert/edit image" icon on the editor menu bar
- attempt to add and edit metadata about an image

##The following specific problems are noted: 

### Layout of icons for files and folders
Icons for files and folders are not tiled, they are presented in a single, vertical row, which wastes space and slows down selection and navigation:
![screen shot 2016-06-09 at 10 53 29 am](https://cloud.githubusercontent.com/assets/263285/15936396/7859bad2-2e30-11e6-836a-5055ee0b2a79.png)

### Layout of image metadata 
Once an image is selected, the various metadata entry/edit fields on the "Insert/Edit" dialog are also positioned in a single, vertical row (below the image, instead of to the right as one expects). To make matters worse, these buttons and text boxes (etc.) are oversized, and the overflow of the containing window (to the left?!?) is hidden. So you can't see the labels, can't find the buttons etc.
![screen shot 2016-06-09 at 10 54 30 am](https://cloud.githubusercontent.com/assets/263285/15936494/dc10ad4c-2e30-11e6-9633-7ac0a3790ba4.png)

**Comment by witekdev** [comment]
I've managed to make decent progress here using only css tweaks - worked on a branch here:
https://github.com/isawnyu/pleiades-notredame/commits/tinymce_plonebrowser_fixes
As things stand it is now in a usable state, though I will try to tweak it a bit more, then get it out to staging..

**Comment by paregorios** [comment]
sounds good. Please let me know @witekdev if you need any help from me.

**Comment by witekdev** [comment]
@paregorios tnx, will do if anything..

**Comment by witekdev** [comment]
I now have something I'm happy with, here are some screenshots:
![screenshot from 2016-06-10 22 03 12](https://cloud.githubusercontent.com/assets/883619/15983298/7d15eb40-2f57-11e6-8ac1-c06812095a1b.png)
![screenshot from 2016-06-10 22 03 17](https://cloud.githubusercontent.com/assets/883619/15983299/81a8d74e-2f57-11e6-98db-ec39ff5aaf5f.png)
![screenshot from 2016-06-10 22 03 38](https://cloud.githubusercontent.com/assets/883619/15983301/940a51c4-2f57-11e6-9fa7-4893172782f1.png)

**Comment by davisagli** [comment]
Hmm, that's definitely an improvement. But the out-of-the-box Plone styles for this dialog float the details panel on the right which I think looks better (those are some loooong fields) and avoids the vertical scrollbar. Maybe we can compare to those styles to see what we need.

**Comment by witekdev** [comment]
@paregorios ok nevermind my earlier screenshots, thanks to @davisagli who pointed out that we were missing some deco styles
https://github.com/plone/plonetheme.sunburst/blob/master/plonetheme/sunburst/skins/sunburst_styles/columns.css

after testing we now have:
![screenshot from 2016-06-10 22 31 33](https://cloud.githubusercontent.com/assets/883619/15983401/b463cfbe-2f5b-11e6-8e98-e6eba838cc72.png)
![screenshot from 2016-06-10 22 31 39](https://cloud.githubusercontent.com/assets/883619/15983402/b465be1e-2f5b-11e6-9e57-7d268dba94bc.png)
![screenshot from 2016-06-10 22 31 50](https://cloud.githubusercontent.com/assets/883619/15983403/b4673442-2f5b-11e6-801d-d6138b48ace1.png)

**Comment by witekdev** [comment]
@paregorios The fix is on staging

**Comment by paregorios** [comment]
I'm taking this ticket for review

**Comment by paregorios** [comment]
Perfect! Please deploy to production at your leisure.

**Comment by witekdev** [comment]
@paregorios deployed to production

**Comment by paregorios** [comment]
Thanks!
