### ISSUE TITLE
robots.txt intermittently returning 503

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#152]
My uptimerobot monitor has reported twice this morning short periods of the site "being down". it's specifically watching robots.txt. The error it reports is 503. Times are as follows:

- 8:26 am CDT to 8:29 am
- 11:47 am CDT to 11:48 am CDT

Can New Relic or log analysis tell us what is happening?

**Comment by alecpm** [comment]
It looks like some "web external" requests took a very very long time to return. This is almost certainly related to the Flickr portlet and delays in their API or issues with the server's connection to it. We could apply a shorter timeout to those requests to ensure they don't tie up a request thread for more than say 5 seconds (not displaying the portlet if we don't get a response in a reasonable amount of time) and possibly including some long-lived internal RAM caching of those responses, or we could try to move the API calls out to the client side, if possible. See:

https://rpm.newrelic.com/accounts/1332365/applications/17811158/externals#id=5b2245787465726e616c2f6170692e666c69636b722e636f6d2f616c6c222c22225d

**Comment by paregorios** [comment]
Right, Flickr is having problems this morning. Can we implement the shorter portlet timeout relatively quickly and cheaply, then at our next planning session do planning poker to estimate re-implementing our flickr functionality on the client side?

**Comment by alecpm** [comment]
I can do the timeout quickly.

**Comment by alecpm** [comment]
I've deployed a fix to staging that implements a timeout (2 seconds to connect, 5 seconds for data read) along with some better error and performance handling logging and some internal caching (two hour cache of valid responses). I also implemented similar updates in the pelagios portlet, to ensure pelagios API issues don't impact the site too much. Let me know if you see anything amiss in those portlets on staging. I'll deploy to production as soon as you give the go ahead.

**Comment by paregorios** [comment]
I'm marking this with the "review" label and taking it, since that seems to be what @alecpm was looking for me to do.

**Comment by paregorios** [comment]
This seems to be working on staging as I would expect from the user perspective. Please deploy to production at your leisure.

**Comment by alecpm** [comment]
This is live on production now, with @cguardia's suggested timeout improvements.
