### ISSUE TITLE
readme file was missing from the CSV downloads folder: find a way to prevent reoccurence

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#154]

**Comment by paregorios** [comment]
I have manually copied the file from the old server to the new server, so downgrading, but we probably want to find a way to manage this readme file under version control, either in the ansible buildout or the CSV export module. Downgrading to medium priority now that we've eliminated the near-term probabiliyt of 404s for this.

**Comment by cguardia** [comment]
I'm sorry, I don't know which file we are talking about. Can someone point me to it?

**Comment by davisagli** [comment]
/var/www/atlantides.org/downloads/pleiades/dumps/README.txt

**Comment by cguardia** [comment]
This looks like the same README in pleiades.dump. I added a symlnik to it in the ansible deploy file. Does that sound reasonable?

**Comment by davisagli** [comment]
That sounds reasonable to me. Can you make sure it deploys cleanly to production?

**Comment by cguardia** [comment]
Is there no VagranFile for locally testing it? Should I add one?

**Comment by davisagli** [comment]
You can test by deploying to staging. But the case I'm concerned about is when the file already exists as an actual file rather than a symlink, so I guess you should create one in the same location on staging before testing.

**Comment by cguardia** [comment]
Tested with an existing file. Needed a force flag, but works now.

**Comment by paregorios** [comment]
so, @davisagli and @cguardia, are we confident this works on production?

**Comment by davisagli** [comment]
Yep, looks like it's in place on production.
