### ISSUE TITLE
misleading status codes for bad web requests

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#155]
@rmhorne reports that our web server provides varying and idiosyncratic responses to some forms of "bad" HTTP requests:

> For instance, http://pleiades.stoa.org/places/3100:32:00/json (obviously something went screwy with the data) leads to a 404 splash page, while something like http://pleiades.stoa.org/places/foo/json leads to a different error page (a 410 result). From more testing, it seems that numeric junk values generate a 404 while text junk generates a 410.

I think it should be our goal that a request for a non-existent PID value in an ```http://pleiades.stoa.org/places/``` URI (that has not been redirected to ```http://pleiades.stoa.org/errata/*``` in the plone) should return 404, regardless of the kind of characters appearing in the PID space.

My guess is that this is caused by an over-greedy rewrite rule in our apache config, aimed at stopping bots from excursions to early-days portions of our web structure. We ought to investigate this theory (and also whether that cruft is still there in the plone) and make a cleanup plan.

**Comment by davisagli** [comment]
Yeah, there was an apache rule to return a 410 Gone response for any /places/ URL starting with a non-digit. I removed the rule so it now returns a 404.

**Comment by davisagli** [comment]
There are also rules to return a 410 for URLs starting with `/names`, `/locations`, and `/join_form`. Should these go too?

**Comment by davisagli** [comment]
Looks like `names` and `locations` don't exist anyway, and the registration form is at a different URL in Plone 4. So I'll remove those. But maybe you want to block `/@@register` instead of join_form?

**Comment by paregorios** [comment]
Everything you've done and suggested sounds good. Yes, we do want to block
/@@register instead of join_form. But what's the right response?

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Never mind, I was confused because I was logged in as an admin so could load the registration form. It's already blocked for logged-out users (raises Unauthorized which causes Plone to show the login form instead).

**Comment by paregorios** [comment]
Perfect.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott
