### ISSUE TITLE
copyright symbol getting erroneously escaped on editing

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#156]
after an edit to a place, name, location, etc. the existing (or default for new items) rights statement has a borked character entity. One sees in the browser: 

> Copyright `&#169;` The Contributors. Sharing and remixing permitted under terms of the Creative Commons Attribution 3.0 License (cc-by).

instead of
> Copyright &#169; The Contributors. Sharing and remixing permitted under terms of the Creative Commons Attribution 3.0 License (cc-by).

**Comment by witekdev** [comment]
What is perplexing me here is that when you edit the borked place, name, location etc and update the `&#169;` to a © manually, the place, name, location etc is no longer borked, upon the following edit attempt, the © is present and happy.

I manually unborked this place on staging:
http://pleiades.jazkarta.com/places/1000

While I don't understand the cause, my initial thought is that perhaps we could write a script to manually unbork all objects somehow? ie. resave the objects with the correct rights field, though I don't know if that would work. @alecpm thoughts?

**Comment by davisagli** [comment]
> What is perplexing me here is that when you edit the borked place, name, location etc and update the &#169; to a © manually, the place, name, location etc is no longer borked, upon the following edit attempt, the © is present and happy.

From what I recall from fixing this on staging, the field is correctly saving input with a utf-8 encoding. The problem is that the default value is stored in the `portal_metadata` tool with a different encoding.

**Comment by paregorios** [comment]
@witekdev I think @davisagli is referring back to issue #73.

**Comment by witekdev** [comment]
ok, I went into portal_metadata and updated the default rights field.
I'm not sure why but when you hit save the © symbol is prepended with an `Â`:
![screenshot from 2016-08-09 09 44 06](https://cloud.githubusercontent.com/assets/883619/17520753/7a4c891c-5e16-11e6-998d-84c385fe947d.png)

This also didn't help existing objects which if I edit, I still get the `&#169;` popping up.
@davisagli can you remember what you did to make https://github.com/isawnyu/pleiades-gazetteer/issues/73 work?
Do we need to regardlessly run a migration script and update all the existing objects that have the rights property stored on them?

**Comment by davisagli** [comment]
`Â©` is actually the correct utf8-encoded value (`\xc2\xa9`) being interpreted in the wrong encoding for this UI. Let's not worry about that because new Archetypes items appear to be showing the value correctly now. You're right that we need a script if we want to automate fixing existing items that got the wrong default.

**Comment by witekdev** [comment]
ok, thanks, so I will go ahead and write and test an update script..

**Comment by witekdev** [comment]
@paregorios I created and ran the script to update all place, name, connection and location objects on staging. Let me know if things are ok and I will run it on production.

**Comment by paregorios** [comment]
@witekdev I'm not sure the script is catching everything. Consider, for example: http://pleiades.jazkarta.com/places/579885

**Comment by witekdev** [comment]
@paregorios ok, I think I know what's up. The script as it stands won't actually fix the existing rights field if it is 'borked'. It only re-saves what is there. An omission on my part.

**Comment by witekdev** [comment]
@paregorios fixed and reran the script on staging.

**Comment by paregorios** [comment]
@witekdev that looks good. Please run the fix on production.

**Comment by witekdev** [comment]
@paregorios the script has been run on production

**Comment by paregorios** [comment]
great, looks good!
