### ISSUE TITLE
connection lists in place views should be sorted alphabetically by title: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#157]
Right now they seem to the user to have an arbitrary order, see e.g., sub "Has a connection with" on http://pleiades.stoa.org/places/579885

**Comment by jessesnyder** [comment]
I have learned that they are sorted by the Title() of the Place you're looking at, which in this case is of course the same for every connection. I suspect there's some other context where this listing generation is used where the sort makes sense (at least I'm _afraid_ that could be true). 

I'll try to make a revised sort that's scoped to this context.

**Comment by paregorios** [comment]
This looks great on staging. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
Please deploy to production.

**Comment by paregorios** [comment]
This looks great on production!
