### ISSUE TITLE
sort time periods by "lower" value (ascending)

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#160]
In legacy production, the time periods pick widget sorts periods by their start date so that users can find the right period intuitively. In the new implementation on production, there is no obvious sort order in the pick widget. We need to reimplement sorting by state ("lower") year in the pick widget.

**Comment by paregorios** [comment]
This sort rule has also been lost from the time periods listings on "location" and "name" base views and needs to be put back.

**Comment by cguardia** [comment]
Forgot to say this is on staging already.

**Comment by paregorios** [comment]
looks good
