### ISSUE TITLE
cannot delete a time period in @@pleiades-settings

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#162]
It's not clear how to do this. See below.

**Comment by paregorios** [comment]
The "delete row" icon (a yellow minus sign) appears along with the "add row" icon (a yellow plus sign), but they are not linked nor are they associated with any sort of javascript.

**Comment by davisagli** [comment]
@cguardia you probably know this, but this sounds like we just need to activate the js for collective.z3cform.datagridfield

**Comment by cguardia** [comment]
As @davisagli said, the datagrid field was not installed on the site. Fixed and added upgrade step to avoid this issue in the future.

**Comment by paregorios** [comment]
Works great!
