### ISSUE TITLE
update "downloads" page to point to JSON exports

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#166]
Now that we have working JSON exports, we should point people to them from the downloads page.

**Comment by paregorios** [comment]
Please review, merge, and deploy to staging.

**Comment by davisagli** [comment]
Deployed to staging. Sorry, I overlooked that there was a pull request here.

**Comment by paregorios** [comment]
Looks good on staging. Please deploy to production.

**Comment by davisagli** [comment]
done
