### ISSUE TITLE
(Re-)enable CORS for JSON requests

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#170]
From @hcayless, migrated from https://github.com/isawnyu/pleiades-json/issues/1:

> Pleiades used to permit cross-origin requests for JSON data until quite recently. It seems to have stopped though. If this isn't a policy decision, can you enable CORS again so other sites can load json form Pleiades via a browser-based request?

**Comment by skleinfeldt** [comment]
@davisagli will take a look shortly

**Comment by davisagli** [comment]
Sorry, didn't realize we were setting `Access-Control-Allow-Origin: *` in the old JSON view, so failed to duplicate it for the new one. It should be there now.

**Comment by paregorios** [comment]
fixed per @hcayless
