### ISSUE TITLE
new-style connections have "all_powerful_Oz" as creator

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#179]
I would prefer something more pedestrian, like "Admin". 

![screen shot 2016-07-05 at 8 54 21 am](https://cloud.githubusercontent.com/assets/263285/16586987/1c00bc82-428e-11e6-8653-d70aee3bdfd3.png)

**Comment by skleinfeldt** [comment]
Nice.

**Comment by davisagli** [comment]
I adjusted how the migration script sets itself up with a Manager-level user so that it uses the real "admin" user rather than a fake one. I'm not going to re-run the migration on staging, but the change is in place for when we run it in production.
