### ISSUE TITLE
Users are unable to delete their drafting-state Locations and Names

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#18]
The issue is that Plone uses a single permission to guard both whether you can can call a method of the parent object to delete content and whether this method can delete the particular child content object. We can't usefully widen the roles for the "delete object" permission without opening the place objects themselves up to deletion.

Solution: add a new "PleiadesEntity: Remove Child Object" permission to Products.PleiadesEntity, reimpl Place.manage_delObjects, and update our workflow. An hour or so of coding, maybe another hour to reindex our existing drafting-state content and update their permissions.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/30, where it was originally opened by @sgillies.

**Comment by davisagli** [comment]
https://pypi.python.org/pypi/collective.deletepermission is a Plone add-on that provides a similar solution in a ready-made package. Probably needs a bit of integration with your workflow.

**Comment by davisagli** [comment]
It looks like @alecpm prepared the update to add collective.deletepermission in https://github.com/isawnyu/pleiades-policy/commit/f0cd9a0bd09c7a2a35d35133b2b1ca88975630d5, but it has not been activated on production. @alecpm, is that intentional or an oversight?

**Comment by davisagli** [comment]
@paregorios it turns out that Alec implemented a fix for this, but missed a step in deploying it. That's now taken care of on staging, so please test there.

**Comment by paregorios** [comment]
I can confirm (with a test user in the Members group) that this is working on staging. Please deploy to production.

**Comment by davisagli** [comment]
I made the same change in production.

**Comment by paregorios** [comment]
Something has regressed here, or my initial test was confused. On neither staging nor production is an authenticated user who is only in the Member group able to delete a place or a name that she has created. The "delete" option does not appear in the "actions" menu item. Here are some examples, created with the auser user:
- https://pleiades.jazkarta.com/places/52124298/
- https://pleiades.jazkarta.com/places/844967/name.2016-11-02.8627985044
- https://pleiades.stoa.org/places/844967/name.2016-11-02.7521359840

I also note that friendly slug creation for names (from the romanized form) now seems to be broken(?).

**Comment by davisagli** [comment]
Try now (on staging, not production yet). For some reason the "Delete objects" permission (which newly means "can delete items in this folder if I also have the 'Delete portal content' permission on those items) was not granted to all the roles it should be as specified in Alec's update.

**Comment by paregorios** [comment]
This works great on staging now. I have tested adding and deleting places, names, and locations. Please deploy to / implment on production.

**Comment by davisagli** [comment]
Okay, should be all set on production.

**Comment by paregorios** [comment]
Confirmed: this is rock and roll and disco on production.
