### ISSUE TITLE
aggressive bot problems

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#180]
all plone-served pages were throwing 503s for several minutes this evening

**Comment by paregorios** [comment]
This resolved after a few minutes. Examination of New Relic (and an assist from @witekdev and @davisagli) pointed us to the the KML view of search. @davisagli opined:

> so it's probably no more complicated than that someone tried to load the KML view of search results that included many results, and since it was slow they clicked a few more times and then started it running on the other instances too

Examination of apache logs revealed a series of likely expensive requests for kml and search views of kml for prolific users. These all emanate from a single IP (associated with an ISP in Montreal) that is switching between multiple (evidently spoofed) browser user-agent strings. Bad bot.

We need a way to quickly ban, tarpit, or otherwise insulate ourselves against bad actors like this.

**Comment by paregorios** [comment]
It occurs to me that the addition of a crawl-delay directive to robots.txt (for good actors), combined with some fail2ban rules (for bad actors) could go a long way here. But I think we may want also to see if there is a way to protect ourselves down inside search. Some tasks:

- [ ] add crawl-delay directive to robots.txt (I'll issue a pull request for this)
- [ ] engage tummy to add apache log monitoring to our fail2ban setup and configure it to address cgi and php script sniffing, crawl-delay ignoring, known bad-bot user agents, and a hard-coded IP blacklist (I'll undertake this)
- [ ] development team to look at search on the plone side to see if we can do anything to optimize or compartmentalize expensive requests

**Comment by paregorios** [comment]
I can't find robots.txt in pleiades-ansible. Is it under configuration control somewhere else, or are we just managing it on the server filesystem?

**Comment by davisagli** [comment]
Sounds good. I didn't realize that fail2ban could also monitor apache logs; that sounds useful.

robots.txt is in the database, here: http://pleiades.stoa.org/robots.txt/manage

**Comment by paregorios** [comment]
@davisagli I tried modifying robots.txt through the plone. I added a single line for the crawl-delay directive so that in the browser it looks like this:

![screen shot 2016-07-07 at 10 41 54 am](https://cloud.githubusercontent.com/assets/263285/16659401/7a3f4348-442f-11e6-9da8-36ac586fa9a1.png)

After cache was successfully purged, it looks like the introduction of that line is somehow/why causing part of the file to be interpreted as response headers instead of robots.txt file content. 

Headers:

```
$ curl -I http://pleiades.stoa.org/robots.txt
HTTP/1.1 200 OK
Date: Thu, 07 Jul 2016 15:39:57 GMT
Server: Zope/(2.13.23, python 2.7.11, linux2) ZServer/1.1
Content-Length: 79
Crawl-Delay: 3
Disallow: /browse_names
X-Frame-Options: SAMEORIGIN
User-Agent: *
Content-Type: text/plain; charset=utf-8
X-Varnish: 2956580 3256145
Age: 25
Via: 1.1 varnish-v4
X-Varnish-Cache: HIT
Accept-Ranges: bytes

```

file content as served:

```
$ curl http://pleiades.stoa.org/robots.txt
User-agent: XoviBot
Disallow: /
```

Thoughts?

**Comment by davisagli** [comment]
We saw this before. Add a newline at the top of the file. I really have no idea why that's necessary.

**Comment by paregorios** [comment]
@davisagli thanks that's got it

**Comment by alecpm** [comment]
I've had a lot of luck dealing with similar issues using nginx's built-in rate limiting on other projects, and there appear to be some similar plugins for apache and varnish.

http://opensource.adnovum.ch/mod_qos/
https://codepoets.co.uk/2015/varnish-throttling/

Not sure how easy either of these would be to integrate into our ansible setup (I suspect the apache one would be more straightforward though).

**Comment by paregorios** [comment]
We haven't seen a recurrence, so lowering priority.

**Comment by paregorios** [comment]
We've been running iptables and fail2ban on the production server for a while. When we run into an aggressive bot that ignores robots.txt, we can ask tummy to make adjustments to deal with the problem. I regard this issue as resolved, so closing.
