### ISSUE TITLE
Link to "Pelagios Datasets" broken

### ISSUE THREAD

**Issue by sfsheath** [isawnyu/pleiades-gazetteer#181]
Looks like template has a link to "Pelagios Datasets" with URL http://pelagios.dme.ait.ac.at/api/datasets . That's 404'ing. This might be current(??): http://pelagios.org/peripleo/pages/datasets .

**Comment by paregorios** [comment]
It's the hard-coded(?) link at the bottom of the portlet. 

@rsimon can you confirm that http://pelagios.org/peripleo/pages/datasets is now the canonical link for the Pelagios datasets listing?

**Comment by rsimon** [comment]
Yes, that's now the official one. The page will change when I get to revising Peripleo, but the URL will stay.

**Comment by paregorios** [comment]
I've made what I think is [the necessary change](https://github.com/paregorios/pleiades.portlet.pelagios/commit/abc3727e4a26ecfe1af8e092e9593042375f8e2e) in a personal fork of pleiades.portlet.pelagios. 

@skleinfeldt would you please ask a developer to do code review and let me know if there's anything else I should address before issuing a pull request?

**Comment by skleinfeldt** [comment]
@paregorios please go ahead and issue the PR, and @ mention David and Alec to review it. A PR is their preferred context for doing a code review. Thanks!

**Comment by davisagli** [comment]
I merged and deployed the change.

**Comment by paregorios** [comment]
Confirmed this is working on production. Closing as resolved. Thanks.
