### ISSUE TITLE
404s on missing images

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#182]
Loading a place makes a few requests for images that are not found; we should fix these or remove the references to the images so the server doesn't have to spend time serving these 404s.

![screen shot 2016-07-10 at 2 57 27 pm](https://cloud.githubusercontent.com/assets/49014/16716348/b831e9fe-46ae-11e6-88bc-4125d55808a6.png)

**Comment by paregorios** [comment]
also linktransparent.gif

**Comment by witekdev** [comment]
Fixed. the missing gifs have been added. Deployed to production and staging.
If we happen to be missing other older Plone gifs in the future, this is where I sourced them from: 
http://www.oces.okstate.edu/template12/ploneimages/images-in-plone

**Comment by paregorios** [comment]
looks good, thanks
