### ISSUE TITLE
authenticated Members receive "insufficient privileges" error on checkout

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#183]
This seems to be happening on any published place. For example:

- http://pleiades.stoa.org/places/462086
- http://pleiades.stoa.org/places/658587
- http://pleiades.stoa.org/places/550911

This problem, reported by a user, has been verified with a test user account with only the Member role assigned (our standard procedure for new users):

![screen shot 2016-07-11 at 10 03 12 am](https://cloud.githubusercontent.com/assets/263285/16735484/cde600f0-474e-11e6-865c-862cbf63941e.png)

Editors and Managers are not reporting this problem. No additional information is provided in the user interface other than the generic "insufficient privileges" notice.

**Comment by alecpm** [comment]
Looking at permissions, currently on both staging and production normal Members do not have the check-out/check-in permissions. Should this permission be granted to Members globally (on all content in any review state) or should it be allowed for Members only for specific content in specific workflow states?

It's not clear to me what changed when here, as I'm not seeing any recent importStep runs or code changes that appear to relate to this problem.

**Comment by alecpm** [comment]
The workflow changes and permissions updates are complete on staging. Please review.

**Comment by paregorios** [comment]
@alecpm This looks good to me, and I'd like to see it deployed to production. Note the comment I just added on related [Scrumdo Story #58](https://www.scrumdo.com/projects/story_permalink/1096403).

**Comment by paregorios** [comment]
@alecpm to clarify, I'd like to have the changes associated with this issue deployed at the earliest possible moment (we have some power users waiting). I'd rather work the outstanding questions with [Scrumdo Story #58](https://www.scrumdo.com/projects/story_permalink/1096403) separately (unless there's a good technical reason otherwise, of course).

cc @skleinfeldt

**Comment by paregorios** [comment]
It appears to me that this has been deployed to production. @alecpm can you confirm? @skleinfeldt

**Comment by alecpm** [comment]
Yes, I deployed yesterday morning and ran the migration in the evening.
