### ISSUE TITLE
place types are no longer sorted

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#185]
Formerly, the place types vocabulary was sorted alphabetically in the pick list on the edit view for place and location. When the new backend was rolled out, they no longer were. 

It would be helpful if they were sorted similarly in these other two contexts:

- http://pleiades.stoa.org/vocabularies/place-types
- @@pleiades-settings

cc @serviliusahala

**Comment by davisagli** [comment]
Heh, I noticed this yesterday, fixed it, and then promptly forgot to deploy. The fix is there now.

**Comment by paregorios** [comment]
super duper thanks
