### ISSUE TITLE
"hiding" doesn't work on place types

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#186]
The new @@pleiades-settings backend for the place types vocabulary includes the "hidden" option, but when selected, the corresponding term still shows up in the pick list on place and location edit views. Consider the following example, taken live from production.

**in @@pleiades-settings**

![screen shot 2016-07-12 at 9 44 47 am](https://cloud.githubusercontent.com/assets/263285/16771223/4e83dae0-4815-11e6-9859-515f4405c041.png)

**in pick list for http://pleiades.stoa.org/places/529754544**

![screen shot 2016-07-12 at 9 43 15 am](https://cloud.githubusercontent.com/assets/263285/16771268/767ceae6-4815-11e6-9ea6-9c8368e501fc.png)

**Comment by davisagli** [comment]
I completely forgot that for time periods this is enforced in a customized widget, and we need a similar customization to the widget for place types.

**Comment by witekdev** [comment]
I guess this will also need to be updated for the relationship types and the upcoming location types vocab widgets as they too include the "hidden" field?

**Comment by davisagli** [comment]
@witekdev We said this morning that we don't need the 'hidden' flag for the location types vocab. But you're right, since we're making it available for relationship types we should probably make it work.

**Comment by witekdev** [comment]
@davisagli I guess I must have missed that detail. Tnx!

**Comment by davisagli** [comment]
This is fixed (in production).
