### ISSUE TITLE
place URIs without trailing slash sometimes returning 406

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#188]
This problem is intermittent (but frequent) since the deployment of the new-style connections code. Discussion from chat:

> @davisagli: doh, error at http://pleiades.stoa.org/places/560221
@paregorios: yeah, I noticed that behavior; without trailing slash, we’re seeing that now
@davisagli: no, that one doesn't work with or without the slash
@paregorios: honestly, I thought there was a rewrite rule in our apache conf to catch those
@paregorios: ah, you get an error number with the slash tho
@paregorios: without the slash on several other places is now throwing 406
@alecm: That's an actual error, but I did get the content negotiation message of the page, which seems super weird.
@paregorios: well, or not
@paregorios: it seems inconsistent to me
.
.
.
@alecm: It's very strange that the trailing slash issues seems to go away on reload sometimes. Maybe one or more instances is out of sync?
@cguardia: seems like that's the case
@cguardia: but the deploy should restart all, no?
@alecm: If I reload this http://pleiades.stoa.org/places/560221 a few times, sometimes I get an error sometimes I get a 406.
@alecm: It should, unless something has changed, probably a good idea to look in supervisor to see if they all were actually restarted around the same time.
@cguardia: they were

**Comment by davisagli** [comment]
The issue with 560221 in particular is completely unrelated to both content negotiation and this morning's deployment. The error is "No gridsquare c5 in map 60"

**Comment by paregorios** [comment]
downgraded to priority "low" since we can't get the problem to recur at the moment

**Comment by davisagli** [comment]
The intermittent 406 problem is fixed. One detail of the cache configuration hadn't been deployed correctly, so cached responses for a different content type were being served from some zope instances' RAM caches.

**Comment by alecpm** [comment]
There's still an open question of what was triggering the 406's in the first place (causing them to be cached). I've added logging to help determine that going forward if it comes up again.

**Comment by paregorios** [comment]
@alecpm should we leave this ticket open (with lower priority), or go ahead and close?

**Comment by paregorios** [comment]
downgrading priority pending response from @alecpm @skleinfeldt

**Comment by skleinfeldt** [comment]
@paregorios it should be closed as far as I can tell.
