### ISSUE TITLE
A dedicated maintenance Plone instance is needed for catalog rebuilds, etc

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#19]
The problem: our site's catalog is too big to be rebuilt or even partially reindexed while the site is in production. It takes hours and the transaction size is very big and will almost certainly conflict with user transactions.

The solution: we need a completely separate Plone instance, one not upstream from the Pleiades load balancer, to which we'll copy the production Data.fs for maintenance (catalog rebuilds, migrations, etc).

TBD: Can we copy a Data.fs back and forth between the production ZEO server and a maintenance file storage? Or do we need a ZEO server for the maintenance Plone.

Notes:
http://plone.org/documentation/faq/plone-zeo-read-only-mode
http://developer.plone.org/persistency/database.html

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/21 where it was originally opened by @sgillies.

**Comment by paregorios** [comment]
What's Jazkarta's thinking on this issue?

**Comment by davisagli** [comment]
Not needed. For a site this size we try very hard to avoid complete catalog rebuilds, and if significant reindexing is necessary we can run it using one of the existing instances in "run" mode which just runs a script without binding to the http interface.
