### ISSUE TITLE
meta tag for description is repeated in place views

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#191]
With the rich metadata upgrade now on staging ([Scrumdo Story #62](https://www.scrumdo.com/projects/story_permalink/1096491)), there are currently two `<meta>` elements getting generated for each place view. We only want one (the most expressive, new one). See, for example, the base view for the [Acropolis of Athens](http://pleiades.stoa.org/places/638356144):

```
<meta content="The acropolis of the ancient city of Athens in Greece." name="description">
```

and 

```
<meta property="og:description dcterms:description schema:description" name="description" content="The acropolis of the ancient city of Athens in Greece.">
```

Zotero, for example, concatenates all of the `<meta name="description">` elements it finds. We should get rid of the old (first) type and keep the newer (second) one, which has all the Open Graph, Dublin Core, and Schema.org goodness as well.

**Comment by witekdev** [comment]
Looks like this <meta content.. line is being generated by the DublinCoreViewlet.
plone.app.layout.viewlets.common.py

```
class DublinCoreViewlet(ViewletBase):
    index = ViewPageTemplateFile('dublin_core.pt')

    def update(self):
        plone_utils = getToolByName(self.context, 'plone_utils')
        context = aq_inner(self.context)
        self.metatags = plone_utils.listMetaTags(context).items()
```

@paregorios even though you pointed out that this is happening on places urls, I see it's also happening on locations: http://pleiades.stoa.org/places/638356144/imagery-location as well as on the home page: http://pleiades.stoa.org/home (and likely elsewhere but I didn't check)
Can you clarify that you want this behavior/bug gone from all urls or just from place urls specifically?

@davisagli or @alecpm or @cguardia 
Can you advise me as how to best suppress an existing plone viewlet? Can one just disable it somewhere or do I need to override it in code? Thanks!
I'm assuming that we do **NOT** want to use the ZMI for this:

![manage_main](https://cloud.githubusercontent.com/assets/883619/17087119/609210de-51b7-11e6-8dec-35047a5a8e00.jpg)

**Comment by paregorios** [comment]
@witekdev yes, I'd like this gone everywhere it's occurring.

Would it be easier/better to fold the new behaviors into the dublin core viewlet and eliminate the duplication there, thereby getting the richer metadata experience for all (or mostly all) content views?

**Comment by skleinfeldt** [comment]
If you wanted to suppress this everywhere, an easy option would be turning off Dublin Core behavior on Site Setup.

**Comment by alecpm** [comment]
@witekdev, as sally mentions you can turn off the DC metadata in the control panel. We would then possibly need to add back whichever tags might be needed in our own viewlet.

An alternative would be to remove the name="description" attribute from the new meta tag, so that there are still two description meta tags, but they don't overlap in purpose. One for the HTML description and another for the og, dc, and schema descriptions.

**Comment by witekdev** [comment]
@paregorios fix deployed to staging

**Comment by paregorios** [comment]
During standup discussion today, we spotted an additional `<meta name="description">` tag and also an additional `<title>` tag that we agreed should be got rid of in favor of our custom ones. @witekdev and @davisagli, did I miss any additional aspects of that discussion?

**Comment by witekdev** [comment]
@paregorios I think that was it. I'm still on the hunt for the source of those..

**Comment by davisagli** [comment]
I think the title comes from title.pt in plone.app.layout/viewlets

**Comment by witekdev** [comment]
@davisagli you are right, thanks! now on to hunt down the extra meta tag..

**Comment by witekdev** [comment]
Ok, so strangely, the extra meta content=.... name="description" > tag is not present on production:
http://pleiades.stoa.org/places/874665
but is present on staging:
http://pleiades.jazkarta.com/places/874665
for the same place resource.
and I grabbed a copy of production today and running it locally now, so I cant see it happening locally.. hmm, /me needs a new strategy here..

**Comment by davisagli** [comment]
@witekdev Oh man, I found it. staging had a copy of dublin_core.pt that was customized in portal_view_customizations, so that was taking precedence over your override on staging only. It was created 3 days ago, so must have been from one of us trying to work on this. I just deleted it.

**Comment by witekdev** [comment]
@davisagli well that is music to my ears, thanks! :)
@paregorios I released this to production now, as hopefully it is done but let me know if you see anything else that's not right.

**Comment by paregorios** [comment]
review on production

**Comment by paregorios** [comment]
great!
