### ISSUE TITLE
assertion error while importing relation from OSM

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#194]
@serviliusahala reported error number 1469578736.670.934644700953 while attempting to import a relation from OpenStreetMap at http://pleiades.stoa.org/places/138340/@@create-location-osm

The following traceback may be found in the instance5 log:

```
2016-07-26T20:18:56 ERROR Zope.SiteErrorLog 1469578736.670.934644700953 http://pleiades.stoa.org/places/138340/@@create-location-osm
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.PleiadesEntity.browser.osm, line 67, in __call__
AssertionError
```

**Comment by davisagli** [comment]
What OSM relation did he try to import?

**Comment by paregorios** [comment]
@serviliusahala can you give us the relation number of what you tried to import from OSM?

**Comment by davisagli** [comment]
Found it in /error_log; it was 1075830

**Comment by serviliusahala** [comment]
I was attempting to import this OSM relation: http://www.openstreetmap.org/relation/1075830

**Comment by davisagli** [comment]
This is a complex relation representing a stream, which references other relations as tributaries (as well as a "spring" node and "side stream" way) and includes them in the xml. I need to make the importer a bit smarter to pick the correct relation from the xml when there are multiple.

Am I correct in thinking you only want to import the geometry for the main stream, and not the tributaries?

**Comment by serviliusahala** [comment]
From my point of view, the main stream of a river or stream is the geometry we would most want to import from OSM.

**Comment by davisagli** [comment]
Fixed. Importing a relation of type waterway from OSM should now work -- at least it does for this one.

Waterways are definitely a case where the way we currently show geometry on the map (with the convex hull containing the geometry rather than the geometry itself) looks odd.

**Comment by paregorios** [comment]
@serviliusahala please see what you think about the behavior of this sort of thing now

**Comment by paregorios** [comment]
@serviliusahala would you care to give this a try and let us know how it goes for you?

**Comment by serviliusahala** [comment]
The performance of importing relations via OSM seems good to me. My most
recent successful attempt is this one:
https://pleiades.stoa.org/places/438803/osm-location-of-gallicano-nel-lazio

A great addition to Pleiades' functionality, IMHO.

best,

JAB

# 

Jeffrey A. Becker, Ph.D. RPA
Department of Classical and Near Eastern Studies
Binghamton University - SUNY
jeffrey.becker@gmail.com; 617-877-4484
Twitter: @servilius_ahala https://twitter.com/servilius_ahala

#

**Comment by paregorios** [comment]
thanks @serviliusahala. Closing as resolved.
