### ISSUE TITLE
post-deployment of story 66: missing connections in place maps 

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#195]
[Scrumdo story 66 (use representative point for position of all connections on place maps)](https://www.scrumdo.com/projects/story_permalink/1097310) has been marked as having been "deployed" to production. I would have expected the place maps on production to match those on staging with regard to connections, but they don't seem to (even after reload/refresh). For example, compare http://pleiades.stoa.org/places/579888 to http://pleiades.jazkarta.com/places/579888.

**Comment by davisagli** [comment]
They do look the same to me, Tom.

**Comment by alecpm** [comment]
I had missed a version pin update on one of the packages, I've deployed that change and cleared the cache.

**Comment by paregorios** [comment]
Great, thanks!
