### ISSUE TITLE
new anchors not showing up as link targets in editor

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#197]
_This bug is blocking needed documentation updates._ 

I edited [an existing document](http://pleiades.stoa.org/help/editorial-guidelines) using the through-the-web editor to add some anchors to it. Saved. I created [a new working copy of a different existing document](http://pleiades.stoa.org/help/copy_of_how-to-add-a-new-name-resource), made some text changes, and used the link-helper widget in the through-the-web editor to create site-internal links to some of the anchors in the first document. Saved. Worked great.

I went back to the first document, edited, and added another anchor. Saved. I went back to my working copy of the second document, edited, and tried to use the same procedure to add a site-internal link back to the newly-created anchor in the first document. But that anchor doesn't show up in the list of options. Waiting didn't help. Saving again didn't help. Canceling and retrying didn't help. 

Anchor is in the first document:

![screen shot 2016-08-02 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/263285/17347585/786f97a0-58d6-11e6-9b20-a5e0a38fc792.png)

Anchor does not appear in the pick list for internal links in the editor for the other document:

![screen shot 2016-08-02 at 5 27 36 pm](https://cloud.githubusercontent.com/assets/263285/17347592/7f29ebae-58d6-11e6-8280-fb315eb04d24.png)

**Comment by witekdev** [comment]
@paregorios 
I am seeing the 'names-certainty' in the dropdown when trying to edit your working copy:
http://pleiades.stoa.org/help/copy_of_how-to-add-a-new-name-resource

![untitled-1](https://cloud.githubusercontent.com/assets/883619/17386295/db6d9ebe-59ae-11e6-9141-007954bb47f0.jpg)

Can you check again?

**Comment by witekdev** [comment]
I wanted to add that I followed your exact methodology/procedure with my offline copy of production and was expecting it to fail on the '2nd pass' but it did not. I then went and looked at the respective pages on production and could see 'names-certainty' in the drop down as described above.

**Comment by paregorios** [comment]
I'm taking this back to re-check/review.

**Comment by paregorios** [comment]
This appears to have been some caching oddity. I can't recreate, so closing "no longer observed"
