### ISSUE TITLE
OSM-derived polygon geometry missing in KML

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#201]
Consider [the Telesterion at Eleusis](http://pleiades.stoa.org/places/408217405). We have [a Pleiades location with polygonal geometery](http://pleiades.stoa.org/places/408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2) derived from [an OSM Relation](http://www.openstreetmap.org/relation/2022511). It displays fine on the Pleiades page:

![screen shot 2016-08-10 at 12 14 03 pm](https://cloud.githubusercontent.com/assets/263285/17563270/3806052c-5ef4-11e6-80ef-ef24d875af27.png)

But when you download the KML view via http://pleiades.stoa.org/places/408217405/kml, nothing shows up in Google Earth:

![screen shot 2016-08-10 at 12 17 36 pm](https://cloud.githubusercontent.com/assets/263285/17563318/77cd778a-5ef4-11e6-8e7c-1a122750acad.png)

Examination of the KML file reveals that no geometry has been included:

``` xml
    <Placemark id="places/408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2">
      <name>OSM location of Τελεστήριον</name>
      <atom:link href="http://pleiades.stoa.org/places/408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2"/>
      <address>http://pleiades.stoa.org/places/408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2</address>
      <!--TimeSpan tal:condition="pm_timeSpan|nothing">
        <start tal:content="pm_timeSpan/start"/>
        <end tal:content="pm_timeSpan/end"/>
      </TimeSpan-->
      <atom:author>
        <atom:name>hspock</atom:name>
        <atom:uri>http://pleiades.stoa.org/places/408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2</atom:uri>
      </atom:author>
      <Snippet>Sanctuary, ; 750 BC - AD 300</Snippet>
        <description>
        <![CDATA[
          <p><em>Location based on OpenStreetMap</em></p>
          <ul><!-- Attributes -->
          <li>ID: <span>408217405/osm-location-of-i-iui-iuiii-r-ii1i-i1-2</span></li>
          <li>In context: <a href="http://pleiades.stoa.org/places/408217405" type="">Locations of Telesterion</a></li>
          <li><a href="#places/408217405;balloonFlyto" type="">Fly to parent place</a></li>
          </ul>
        ]]>
        </description>
      <styleUrl>#style-core-1</styleUrl>
    </Placemark>
```

Other serializations (JSON, TTL, RDF/XML) seem to have the geometry.

**Comment by davisagli** [comment]
Give it a try now. The KML export wasn't handling MultiLineString geometries.
