### ISSUE TITLE
batch update: changes baseline instead of working copy when workflow=draft

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#202]
_Testing and reviewing [scrumdo story 12 (Batch Update of Content)](https://www.scrumdo.com/projects/story_permalink/1087991)_

This command:

```
bin/instance1 run scripts/batch_update.py --workflow=draft /home/thomase/updates-test.json
```

Correctly checks out a working copy and leaves it in "drafting" state, but it modifies the wrong object. 
## Desired behavior
- Check out a working copy
- Modify the title in the working copy
## What it did
- Check out a working copy
- Modify the title in the baseline original

I've left things on the staging server in the state that resulted from running the script:
- Original baseline object (with title modified by script): http://pleiades.jazkarta.com/places/70978
- Working copy created by the script in which the title has not been modified: http://pleiades.jazkarta.com/places/copy_of_70978

**Comment by cguardia** [comment]
Fixed.
