### ISSUE TITLE
show "Fetch Zotero" button on newly added reference subform

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#204]
_Testing and reviewing [scrumdo story 61 (populate new-style references from Zotero)](https://www.scrumdo.com/projects/story_permalink/1096459)_

Presently (on staging), when the "References" tab on the "Edit" view is displayed, the "Fetch Zotero" button appears to the right of the "Bibliographic URI" field for each reference already in the object. But when a new reference is added to the widget, using the "Add Reference" button, no such "Fetch Zotero" button is displayed. One has to save the edit form, open it again, navigate to the "References" tab and scroll down to the added reference in order to get the "Fetch Zotero" button. Preferably, the "Fetch Zotero" button would already be displayed for a new reference, or would appear once text has been entered in the "Bibliographic URI" field.

**Comment by alecpm** [comment]
The fix is live on staging.

**Comment by paregorios** [comment]
Works!
