### ISSUE TITLE
Pleiades json dump is not valid JSON

### ISSUE THREAD

**Issue by gabrielbodard** [isawnyu/pleiades-gazetteer#205]
The Pleiades JSON dump downloaded from http://atlantides.org/downloads/pleiades/json/pleiades-places-latest.json.gz (on July 13, 2016, for reference) seems not to be valid JSON. Specifically it is a comma-delimited set of json dictionaries, one for each place, but not grouped together in a list or similar. (If I add `[` and `]` and the very beginning and end of the file, it validates.)

**Comment by alecpm** [comment]
Taking a look at the latest successful export, I'm seeing valid JSON. The format looks like the following:

{
    "@context": {...},
    "@graph":  [...]
}

Where @context contains a JSON-LD schema and @graph contains the list of place dictionaries.

**Comment by paregorios** [comment]
@gabrielbodard can you point us to the validator you were using?

**Comment by paregorios** [comment]
@gabrielbodard please download the latest JSON file (http://atlantides.org/downloads/pleiades/json/pleiades-places-20160812.json.gz) and review for validation. It looks good to us.

**Comment by gabrielbodard** [comment]
Yes, this looks fine now. What was missing before, I can now see, was the outer dictionary (@context and @graph) and so the file only contained the contents of the graph (without even the enclosing list braces).

Thanks so much!
