### ISSUE TITLE
add new reference default value for 'other uri'

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#207]
We're seeing an old default value (http://atlantides.org/bibliography/) populate into the "other identifier" field when a new reference is created:

![screen shot 2016-08-12 at 2 49 19 pm](https://cloud.githubusercontent.com/assets/263285/17635263/02b7f4e4-609c-11e6-96c9-feade77ca046.png)

I'd prefer that the field be blank by default.

**Comment by alecpm** [comment]
This is fixed on staging

**Comment by paregorios** [comment]
looks good
