### ISSUE TITLE
on Zotero import, don't add title

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#208]
The [story](https://www.scrumdo.com/projects/story_permalink/1096459) said:
- short title < Zotero record short title 
- formatted citation < response from Zotero API to [a call for 'format="bib"'](https://www.zotero.org/support/dev/web_api/v3/basics#parameters_for_format_bib_includecontent_bib_includecontent_citation) and citation style = https://www.zotero.org/styles/modern-language-association-with-url
- identifiers: 
  - add Zotero URI with type "bibliographic uri"
  - if Zotero record's "url" field is non-empty and is a valid url, add its contents with type "access url"

In addition to the above, the Zotero title is getting pulled into the "citation detail" field. That field should be left blank.

**Comment by alecpm** [comment]
This is done. The short title field will populate with title if the zotero short title isn't filled.

**Comment by paregorios** [comment]
Final review of this issue is blocked for resolution of #209

**Comment by paregorios** [comment]
@alecpm: alas, this doesn't yet seem to work (although clearly something has changed).

## Steps to reproduce:
- login to staging with a user that has admin or editor group affiliation (i.e., can direct-edit published places)
- navigate to http://pleiades.jazkarta.com/places/109169
- select the "edit" button
- select the "references" tab
- scroll down and select the "add reference" button
- paste https://www.zotero.org/groups/pleiades/items/itemKey/CE2IVAQW into the "bibliographic URI" text box
- select the "Fetch Zotero" button

## What happens:

"0" appears in the short title, instead of "The Library of Alexandria" as expected. Screenshot:

![screen shot 2016-08-17 at 7 55 15 am](https://cloud.githubusercontent.com/assets/263285/17736930/f97c0660-644f-11e6-947f-66127cdf39af.png)

## Expected behavior:

Difference from what's actually happening is in **bold**:
- Citation type: seeFurther
- Short Title: **"The Library of Alexandria"**
- Citation Detail: ""
- Formatted Citation: "`<div class="csl-entry">Trumble, Kelly, and Robina MacIntyre Marshall. <i>The Library of Alexandria</i>. New York: Clarion Books, 2003.</div>`"
- Bibliographic URI: "https://www.zotero.org/groups/pleiades/items/itemKey/CE2IVAQW"
- Access URI: ""
- Alternate URI: ""
- Other identifier: ""

## The source data in Zotero

It has no "short title" value, which is the edge case we're trying to address here:

![screen shot 2016-08-17 at 7 58 25 am](https://cloud.githubusercontent.com/assets/263285/17737030/840cd9c6-6450-11e6-81d6-37977f8f878b.png)

**Comment by atomrab** [comment]
This may be my fault -- I added this recently without including a "short
title" field (didn't realize this was how we'd be grabbing the Zotero
records). I've added a short title now -- maybe try again?

**Comment by atomrab** [comment]
Or -- reading more carefully -- maybe you're trying to see what happens
when there is no short title, in which case you can try with one of the
other entries I recently added, like
https://www.zotero.org/groups/pleiades/items/itemKey/CUWZ2SG6.

**Comment by paregorios** [comment]
@atomrab right, I'm trying to make sure we have a fallback behavior that works when there is no short title in the zotero record. It will be Pleiads editorial policy to include the short title, but I want the import to do something sane if we screw that up. 

So, to clarify, have you modified the zotero reference I indicated above int he "steps to reproduce"? If so, I'll need to change that so @alecpm has a live short-title-free record to work with on the zotero side for testing.

**Comment by atomrab** [comment]
Yes, I modified that one, but the link I provided in the second message is
short-title free and can be used for testing.

**Comment by alecpm** [comment]
Looks like I made a typo in the JS that only affected the case where there's no shortTitle, but there is a title set. Should be fixed now.

**Comment by paregorios** [comment]
This (and all the associated permutations) is now working.
