### ISSUE TITLE
Zotero import doesn't get short title when present

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#209]
_Reviewing implementation of https://www.scrumdo.com/projects/story_permalink/1096459_
## Steps to reproduce:
- login to staging with a user that has admin or editor group affiliation (i.e., can direct-edit published places)
- navigate to http://pleiades.jazkarta.com/places/109169
- select the "references" tab
- scroll down and select the "add reference" button
- paste https://www.zotero.org/groups/pleiades/items/itemKey/6B9S8BSJ into the "bibliographic URI" text box
- select the "Fetch Zotero" button
## The result looks like this:

<img width="442" alt="screen shot 2016-08-13 at 6 10 44 am" src="https://cloud.githubusercontent.com/assets/263285/17642874/0e0b885c-611d-11e6-8cd0-42f442a4a205.png">
## The problem

There is a short title present in the Zotero record, but it is not being used in the Pleiades bibliographic record:

<img width="479" alt="screen shot 2016-08-13 at 6 18 27 am" src="https://cloud.githubusercontent.com/assets/263285/17642892/c9f12a86-611d-11e6-873c-c0fbc2906637.png">
## Desired behavior ...

... is fields populated like this (differences from screen shot are **bolded**):
- Citation type: "See Further"
- **Short title: "TIR Mogontiacum"**
- Citation detail: ""
- Formatted citation: "`<div class="csl-entry"><i>Mogontiacum</i>. Tabula Imperii Romani, M 32. Frankfurt, 1940.</div>`"
- Bibliographic URI: "https://www.zotero.org/groups/pleiades/items/itemKey/6B9S8BSJ"
- Access URI: ""
- Alternate URI: ""
- Other Identifier: ""

**Comment by paregorios** [comment]
Resolution of this issue blocks final review of #208

**Comment by alecpm** [comment]
I implemented it this way intentionally, so that the button did not overwrite manually entered values. It's simple enough to remove that "feature" if it's not desirable.

**Comment by alecpm** [comment]
This should be fixed now.

**Comment by paregorios** [comment]
Fixed. Super duper!
