### ISSUE TITLE
batch update: owner set by script has "insufficient privileges"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#210]
**This issue is related to review of [story 12](https://www.scrumdo.com/projects/story_permalink/1087991).**

As `plone_daemon`, I issued the following command on staging and saw the following output (plone warnings omitted):

```
$ bin/instance1 run scripts/batch_update.py --workflow=draft --owner auser /home/thomase/updates-test.json

Starting batch content update...

Updating object at path: places/70978
Found Place with title "Untitled"
Workflow state: published.
2016-08-15 13:02:34 WARNING OFS.Uninstalled Could not import class 'IRatingCategoryAssignment' from module 'plone.contentratings.interfaces'
Checked out working copy: /plone/places/copy_of_70978
Set "title" to: "Unnamed roads in the area of Vorgium". Old value: "Untitled"
Set owner to auser
Updated "Unnamed roads in the area of Vorgium".

Updated content in Plone.
```

Then I logged into staging as "auser" (the user to whom ownership of the working copy was assigned). But when I visit `/places/copy_of_70978` I see:

![screen shot 2016-08-15 at 12 08 28 pm](https://cloud.githubusercontent.com/assets/263285/17672244/06acaf62-62e1-11e6-9f6e-5714e81a41af.png)

When I log in as a user with administrative permissions, I can view the working copy. Viewing the "ownership form" would seem to indicate that ownership has been correctly assigned by the script:

![screen shot 2016-08-15 at 12 12 19 pm](https://cloud.githubusercontent.com/assets/263285/17672363/a0068598-62e1-11e6-9432-09edd32d60b9.png)
## Expected behavior:

User to whom ownership has been given should be able to view, edit, and submit the content item in question.

**Comment by cguardia** [comment]
Turns out changing owner was not enough. Local roles had to be set on the working copy as well. Deployed fix to staging.

**Comment by paregorios** [comment]
@cguardia now something else is broken.

I run the following:

`bin/instance1 run scripts/batch_update.py --creators auser jbecker --contributors sarcanon sgillies --workflow draft /home/thomase/updates-test.json`

Then, as my authenticated user, I try to visit the working copy at `http://pleiades.jazkarta.com/places/copy_of_70978`, I get the following:

> AttributeError("'list' object has no attribute 'replace'",) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: 'list' object has no attribute 'replace')

I have left the busted working copy in place for your investigation.

**Comment by cguardia** [comment]
This is the same problem with the json format that I mentioned in #211.

**Comment by paregorios** [comment]
Works!
