### ISSUE TITLE
references are broken on production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#214]
Consider the following examples ... perhaps a migration wasn't run or didn't complete?

http://pleiades.stoa.org/places/579920
<img width="409" alt="screen shot 2016-08-30 at 5 07 13 am" src="https://cloud.githubusercontent.com/assets/263285/18085219/d38f3bdc-6e6f-11e6-9339-d2320b6efef8.png">

http://pleiades.stoa.org/places/935032928
<img width="407" alt="screen shot 2016-08-30 at 5 06 59 am" src="https://cloud.githubusercontent.com/assets/263285/18085212/cc0f2926-6e6f-11e6-8f61-1c10d8a09022.png">

**Comment by alecpm** [comment]
It's not clear to me what happened here. The migration ran without any hiccups, but it appears the "range" data was not transferred into the formatted citation field. That data still appears to be accessible in the ZODB. Unfortunately, there seems to be a more significant issue where some identifiers, didn't get copied into the bibliographic_uri field. That data seems to be entirely gone, so we may have to restore a recent backup to recover this data if the loss appears to be extensive. The first example above appears to have no URIs set for two of the references, but the second has URIs set for all of the references.

I can make an updated migration that pulls the "range" data into the formatted citation field, but if the missing URI issue appears to be extensive, it would probably be better to restore from a pre-migration backup before attempting to correct the migration issues.

**Comment by paregorios** [comment]
I will investigate as soon as I can regarding the URI info and report back. Did you happen to grab a zodb snapshot or do I need to ask Tummy to start pulling the most recent backup?

**Comment by paregorios** [comment]
@alecpm how would I check to see if the old URI data is still hanging around? I see plenty of references at random that have empty bibliographic_uri fields ...

**Comment by skleinfeldt** [comment]
FYI Tom is in the process of getting the latest backup from Tummy.

**Comment by alecpm** [comment]
No snapshots available, but we could backup the current DB and then truncate it at a specific transaction to bring it back to a point in time if needed.

**Comment by alecpm** [comment]
@paregorios on that first item there are 2 references that have no URI field or even the identifier set. I'm wondering if that's just a one off issue or more common. I don't see how a record that originally had an identifier would end up with all those fields blank, but it appears to be the case for that one Place at least, and I'd like to know if it's more widespread.

**Comment by alecpm** [comment]
The range data has been restored into the formatted citation field, and things are looking OK on production. The default atlantides.org bibliography urls are still not populating, and I'll investigate that ASAP.

**Comment by alecpm** [comment]
OK, the default atlantides urls are now used on the view when no identifiers are set, they do not appear in the edit forms for reasons that are a bit mysterious to me at the moment, but I think that's actually a reasonable behavior.

**Comment by paregorios** [comment]
@alecpm this looks fixed, thanks!
