### ISSUE TITLE
browsers blocking mixed content on home page

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#221]
On the home page via HTTPS:
- Chrome blocks: http://pleiades.stoa.org/api/status
- Chrome warns about: http://atlantides.org/images/justice-blue.png

**Comment by alecpm** [comment]
The homepage should safely be able to reference https://pleiades.stoa.org/api/status instead or //pleiades.stoa.org/api/status to be protocol agnostic.

Could we move that image into the CMS and reference it via HTTPS, say:

https://pleiades.stoa.org/images/justice-blue.png

**Comment by witekdev** [comment]
What I'm seeing with Chrome 54 on Win 7 is that it doesn't even let me access the http link but redirects me to the https. I see this behaviour too with other browsers, FF, Opera, Srware Iron.

**Comment by davisagli** [comment]
@witekdev read it again. The problem is that _when_ the page loads via https, there are warnings in the console about some resources that are loaded via http. We should change them to load via https also.

**Comment by witekdev** [comment]
@davisagli ah, I see now, ok thanks!

**Comment by witekdev** [comment]
I made changes to the pleiades.frontpage package that will hopefully address this, however I realised I don't know how to deploy these changes to the non-plone pleiades front page. @davisagli @alecpm what is the mechanism to do that? thanks!

**Comment by davisagli** [comment]
@witekdev It's in /var/www/pleiades.stoa.org/pleiades-frontpage on the server.

**Comment by paregorios** [comment]
Is it not part of the ansible playbook?

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
I think it's part of the full "pleiades.yml" playbook, not the "deploy.yml" playbook which only deploys Plone. But it seems silly to run the full playbook for something that only requires a "git pull"

**Comment by witekdev** [comment]
Deployed on staging and production.

**Comment by paregorios** [comment]
excellent, thanks!
