### ISSUE TITLE
Bad URLs in connectsWith property in JSON output

### ISSUE THREAD

**Issue by ryanfb** [isawnyu/pleiades-gazetteer#224]
The `connectsWith` property in the JSON output is often a URL which looks like (for https://pleiades.stoa.org/places/265877):

https://pleiades.stoa.org/places/9c80aa04f0883d00bbe730ad4b7a6e58

However, this is not always the case, as there are also good URLs as well (for https://pleiades.stoa.org/places/265880):

https://pleiades.stoa.org/places/269561

This appears to be the case for both the JSON dumps as well as the JSON for an individual place.

**Comment by ryanfb** [comment]
These are also in the connections properties in the CSV dumps.

**Comment by davisagli** [comment]
@witekdev These are supposed to use the place's id, not its UUID. In some cases these URLs are generated from catalog metadata, so maybe the metadata is wrong or maybe we're using the wrong field.

**Comment by alecpm** [comment]
It looks like this is a catalog metadata issue, reindexing the content fixes it.  I'll make a quick catalog updater script that we can run on every place to update its catalog metadata if it has any UIDs in connectsWith or hasConnectionsWith.

**Comment by alecpm** [comment]
The migration has been run on staging, there should no longer be any items with the erroneous connection urls. I manually fixed the one above on production when verifying the cause, but the migration has not yet been run there to catch other instances.

**Comment by paregorios** [comment]
ok @alecpm, let's schedule a time to run this migration on production. I'd like to ask for you to grab and store a copy of the database file before running the migration.

**Comment by alecpm** [comment]
OK, I made a backup (and started an implementation of auto-backup/pack since that appears to be missing from our deployment), and ran the migration on production. It appears to have run quickly and without issues.

**Comment by ryanfb** [comment]
This appears to be fixed in both individual JSON representations and the latest JSON/CSV dumps. Thanks!
