### ISSUE TITLE
CORS failure using AWMCjs

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#226]
For example, consider [this page at DCC](http://dcc.dickinson.edu/caesar/book-1/chapter-1-1). Instead of nifty map and description pulled from Pleiades JSON, [AWMCjs](http://isawnyu.github.io/awld-js/) pops up a generic entry (symptomatic of a failure to retrieve and parse successfully the Pleiades JSON):

<img width="745" alt="screen shot 2016-09-27 at 1 55 30 pm" src="https://cloud.githubusercontent.com/assets/263285/18887563/2e5ef506-84ba-11e6-8254-18241042bcfe.png">

At first I thought it was just that our shift from HTTP to HTTPS was freaking out AWMCjs, but I note the following errors:

<img width="463" alt="screen shot 2016-09-27 at 1 59 03 pm" src="https://cloud.githubusercontent.com/assets/263285/18887651/97a4abc8-84ba-11e6-98d2-e48147629e4d.png">

It may be the case that AWMCjs needs to be taught how to deal with a 301 HTTP response, but we'll probably need to get past this cross-origin issue before we can troubleshoot that. 

Consider these diagnostic curls:

```
$ curl -I http://pleiades.stoa.org/places/993/json
HTTP/1.1 301 Moved Permanently
Date: Tue, 27 Sep 2016 18:59:54 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://pleiades.stoa.org/places/993/json
Cache-Control: max-age=86400
Expires: Wed, 28 Sep 2016 18:59:54 GMT
Content-Type: text/html; charset=iso-8859-1
```

and

```
$ curl -I https://pleiades.stoa.org/places/993/json
HTTP/1.1 200 OK
Date: Tue, 27 Sep 2016 19:00:12 GMT
Server: Zope/(2.13.23, python 2.7.11, linux2) ZServer/1.1
Content-Length: 7865
Vary: Accept
Access-Control-Allow-Origin: *
Content-Type: application/json
X-Frame-Options: SAMEORIGIN
X-Varnish: 600119
Age: 0
Via: 1.1 varnish-v4
X-Varnish-Cache: MISS
Accept-Ranges: bytes
Cache-Control: max-age=86400, s-maxage=11988
Expires: Wed, 28 Sep 2016 19:00:12 GMT
```

Thoughts? 

cc @sfsheath

**Comment by davisagli** [comment]
How hard would it be to make AWMCjs load directly from the https URLs instead of http? The problem is that the Access-Control-Allow-Origin: \* header is added by the json view, but the redirect happens before the traffic makes it to Plone, much less the view. We can make apache add the header, but loading directly from https should avoid the problem and also avoid an extra request.

**Comment by paregorios** [comment]
Since Pleiades has gone to HTTPS "for real", it might not be unreasonable to help people out by having AWMCjs sniff pleiades links for protocol and just "do the right thing". That won't help others who aren't using AWMCjs but who are holding data in which the HTTP URIs have been embedded and who were relying on the promise of redirects to provide some future-proofing to their Pleiades-using webapps. 

Thoughts from @ekansa, @portableant, @ryanfb, @rmhorne, @ewg118, @wenamun, @rsimon ?

**Comment by davisagli** [comment]
Yeah. I think we should make apache add the header _and_ make AWMCjs load from https.

**Comment by portableant** [comment]
Does this sum up the issue 
http://stackoverflow.com/questions/24484427/cors-no-access-control-allow-origin-header-is-present-yet-there-is
Sorry not dug into this deeply...

**Comment by paregorios** [comment]
Thanks to [a patch to awld.js](https://github.com/isawnyu/awld-js/pull/11) from @ryafb, existing implementations that use legacy pleiades HTTP URIs and that pull their AWLD.js code live from github are no longer broken. We still need to modify our ansible playbook for apache to make it add the CORS header to the redirect.

**Comment by alecpm** [comment]
The header should be in place on all https redirects on staging and production.

**Comment by paregorios** [comment]
looks good, thanks!
