### ISSUE TITLE
Fetch Zotero fails silently if query string is attached to item URI

### ISSUE THREAD

**Issue by steko** [isawnyu/pleiades-gazetteer#227]
While trying to import a reference from https://www.zotero.org/steko/items/itemKey/IUN6AZYT/q/carsiche using the _Fetch Zotero_ widget, I obtained no error message and no content.

Removing the query string part from the URI, resulting in https://www.zotero.org/steko/items/itemKey/IUN6AZYT works perfectly.

Expected outcome: there should be an error message telling users that something is wrong with the URI, at minimum.

**Comment by paregorios** [comment]
We should probably generalize this to report any error response received from the Zotero API (rather than just silently failing). Could we do this via a pop-up or something?

**Comment by alecpm** [comment]
There is some alert message error handling, but it appears to be failing in this case. Should be easy to fix.

**Comment by alecpm** [comment]
The fix for both the missing alert and the underlying issue with the Zotero url are now on staging.

**Comment by paregorios** [comment]
@alecpm this is working now, but would it be possible to cleanup/regularize the URL that we subsequently store? So, for this example (https://www.zotero.org/steko/items/itemKey/IUN6AZYT/q/carsiche) you've figured out how to get the correct data. Could we strip off the query components when storing the bibliographic URL (i.e., store https://www.zotero.org/steko/items/itemKey/IUN6AZYT)?

**Comment by alecpm** [comment]
Most likely yes, I'll look into that today.

**Comment by alecpm** [comment]
This should be working correctly on staging now.

**Comment by paregorios** [comment]
@alecpm I;'m not seeing the URL cleaning working on staging. Here's what I did:
- Logged into staging as an admin user
- Navigated to https://pleiades.jazkarta.com/places/893999
- Edited the place resource
- Switched to the reference tab
- Added a new resource
- Pasted this URL into the "Bibliographic URI" box: https://www.zotero.org/paregorios/items/collectionKey/V9VA7HTP/itemKey/5WZRH53A/q/git
- Click the FETCH button
- Noted that all the appropriate fields got populated, **but** the Bibliographic URI value was still https://www.zotero.org/paregorios/items/collectionKey/V9VA7HTP/itemKey/5WZRH53A/q/git even though I [expected](https://github.com/isawnyu/pleiades-gazetteer/issues/227#issuecomment-257865931) it to have been cleaned to https://www.zotero.org/paregorios/items/collectionKey/V9VA7HTP/itemKey/5WZRH53A
- Went ahead and saved the change, thinking maybe the cleanup didn't happen till save.
- Opened the edit for again to inspect the bibliographic URI and noted that it was still https://www.zotero.org/paregorios/items/collectionKey/V9VA7HTP/itemKey/5WZRH53A/q/git

I've left the added reference in place for your inspection.

**Comment by alecpm** [comment]
The portal javascript registry needed to be re-saved to clear the cache. It is working as expected now.

**Comment by paregorios** [comment]
I can confirm it's working now on staging. Please deploy to production.

**Comment by alecpm** [comment]
This is deployed to production.
