### ISSUE TITLE
OSM widget to add new location not shown on working copy of a place

### ISSUE THREAD

**Issue by steko** [isawnyu/pleiades-gazetteer#229]
See the screenshots 

Original place

![schermata da 2016-10-01 17-03-04](https://cloud.githubusercontent.com/assets/40545/19014876/f67a178c-87f8-11e6-8ca1-32e6e6d1c6bf.png)

Working copy

![schermata da 2016-10-01 17-02-52](https://cloud.githubusercontent.com/assets/40545/19014877/f67a6af2-87f8-11e6-92b6-035645b4003f.png)

Thus apparently I have no way of adding a new OSM-based location to the working copy.

**Comment by paregorios** [comment]
this used to work ...

**Comment by davisagli** [comment]
Fixed

**Comment by paregorios** [comment]
Confirmed fixed. Closing.
