### ISSUE TITLE
importing complex OSM relations provokes 500-series errors on Pleiades

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#232]
Frontpage works, so server is up and apache is running, but plone-served pages are returning 503. This seems to have started around 6:10 a.m. US Eastern time on 19 October.

**Comment by paregorios** [comment]
And now it's back, suddenly.

**Comment by paregorios** [comment]
I'd like to do some forensics on what happened here (about a 20 minute outage, it appears), when we have time.

**Comment by davisagli** [comment]
It looks like the culprit is the view to import a location from OSM, which was called a number of times from static-170-42-226-77.ipcom.comunitel.net and at least in some cases ran for an insanely long time. I'm not sure why it would do that. If we know who was creating locations this morning and can find out what they were trying to import, we can investigate further.

**Comment by paregorios** [comment]
Thanks @davisagli I'll try to find out who that was and get some info.

**Comment by paregorios** [comment]
https://pleiades.stoa.org/places/810796635/osm-location-of-galicia

**Comment by paregorios** [comment]
```
2016-10-19T06:58:16 INFO pleiades.vaytrou Indexing geolocation: 1914190519, <Location at osm-location-of-galicia>
------
2016-10-19T06:58:16 WARNING pleiades.geographer Failed to adapt <Location at osm-location-of-galicia> in 'location_geo': 'NoneType' object has no attribute 'get'
------
2016-10-19T06:58:16 INFO pleiades.vaytrou No indexable attribute geolocation in <Location at osm-location-of-galicia>
------
2016-10-19T06:58:24 INFO ZPublisher.Conflict ConflictError at /VirtualHostBase/https/pleiades.stoa.org/plone/VirtualHostRoot/places/810796635/@@create-location-osm: database conflict error (oid 0x01add36b, class Products.PleiadesEntity.content.Place.Place) (2 conflicts (0 unresolved) since startup at Mon Sep 26 17:07:25 2016)
```

**Comment by davisagli** [comment]
I'm wondering what OSM object was that imported from, and were there attempts to import any others that did not complete?

David Glick
(mobile)

**Comment by paregorios** [comment]
It looks like the import was from https://www.openstreetmap.org/relation/349036, which is so complex that even OSM takes a long time to display it in their web app. I think we may need a complexity filter or something on the Pleiades import side (if we can figure out how that would work).

**Comment by davisagli** [comment]
Actually that relation is supposed to already be rejected (we only allow relations of type "multipolygon" or "waterway"), but the code to abort when the relation type is something else wasn't working. Fixed.

**Comment by paregorios** [comment]
@davisagli works well on staging. Did you also fix this on production? (I'm nervous to try without checking with you first).

**Comment by davisagli** [comment]
Yep.

**Comment by paregorios** [comment]
Confirmed this is now fixed on production. Thanks.
