### ISSUE TITLE
Add path to advanced search form to home page and refine instructions

### ISSUE THREAD

**Issue by ewg118** [isawnyu/pleiades-gazetteer#235]
The autosuggest feature is useful in the main search bar on the home page, but it only suggests items where the search term appears in the title. Since there's no search button, it's impossible to search keywords. E.g., if I want to search "aqueducts" in general, I cannot do it from the home page. Several aqueducts will appear in the autosuggest (because the word is in the title), but Aqua Marcia will not.

**Comment by paregorios** [comment]
this would be a modification to https://github.com/isawnyu/pleiades-frontpage

**Comment by paregorios** [comment]
As a web user of the Pleiades front page, I will see a modified version of the search section of the home page, as follows:

![search](https://user-images.githubusercontent.com/263285/54855963-61d38b00-4cc6-11e9-968a-a54d7088e0b6.png)

Here's what's changed:

 - the tip text inside the search box will now read "Start typing a placename, Pleiades ID, or URL"
 - below the search box the following new text will be added: "or try our Advanced Search form" 
 - in the new text, the words "Advanced Search form" will link through to https://pleiades.stoa.org/search_form
