### ISSUE TITLE
some map controls have bigger z-index(?) than dialogs

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#236]
Consider the poor reference browser widget for accuracy assessments:

![screen shot 2016-11-04 at 8 38 45 am](https://cloud.githubusercontent.com/assets/263285/20007441/4156e51a-a26a-11e6-984c-3e84975cfcf7.png)

Is there a quick and easy (CSS?) way we can tone down the altitude on the layer selector and zoom level control in our maps?

**Comment by davisagli** [comment]
I fixed this while working on story 82 (currently on staging)

**Comment by paregorios** [comment]
@davisagli looks great. Please deploy to production.

**Comment by davisagli** [comment]
This was deployed as part of story 82.

**Comment by paregorios** [comment]
@davisagli I'm not seeing any difference on production. Do we need a cache purge or is something else not quite fully deployed? See also comment in scrumdo on story 82 deployment.

**Comment by davisagli** [comment]
@paregorios try now

**Comment by paregorios** [comment]
that's got it.
