### ISSUE TITLE
JSON place representations should include charset in HTTP Content-Type header

### ISSUE THREAD

**Issue by ryanfb** [isawnyu/pleiades-gazetteer#237]
See: http://www.w3.org/International/articles/http-charset/index

> HTTP 1.1 says that the default charset is ISO-8859-1

This results in encoding mangling when viewing the JSON response (which is UTF-8) as ISO-8859-1. e.g. https://pleiades.stoa.org/places/265877/json has:

    "details": "The Barrington Atlas Directory notes: SE coastal area, E Bastetania up to R. JÃºcar (XÃºquer)"

Instead of:

    "details": "The Barrington Atlas Directory notes: SE coastal area, E Bastetania up to R. Júcar (Xúquer)"

Some other place representations already include this, e.g. turtle:

    Content-Type: text/turtle; charset=utf-8

**Comment by paregorios** [comment]
I bet this is something that didn't get transferred from our hand-curated apache config to the one that's set up by ansible

**Comment by davisagli** [comment]
Fixed on staging.

**Comment by paregorios** [comment]
Looks good to me:

```
$ curl -I https://pleiades.jazkarta.com/places/265877/json
HTTP/1.1 200 OK
Date: Tue, 08 Nov 2016 21:50:09 GMT
Server: Zope/(2.13.24, python 2.7.11, linux2) ZServer/1.1
Content-Length: 13007
Vary: Accept
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
X-Frame-Options: SAMEORIGIN
X-Varnish: 229750
Age: 0
Via: 1.1 varnish-v4
X-Varnish-Cache: MISS
Accept-Ranges: bytes
Cache-Control: max-age=86400, s-maxage=11988
Expires: Wed, 09 Nov 2016 21:50:09 GMT
```

Please deploy to production.

**Comment by davisagli** [comment]
deployed

**Comment by ryanfb** [comment]
Thanks!
