### ISSUE TITLE
streamlined submit: edge case on locations

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#238]
In reviewing implementation of [Scrumdo Story 92 (force all submits to be "advanced")](https://www.scrumdo.com/projects/story_permalink/1101153) on staging, I encountered the following edge case:

When attempting to submit a draft Location within a draft Place, the "Publishing Process" page shows the Location twice in the "Affected content" listing: 

 
<img width="543" alt="screen shot 2016-11-07 at 11 40 31 am" src="https://cloud.githubusercontent.com/assets/263285/20068661/071d88a0-a4df-11e6-9851-cc8d17feb808.png">

## Steps to reproduce:

 * Login to staging
 * Visit https://pleiades.jazkarta.com/places/746512571/akroteri
 * Select "State: drafting" -> "Submit for review"
 * Examine the "Publishing Process" page.

**Comment by paregorios** [comment]
Update: this seems to affect all sub-place content. I just added a draft Name in the same Place context as above, and now when I attempt to submit the Name only, I see:

<img width="520" alt="screen shot 2016-11-07 at 11 48 07 am" src="https://cloud.githubusercontent.com/assets/263285/20068895/146a850c-a4e0-11e6-85e5-3bfb0b3bb55a.png">

(There should only be one "Atlantis Nesos" in this view, and no Ακρωτήρι

**Comment by paregorios** [comment]
This same behavior occurs if the "submit" is actuated via the folder listing on the place with only one subordinate item checked.

**Comment by paregorios** [comment]
I see this behavior on regular content too. So, for example, I create https://pleiades.jazkarta.com/news/blog/testaroo then select "state: drafting" -> "submit for review" and I see this:

<img width="918" alt="screen shot 2016-11-07 at 12 20 02 pm" src="https://cloud.githubusercontent.com/assets/263285/20070026/89dc4cd6-a4e4-11e6-9d30-803b341ac718.png">

I.e., all content in the parent folder.

**Comment by davisagli** [comment]
I suspect this is happening for any item that is not itself folderish. Should be an easy fix.

**Comment by davisagli** [comment]
Fix deployed to staging.

**Comment by paregorios** [comment]
Perfect.
