### ISSUE TITLE
KML search URLs can't handle RTL language chars

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#25]
Am naively appending the Hebrew language string for Tadmur (from http://pleiades.stoa.org/places/668331/tadmor) to http://pleiades.stoa.org/search_kml?SearchableText= and encountering trouble. 

http://pleiades.stoa.org/se[…]%93%D6%B0%D7%9E%D6%B9%D7%A8 doesn't work (no results), but http://pleiades.stoa.org/se[…]%93%D6%B0%D7%9E%D6%B9%D7%A8 does (1 result).

Q: Are we making valid internationalized search URLs? Is the pleiades_kml handler messing up?

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/11, where it was originally opened by @sgillies.

**Comment by sgillies** [comment]
Hey @paregorios no need to mention me on all these!

**Comment by paregorios** [comment]
closing "won't fix" as this is a rather artificial attempt and one I don't see users trying in analytics data.
