### ISSUE TITLE
pull request for batch update script -- 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#264]
Request code review and merge of https://github.com/isawnyu/pleiades3-buildout/pull/4

**Comment by paregorios** [comment]
This seems never to have got reviewed and merged. It should be re-assessed for validity/relevance, reviewed, tested, and then merged or rejected.

**Comment by paregorios** [comment]
justification: the batch script input file makes you set an id for new content; however, place ids are supposed to be autogenerated by code in the plone. This modification to the script prevents trouble by ignoring the input id on a new content item for creation if that item is a place.

**Comment by cguardia** [comment]
The PR has been merged.

**Comment by paregorios** [comment]
@cguardia so is this ticket ready to move into "reviewing"?

**Comment by cguardia** [comment]
It is now. I hadn't deployed to staging.

**Comment by paregorios** [comment]
this looks good; please deploy to production
