### ISSUE TITLE
who is "admin2" and why are they showing up on the "credits" page?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#266]
https://pleiades.stoa.org/credits

No name line, but that's the user account shown in the links.

Note, moreover, that creator link doesn't return results.\

![screen shot 2016-12-13 at 8 18 25 am](https://cloud.githubusercontent.com/assets/263285/21143539/c174d7aa-c10c-11e6-853d-c104af2be8f4.png)

**Comment by davisagli** [comment]
This is a Zope-level admin account that I was using. I didn't intend to edit any content with it but I must have at some point. Looking at the catalog the items that were created by this user are:
- https://pleiades.stoa.org/Members/admin2 (you can delete this)
- https://pleiades.stoa.org/credits (i.e. the credits page itself; I think I turned this from just a view template into a page with a special view template so that it shows up in the breadcrumbs. You can probably edit the page and remove admin2)

**Comment by paregorios** [comment]
@davisagli : removing admin2 from the "creators" list on https://pleiades.stoa.org/credits by itself didn't work, but once I'd changed the owner for the credits page, then that got rid of the "one addition" aspect. But the https://pleiades.stoa.org/help/help-and-information page was edited by someone using admin2 back in May and I don't see how to expunge that contribution without punting subsequent changes that I've made, and I can't see another way to remove admin2 from the mix. 

I do think that we are suppressing (or at least used to) in the view template for Credits the plain old "admin" user (and also thomase and sgillies). Where would I look for that code to see if I can intervene further regarding admin2?

**Comment by paregorios** [comment]
I found pleiades-notredame, but cannot see any filtering. Whatever we once had in place to keep sgillies out of the listing is now gone, but thomase is still not there, nor "admin".  But I cannot detect whatever code it is that makes that happen. Perhaps it is hidden somewhere else ...

**Comment by davisagli** [comment]
@paregorios I think you can just edit https://pleiades.stoa.org/help/help-and-information, and delete admin2 from the Contributors field on the Creators tab. Or is the issue that you also don't want admin2 to show up in the revision history?

The list shown in the credits template is now generated by code in credits.py in PleiadesEntity. I think the list you mentioned is here: https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/browser/credits.py#L7

**Comment by paregorios** [comment]
this was resolved long ago. closing
