### ISSUE TITLE
spatial constraints on advanced search seem to fail

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#275]
Searches that otherwise return vast numbers of places, when constrained to a bounding box, return a surprisingly small number of places. The places returned seem to be those edited in the past few months. Did code changes affecting "representative point" calculations somehow mess up the spatial component of advanced search?

For example:

[this search (published places of type = settlement)](https://pleiades.stoa.org/search?SearchableText=&Title=&Description=&Subject_usage%3Aignore_empty=operator%3Aand&getFeatureType%3Alist=settlement&getFeatureType_usage%3Aignore_empty=&get_usage%3Aignore_empty=operator%3Aand&Creator=&Contributors=&Provenance=&Cites=&lowerLeft=&upperRight=&predicate=intersection&tolerance=0.0&limit=1&created%3Alist%3Adate=1970%2F02%2F01&created_usage=range%3Amin&pt_toggle=%23&portal_type%3Alist=Place&review_state%3Alist=published&fieldsets%3Alist=basic&fieldsets%3Alist=categories&fieldsets%3Alist=authciteprov&fieldsets%3Alist=geo&fieldsets%3Alist=workflow&form.submitted=1&submit=Advanced+Search&_authenticator=48b1bb067da8de180deed8ce19c655ec01ac8887) returns 12,124 items

but

[this search (same with bounding box settings shown below)](https://pleiades.stoa.org/search?SearchableText=&Title=&Description=&Subject_usage%3Aignore_empty=operator%3Aand&getFeatureType%3Alist=settlement&getFeatureType_usage%3Aignore_empty=&get_usage%3Aignore_empty=operator%3Aand&Creator=&Contributors=&Provenance=&Cites=&lowerLeft=24.0%2C18.0&upperRight=50.0%2C40.0&predicate=intersection&tolerance=0.0&limit=1&created%3Alist%3Adate=1970%2F02%2F01&created_usage=range%3Amin&pt_toggle=%23&portal_type%3Alist=Place&review_state%3Alist=published&fieldsets%3Alist=basic&fieldsets%3Alist=categories&fieldsets%3Alist=authciteprov&fieldsets%3Alist=geo&fieldsets%3Alist=workflow&form.submitted=1&submit=Advanced+Search&_authenticator=48b1bb067da8de180deed8ce19c655ec01ac8887) only returns 18 items! 

![screen shot 2017-01-19 at 1 39 55 pm](https://cloud.githubusercontent.com/assets/263285/22122249/dce4a7ce-de4c-11e6-9b47-b9d3bb9abf3a.png)

**Comment by paregorios** [comment]
Editing [a place in the target area](https://pleiades.stoa.org/places/893951) seems to have made no difference, but editing one of its subordinate locations did!

Reindexing needed?

**Comment by paregorios** [comment]
Forcing an index update, via the ZMI, on a location of a place not appearing in the search results caused that place to appear when the search was next reloaded. 

Steps:

 - ZMI
 - portal_catalog
 - "Catalog" tab
 - filter by place URI fragment
 - select checkbox next to entry for the published location
 - select "update" button

**Comment by paregorios** [comment]
An re-index of the "geolocation" Vaytrou index, initiated via the ZMI and still in progress at this moment, seems incrementally to be adding to the search results. 

Steps:

 - ZMI
 - portal_catalog
 - "Indexes" tab
 - select checkbox next to entry for "geolocation"
 - select "Reindex" button

**Comment by davisagli** [comment]
.Sounds like maybe the spatial index data didn't get transferred properly when we upgraded, and that you're on the right track to resolving the problem.

**Comment by paregorios** [comment]
Indexing appears to be complete, with the Index page in the ZMI showing 59,385 unique values in the "geolocation" index. The diagnostic search above now consistently produces 3,539 matched places, which seems reasonable.
