### ISSUE TITLE
intermittent unexpected redirect from base_view on production links

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#284]
After a deploy and restart on production, I am sometimes encountering an unexpected error when clicking on a link to a Pleiades place page from the map popup or the search results on the landing page. I've only been able to verify that this happens when I'm logged in, but I can't seem to find a reason for why it happens to some and not to others. 

Here's what the error page looks like when it does happen:

<img width="901" alt="screen shot 2017-02-14 at 2 25 28 pm" src="https://cloud.githubusercontent.com/assets/263285/22947641/77e9d266-f2c1-11e6-809e-1452c0e1c0e5.png">

I mentioned this to @davisagli in IRC and he said:

> it happens when something tries to write to the db on a GET request. which often happens only on the first load (i.e. if that populates some cache that doesn’t need to be written later). there’s a good chance that’s a long-standing issue that we should look into

**Comment by paregorios** [comment]
Although I cannot now repeat it, I know it just happened to me (e.g.) on Athens: http://pleiades.stoa.org/places/579885

**Comment by davisagli** [comment]
This is supposed to be suppressed if the user is coming from the same domain; I think that was not working because the homepage slideshow and search were linking to http place URLs which then got redirected to https. I updated the homepage to link directly to https.

**Comment by paregorios** [comment]
Looks good, thanks.
