### ISSUE TITLE
friendly URL slug creation no longer works on names - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#287]
Once upon a time, when a person created a new Pleiades name item, the URL slug was built automagically from the "romanized" name form field (which is also the title). So a Romanized name value like "York" would result in a URL like ```https://pleiades.stoa.org/12345/york.```  This no longer seems to happen reliably; instead we see slugs of a form like ```name.2017-02-17.5618929979```.

**Comment by paregorios** [comment]
Need to add "steps to replicate"

**Comment by alecpm** [comment]
This should be fixed on staging. The auto rename mechanism for Places and Features was also changed in this commit to ensure they are all using the more direct API for choosing a name on AT content.

**Comment by paregorios** [comment]
This works great on staging. Please deploy to production.

**Comment by alecpm** [comment]
Will do! That means @MatthewWilkes Will have to deal with the conflict errors when merging the zombie fix branch. I can merge this into that branch (which one is it?) to avoid the need for that if you'd like though @MatthewWilkes.

**Comment by alecpm** [comment]
Deployed.

**Comment by paregorios** [comment]
Looks good. Closing resolved.
