### ISSUE TITLE
Assertion Error when attempting to save a location based on a failed OSM relation/linestring import -- 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#290]
Attempted to import OSM relation Ceyhan (158125). Received the following traceback:

```
Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 110, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/location_view.pt
Line 65, Column 4
Expression: <PathExpr standard:u'context/@@where'>
Names:
{'container': <Location at /plone/places/658576/osm-location-of-the-modern-course-of-the-ceyhan>,
'context': <Location at /plone/places/658576/osm-location-of-the-modern-course-of-the-ceyhan>,
'default': <object object at 0x7fd26f060bc0>,
'here': <Location at /plone/places/658576/osm-location-of-the-modern-course-of-the-ceyhan>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fd1efcbd940>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/658576/osm-location-of-the-modern-course-of-the-ceyhan/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/658576/osm-location-of-the-modern-course-of-the-ceyhan/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'thomase'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.geographer.views, line 9, in __call__
Module zope.component.hookable, line 33, in __call__
Module zope.component.hooks, line 104, in adapter_hook
Module pleiades.geographer.geo, line 285, in __init__
Module zope.component.hookable, line 33, in __call__
Module zope.component.hooks, line 104, in adapter_hook
Module pleiades.geographer.geo, line 68, in __init__
Module shapely.geometry.base, line 445, in bounds
Module shapely.geometry.base, line 586, in is_empty
Module shapely.geometry.proxy, line 33, in _geom
Module shapely.geometry.multilinestring, line 120, in geos_multilinestring_from_py
AssertionError
```

**Comment by paregorios** [comment]
Clarification: this was not on import but rather on first attempt to save the location after import.

**Comment by paregorios** [comment]
Error appears to be symptomatic of the import having failed to bring over any useful geometry:

![screen shot 2017-02-24 at 12 13 24 pm](https://cloud.githubusercontent.com/assets/263285/23315191/bcca5894-fa8a-11e6-96e7-e0fa4691180c.png)

**Comment by davisagli** [comment]
Still, I'd hope for this to show a validation error rather than breaking.

**Comment by paregorios** [comment]
Offending location did get saved as https://pleiades.stoa.org/places/658576/osm-location-of-the-modern-course-of-the-ceyhan

It's throwing the error for the base view on the parent place too.

**Comment by paregorios** [comment]
I didn't keep a link to the source way on OSM, so this is a bit hard to troubleshoot/verify now, but I note the following:

 - There is an OSM relation of type=waterway corresponding to the Ceyhan river: https://www.openstreetmap.org/relation/158125
 - I tried importing it through Pleiades and was able to get the same behavior as that described above
 - I did not save the location, because I don't want to break the parent place view

We should try to do one or both of the following:

 - detect what is going wrong during the import and intervene to alert the user and prevent creation of a broken location (this would let us figure out what we're doing wrong vis-a-vis osm)
 - validate locations on save and make sure they don't get saved with busted/missing linestring content (this would be a robust safety step for other potential failure modes)

**Comment by paregorios** [comment]
priority:high because this behavior makes it easy for users to create broken pleiades content that throws errors.

**Comment by paregorios** [comment]
See also #318, which is a duplicate, but has lots of additional troubleshooting and other information.

**Comment by paregorios** [comment]
Don't save a location unless it's got valid geometry.

**Comment by skleinfeldt** [comment]
(Do final bullet on https://github.com/isawnyu/pleiades-gazetteer/issues/290#issuecomment-475797265)

**Comment by cguardia** [comment]
There's a fix for this on staging. I tested by first saving coordinates with this value:

{"type": "MultiLineString", "coordinates": []}

This caused an error, as per the issue description. I then added the patch and now it's not possible to save this value and a validation error is shown. This should get other errors where the JSON format is OK, but the coordinates are bad.

**Comment by paregorios** [comment]
It looks to me like both of my (implied) use cases are being addressed, but I would like to suggest a modification to the error notification for the one involving OSM import. 

## Complete: entry of bad geometry string through-the-plone

Steps to test:

 - Navigate to https://pleiades.jazkarta.com/places/
 - Login
 - Select "Add new..." -> "Place" from the actions menu
 - Create a new place and save
 - On the base view of the new place, select the "Add Location" button and fill in the form (title and coordinates -> geometry and coordinates). Use junk text for the contents of the "Geometry and coordinates" field on the "Coordinates" tab of the "add/edit location" form. Select the "save" button.
 - Note the notice that says: "Error: Please correct the indicated errors."
 - Be happy.

## Modify error message: bad geometry found during OSM import

 - Navigate to https://pleiades.jazkarta.com/places/
 - Login
 - Select "Add new..." -> "Place" from the actions menu
 - Create a new place and save
 - On the base view of the new place, select the drop-down arrow at the right end of the "Add Location" form in order to display the "Add OpenStreetMap Point Location" pop-up form. 
    - Select the "relation" radio button
    - Type or paste this value in the "Object ID" text box (no quotes): "158125"
    - Select the "add" button.
    - Note the error message: "Info: Location not created. invalid literal for int() with base 10: ''.""

Could we instead change the error message as follows:

 1. Make it look like the error message for the first use case (red "Error" callout with yellow-filled text field instead of blue "Info" callout with light-blue filled text field).
 2. In the text field, use the following text: "OSM Import Failed because of an error in parsing coordinate geometry" then append any error message that came back from the process.

**Comment by cguardia** [comment]
The latest fixes are on staging now.

**Comment by paregorios** [comment]
Looks great! Please merge to master and deploy to production.

**Comment by cguardia** [comment]
Deployed.
