### ISSUE TITLE
autozoom to location geometry in maps

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#291]
Polygonal geometry is often too small to be seen in our standard zoom level for places and locations. Even at maximum zoom level on the default layer, they may be difficult to spot. Ideally, we'd give users an affordance to zoom to 

- extent of all geometry
- extent of a particular location

We probably should auto-switch to our highest resolution map layer (currently "streets"). 

discussed with @rmhorne in IRC

**Comment by paregorios** [comment]
An alternative is to overlay a symbol when the polygon is too small for the scale. Thoughts @rmhorne?

**Comment by paregorios** [comment]
see also #280

**Comment by rmhorne** [comment]
I am all for auto-switching when the zoom level is too small; we should also allow closer zoom for the other basemaps where possible (i.e. OSM can zoom in far more than the ancient layers)
