### ISSUE TITLE
https://pleiades.stoa.org/places/vocab returns 404 -- 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#294]
This is reported in our RDF as our place ontology. Here it is in the wayback: https://web.archive.org/web/20130410033524/http://pleiades.stoa.org:80/places/vocab

**Comment by paregorios** [comment]
The document is still on the site, there just appears to be a broken redirect:

https://pleiades.stoa.org/docs/partners/pleiades-rdf-vocabulary

**Comment by paregorios** [comment]
I would prefer for this document to be found under ```https://pleiades.stoa.org/help/concepts/pleiades-rdf-vocabulary```, for the RDF to report the new location, and for both https://pleiades.stoa.org/places/vocab and https://pleiades.stoa.org/docs/partners/pleiades-rdf-vocabulary to redirect to that new uri.

**Comment by cguardia** [comment]
The aliases didn't work for /places/vocab, because of an apache rewrite rule. Fixed that, updated ansible, and moved the doc to help as requested. All three urls should work now.

**Comment by paregorios** [comment]
This looks good. Closing as resolved.
