### ISSUE TITLE
Connections missing in CSV export

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#3]
Working with the CSV exports to walk the graph of connections, I noticed a suspicious absence of connections for Hadrian's Wall. The offending line in pleiades-places-latest.csv on 8/11/14 is attached as a single line CSV with headers for ease of debugging.

Meanwhile, http://pleiades.stoa.org/places/91358 has a large number of connections. Perhaps a limit somewhere in the export is being hit, causing no connections to show up in the export? Also of note is that examining the first place in the list of Hadrian's Wall connections, http://pleiades.stoa.org/places/89288 also has an empty "connectsWith" field in the CSV (where it would be expected that it should have 91358).

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/69, where it was originally opened  by @ryanfb .

**Comment by davisagli** [comment]
This appears to be working now; it probably fixed itself when we migrated to separate content items as connections.

**Comment by paregorios** [comment]
@ryanfb happy?

**Comment by ryanfb** [comment]
Looks good for spot-checks of the latest CSV dumps on the original report of places 91358 and 89288.

See also: #224 (not yet resolved by this fix)
