### ISSUE TITLE
add "title" field to connections - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#300]
As a Pleiades contributor adding/editing a connection, I am able to enter a title for the connection item, overriding the dynamic title drawn from the connected place.

Recent guidelines changes suggest particular naming strategy for connections; however, the current connection form hides(?) the title field, which prevents conformance with the Guidelines.

**Comment by paregorios** [comment]
Renaming via menu item action doesn't affect title either.

**Comment by paregorios** [comment]
need to add link to relevant bit of guidelines

**Comment by cguardia** [comment]
- [x] Make title visible again.
- [x] Use title field in view.

**Comment by paregorios** [comment]
This looks good! Please merge to master and deploy to production.

**Comment by paregorios** [comment]
This is working well on production.
