### ISSUE TITLE
workflow item selection is too greedy - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#301]
Select a single item (inside a place) in the "folder listing", select the "change state" button below: on the "publishing process" page discover that everything inside the place has been selected for action, not just the item manually selected. 

As an authenticated Member with appropriate role on the relevant content object(s):

- Initiate a workflow state change via the actions menu on a ```place``` item. When the "Publishing Process" page displays, I will see that not only the ```place``` item is selected, but also all contained content items that have the same origin state as the parent ```place``` item. __This currently works__. 

- Initiate a workflow state change via the actions menu on a ```location```, ```name```, or ```connection``` item. When the "Publishing Process" page displays, I will see that __only__ the item I started from is selected.  __This currently works__.

- View the "folder listing" for a particular ```place```. Select (checkbox) a single, contained ```location```, ```name```, or ```connection```, then select the "change state" button. On the "Publishing Process" page, I see listed all contained content items within the ```place```, but only the one(s) I selected in the folder listing are selected for state transition. __This currently FAILS__ (all sibling content items and the parent place get selected). 

- When on the "Publishing Process" page, I can always check/uncheck/recheck any item in the current context as I wish, so that the publishing process affects only what I want. __This currently FAILS__.

**Comment by rmhorne** [comment]
Possibly related: I attempted to publish a place (https://pleiades.stoa.org/places/403627900) with only one location selected, and it would not leave the "pending" state.

**Comment by paregorios** [comment]
I moved @rmhorne 's issue to #364 so we can keep this ticket focused specifically on the publication transition selection behavior. I will add story steps.

**Comment by alecpm** [comment]
Tasks:

* [x] Ensure folder listing change state button passes checked items through to advanced workflow form
* [x] Ensure that advanced workflow form checks only the items selected on the folder listing form.

**Comment by alecpm** [comment]
This is up on staging for review.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
This is live on production.
