### ISSUE TITLE
busted: full-screen map view of recent changes -- 1

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#308]
I am unable to get the full screen map view of 'recent changes' in Pleiades to load - 

https://pleiades.stoa.org/map_recent

I have tried this using both Chrome and Safari browsers. Thanks!

**Comment by ryanfb** [comment]
It looks like this was broken in the HTTPS switchover. I see a bunch of mixed content warnings that all the JQuery/Leaflet JS/CSS aren't loaded because they're on HTTP but the page is HTTPS.

**Comment by paregorios** [comment]
Identify and fix mixed content problems so the map works over https

**Comment by cguardia** [comment]
This is on staging.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by cguardia** [comment]
Deployed.
