### ISSUE TITLE
Add "summary" and "details" fields to connections - 1

### ISSUE THREAD

**Issue by rmhorne** [isawnyu/pleiades-gazetteer#310]
Like the places page, connections should have a details field that allows creators to put in more verbose information on a connection. Also desired: A summary field in addition to the title (see #300 ) to make the presentation of connections more in-line with our places, locations, and names.

**Comment by rmhorne** [comment]
As we continue to expand connections (including time adjustments - see #358 ), it is becoming apparent that we need more details / descriptions for them, especially for connections that may be controversial. Perhaps a "full conversion" of connections so that they have most of the same options presented by the places type.

**Comment by paregorios** [comment]
@rmhorne What am I missing besides summary, details, and (#300) title?

**Comment by rmhorne** [comment]
@paregorios: I think that does it, unless we want to consider connections as standalone entities that have URIs which are not tied to places (i.e. /connections/foo as opposed to  /places/foo/bar). That might be an entirely different philosophical / practical discussion however.

**Comment by paregorios** [comment]
Thanks. I think for now keeping them within the context of their originating place is consistent with the way we treat names and locations. We don't have sufficient development resources right now IMO to contemplate a complete reswizzle of the data model.

**Comment by cguardia** [comment]
- [x] Change schema to add back description and text, with correct labels.
- [x] Display new fields in view.

**Comment by paregorios** [comment]
This looks good! Please merge to master and deploy to production.

**Comment by paregorios** [comment]
This is working as expected on production
