### ISSUE TITLE
GeoJSON Polygons should follow right-hand rule -- 5

### ISSUE THREAD

**Issue by ryanfb** [isawnyu/pleiades-gazetteer#320]
Use `npm install -g @mapbox/geojsonhint`, then run against e.g. https://pleiades.stoa.org/places/109255/json, and you'll get a warning that Polygons and MultiPolygons should follow the right-hand rule. This was a normative change when GeoJSON became an RFC: https://tools.ietf.org/html/rfc7946#section-3.3

From ryanfb/pleiades-geojson#3, it seems like in every instance simply *reversing* any Polygon coordinates from their current ordering will make them conform, i.e. the current order is left-hand.

**Comment by paregorios** [comment]
priority:high because this is data corruption

**Comment by paregorios** [comment]
On step of generating JSoN, examine the geometry and ensure they follow the right-hand rule.

**Comment by MatthewWilkes** [comment]
I believe I've made sufficient changes to make this work, as can be seen on http://192.168.1.50:9080/plone/places/423064/json and http://192.168.1.50:9080/plone/places/423064/json

I used http://geojsonlint.com/ as an easy way of double checking this and visualising the data.

I think a good way of checking this will be to wait for the next bulk export from staging (those **do** happen, right?) and bulk verify that file.

**Comment by paregorios** [comment]
Need help: how do I view bulk exports on staging so I can review this?

**Comment by MatthewWilkes** [comment]
You can get them with a slightly complex cURL command:

    curl -O http://pleiades.jazkarta.com/downloads/pleiades/json/pleiades-places-latest.json.gz -H "Host: atlantides.org"

or from `/var/www/atlantides.org/downloads/pleiades/json/` if you ssh in to the server.

**Comment by paregorios** [comment]
Both bulk and individual serializations on staging are now correct. This change is ready to merge to master and deploy to production.

**Comment by paregorios** [comment]
Was this deployed?

**Comment by ryanfb** [comment]
> Was this deployed?

With the instructions/link in the original comment, I still get a right-hand rule warning.

**Comment by paregorios** [comment]
It looks like this might be the code, which has been merged to staging but has not been merged to master: https://github.com/isawnyu/pleiades-geographer/tree/features/righthandrule

**Comment by alecpm** [comment]
It definitely appears to be the case that the feature was not merged. When I ran the staging branch of Products.PleiadesEntity locally I got an `ImportError: cannot import name is_clockwise`. I'll take care of merging this work.

**Comment by alecpm** [comment]
I found relevant changes is `Products.PleiadesEntity`, `pleiades.geographer`, and `pleiades.json`, merged those to the respected masters, and updates the repo pins in the production buildout. This should be live on production now.

**Comment by paregorios** [comment]
Both bulk and individual serializations on production are now correct.
