### ISSUE TITLE
Import OSM watershed

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#321]
The current OSM import of relations is restricted to  'multipolygon' and 'waterway'.

For this place https://pleiades.stoa.org/places/874639, it would be advantageous to import the Batman basin watershed from OSM, which is not classified as  'multipolygon' and 'waterway', but as 'watershed'. http://www.openstreetmap.org/relation/2264091

**Comment by paregorios** [comment]
I'm consolidating this concern into #341. Closing.
