### ISSUE TITLE
"promote to place" should do more - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#332]
Desireable:
 - copy references from location to new parent place
 - construct place title free of conventional location title components

**Comment by paregorios** [comment]
title would be identical unless the location title started with "OSM Location of" or "Location of" in which case these initial substrings would be removed for the place title.

**Comment by alecpm** [comment]
So it looks like it already copies references, but explicitly excludes those of type `citesAsDataSource` (https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/browser/location.py#L16). Do we want to start including those types of references? Or when you say references do you mean AT `relatedItems` (it doesn't seem like you're using those generally)?

**Comment by alecpm** [comment]
The title update is in place on staging for review. I'll implement the reference change once I better understand the intention.

**Comment by paregorios** [comment]
Regarding references:

https://pleiades.jazkarta.com/places/227802613/athena-t was a location under https://pleiades.jazkarta.com/places/580107 and I "promoted to place" which led to the creation of https://pleiades.jazkarta.com/places/227802613 . But the reference to "Perseus, Sounion, Temple of Athena (Building)" on the location did not get copied to the new place resource.

**Comment by paregorios** [comment]
title cleanup works on staging

**Comment by alecpm** [comment]
References should be copied on staging now:

https://pleiades.jazkarta.com/places/958536675

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.

**Comment by paregorios** [comment]
This is indeed working on production.
