### ISSUE TITLE
Time period language on edit forms is misleading -- 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#339]
from @atomrab:

> The description of the temporal attestations for Locations inherit the language used for Name resources (e.g. "time period for which this name is attested"). To avoid confusion, we should perhaps say "location was active/a locus of activity/etc" -- or, if both name and location are drawing from the same template, make the wording less name-specific.

**Comment by paregorios** [comment]
+1 on this being a problem for users from Jamie Novotny in Munich.

**Comment by paregorios** [comment]
To restate the concern:

In the "edit" view for locations, names, and connections, the "Time Period" subsection of the "Time Period and Confidence Level" widget that is used by the "Temporal Attestations" widget refers to "this name" even if the context is not a name. Consider this example, from the "location" edit view:

<img width="525" alt="Screen Shot 2019-03-25 at 2 49 35 PM" src="https://user-images.githubusercontent.com/263285/54949699-ad2baa80-4f0d-11e9-910e-197b83807382.png">

The offending code seems to be in ```PleiadesEntity/Products/PleiadesEntity/content/TemporalAttestation.py```:

```python
    atapi.StringField(
        name='timePeriod',
        widget=FilteredSelectionWidget(
            label="Time period",
            description="Select time period for which this name is attested",
            label_msgid='PleiadesEntity_label_timePeriod',
            description_msgid='PleiadesEntity_help_timePeriod',
            i18n_domain='PleiadesEntity',
        ),
        description="Time period for which this name is attested",
        vocabulary_factory="pleiades.vocabularies.time_periods",
        enforceVocabulary=1,
        required=1,
    ),
```

Is it possible to get descriptions (note both places, above) that properly reference the containing type?

**Comment by paregorios** [comment]
"Select the time period to be associated with this resource."

**Comment by alecpm** [comment]
This change (isawnyu/PleiadesEntity#38) is deployed to staging for review.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
