### ISSUE TITLE
place-types.ttl is empty -- 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#340]

**Comment by paregorios** [comment]
The code that is supposed to generate this file is in pleiades.rdf/pleiades/rdf/common.py. Is it possible that this aspect wasn't upgraded when the place types vocabulary was moved out of ATVocabularyManager and into settings?

**Comment by paregorios** [comment]
priority high becuase data corruption

**Comment by paregorios** [comment]
download files are here: http://atlantides.org/downloads/pleiades/rdf/

**Comment by cguardia** [comment]
This is on staging now, meaning you can run

bin/instance1 run dump-scripts/rdf.py -v place-types

and the correct data will now show up (it errored out previously).

**Comment by paregorios** [comment]
Output from the script looks good. Please merge to master, deploy to production, and verify that it runs correctly on the regular dump schedule.

**Comment by paregorios** [comment]
I will undertake to complete review of this on production after the scheduled next cycle for rdf export, which is on Sunday.
