### ISSUE TITLE
add support for import of additional OSM way types - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#341]
We'd like to be able to get relations of the following types that are not facilitated now:

 - boundary: https://www.openstreetmap.org/relation/3303726
 - watershed: https://www.openstreetmap.org/relation/2264091

keep existing values (multipolygon, waterway)

**Comment by paregorios** [comment]
I note that the OSM wiki doesn't seem to be up-to-date with regard to all the possible values:

https://wiki.openstreetmap.org/wiki/Types_of_relation

**Comment by alecpm** [comment]
These are to be imported as type "relation" rather than type "way", correct?

**Comment by alecpm** [comment]
Assuming it's `relation` this is up on staging for review.

**Comment by paregorios** [comment]
Assumption was correct. And this works as desired. Please merge to master and deploy to production.
