### ISSUE TITLE
OSM import on Pleiades is broken

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#342]
An error occurred while attempting to import an OSM node to create a location for a [new place](https://pleiades.stoa.org/places/153179566) that, in turn, had been migrated from being a subordinate location on another place page.

https://pleiades.stoa.org/places/153179566/@@create-location-osm

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.PleiadesEntity.browser.osm, line 57, in __call__
Module newrelic.api.external_trace, line 124, in dynamic_wrapper
Module httplib2, line 1609, in request
Module httplib2, line 1404, in _request
Module newrelic.api.external_trace, line 124, in dynamic_wrapper
Module httplib2, line 1609, in request
Module httplib2, line 1351, in _request
Module httplib2, line 1272, in _conn_request
Module newrelic.api.external_trace, line 124, in dynamic_wrapper
Module httplib2, line 1059, in connect
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by paregorios** [comment]
I saw this error on a different OSM import this morning. On the face of it, it looks like OpenStreetMap has allowed the SSL certificate on their API server to expire or it has been configured incorrectly. But perhaps it has to do with library upgrades, possibly required on our side:

https://github.com/hotosm/osm-tasking-manager2/issues/976

**Comment by paregorios** [comment]
Other users are now reporting this problem too.

**Comment by serviliusahala** [comment]
I have encountered it multiple times myself, and so have held off on add'l
OSM import attempts for locations.

============================================
Jeffrey A. Becker, Ph.D. RPA
Department of Classical and Near Eastern Studies
Binghamton University - SUNY
jeffrey.becker@gmail.com; 617-877-4484
Twitter: @servilius_ahala <https://twitter.com/servilius_ahala>
HCommons: @serviliusahala
<https://hcommons.org/members/serviliusahala/notifications/>
orcid.org/0000-0001-8759-3774

============================================

**Comment by paregorios** [comment]
Yeah, it's clearly a universal problem. OSM import on Pleiades is broken.

**Comment by paregorios** [comment]
[Code inspection](https://github.com/isawnyu/PleiadesEntity/blob/859d23303d9deb2cb6a4f609e424c50d3359c2b4/Products/PleiadesEntity/browser/osm.py#L53-L62) and some non-production testing indicates that the problem may be that we are building the OSM API request with http which then **should** redirect to https, but something is going wrong somewhere in that process. Perhaps simply by updating to use https and possibly also switching from using ```httplib2``` to ```requests``` (which is already in the stack for more recent code that interacts with Flickr and Zotero), we can get around this problem.

**Comment by paregorios** [comment]
Fixed with @d2f561ab6cd837352732cbc9a6faef8c82f2b974 on Pleiades entity and version pin update in pleiades-buildout: c59e0a5c6963e229b5cb9a96e6d54a8843514ba5

Deploy to production.
