### ISSUE TITLE
Neighborhood KML seems to be broken - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#343]
See, for example:

https://pleiades.stoa.org/places/390922209/neighborhood-kml

which throws errors about "unexpected element html" in Google Earth.

**Comment by paregorios** [comment]
priority:high because user experiences failure; we need to investigate how this is broken and how hard it would be to fix then make a go/no go determination on either fixing it or removing the option from the interface.

**Comment by paregorios** [comment]
Development:

 - eliminate link to "neightborhood kml" in HTML and __all other serializations including dumps__
 - put apache rewrite rule in place to emit an HTTP status code in the response ("410 Gone") for any attempt to get to any "neighborhood kml" uri in future

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
Brilliant! Please merge to master and deploy to production.

**Comment by cguardia** [comment]
Deployed.

**Comment by cguardia** [comment]
Well, it seems that the 410 redirect is not working in production, not sure why.

**Comment by cguardia** [comment]
Never mind, forgot to restart the cache.
