### ISSUE TITLE
connection attributes are not included in JSON -- 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#345]
We enhanced the connection content type, adding relationship types, references, and more. None of these new attributes appear in the JSON serializations (individual or export/dump), but they should if we are to meet our obligations of complete openness and data archiving.

For example, this is all we see at present in [the JSON for Syracuse](https://pleiades.stoa.org/places/462503/json):

```json
"connectsWith": [

    "https://pleiades.stoa.org/places/462492",
    "https://pleiades.stoa.org/places/991353",
    "https://pleiades.stoa.org/places/981549",
    "https://pleiades.stoa.org/places/462492",
    "https://pleiades.stoa.org/places/991353",
    "https://pleiades.stoa.org/places/981549",
    "https://pleiades.stoa.org/places/219478548",
    "https://pleiades.stoa.org/places/895916364",
    "https://pleiades.stoa.org/places/462204",
    "https://pleiades.stoa.org/places/915204962",
    "https://pleiades.stoa.org/places/473876126",
    "https://pleiades.stoa.org/places/649857186",
    "https://pleiades.stoa.org/places/560149180",
    "https://pleiades.stoa.org/places/786829671",
    "https://pleiades.stoa.org/places/418729933",
    "https://pleiades.stoa.org/places/copy_of_462204",
    "https://pleiades.stoa.org/places/649857187"

],
```

**Comment by paregorios** [comment]
Here's what we're looking for in the JSON (example excerpted from, and expanded upon, JSON for the [Forum of Beneventum](https://pleiades.stoa.org/places/585690564). Data under keys "bbox" and "connectsWith" are present now, and the logic for same must not be changed. We are introducing a new key "connections", which is the focus of this ticket. The objects in the "connections" array are modeled on the "locations" array already found in our JSON files. Main considerations:

 - Only the keys shown in the example below should be included (there are some location-specific keys we have omitted). 
 - We are adding only two connection-unique keys: "connectionType" and "connectionTypeURI" 

```json
...
    "bbox": [
        14.7732856,
        41.1310668,
        14.7741272,
        41.1318129
    ],
    "connections": [
        {
            "@type": "Connection",
            "associationCertainty": "certain",
            "attestations": [
            ],
            "contributors": [
                {
                    "homepage": null,
                    "name": "Tom Elliott",
                    "uri": "https://pleiades.stoa.org/author/thomase",
                    "username": "thomase"
                }                
            ],
            "created": "2016-07-13T14:58:14Z",
            "creators": [
                {
                    "homepage": null,
                    "name": "Sean Gillies",
                    "uri": "https://pleiades.stoa.org/author/sgillies",
                    "username": "sgillies"
                }
            ],
            "description": null,
            "details": null,
            "end": null,
            "connectionType": "at",
            "connectionTypeURI": "https://pleiades.stoa.org/vocabularies/relationship-types/at", 
            "connectsTo": "https://pleiades.stoa.org/places/432721",
            "history": [
                {
                    "comment": "ctype",
                    "modified": "2019-03-25T19:53:14Z",
                    "modifiedBy": "thomase"
                },
                {
                    "comment": "Created by admin",
                    "modified": "2016-07-13T14:58:14Z",
                    "modifiedBy": "admin"
                }
            ],
            "id": "432721",
            "provenance": "Pleiades",
            "references": [
            ],
            "review_state": "published",
            "start": null,
            "title": "Beneventum/Maleventum ",
            "uri": "https://pleiades.stoa.org/places/585690564/432721"
        }
    ],
    "connectsWith": [
        "https://pleiades.stoa.org/places/432721"
    ],
...
```

**Comment by paregorios** [comment]
@rmhorne how does the above JSON suggestion look to you?

**Comment by paregorios** [comment]
It looks like @cguardia has finished review of the pull request, so I think the next step (right @skleinfeldt ?) is to put this change on staging so that I can look at the json output from a live system.

**Comment by skleinfeldt** [comment]
All the project board columns are about the production deploy, I would have thought the "reviewing" column implied that it is on staging already. We might want to discuss Monday how this should work, taking into account PR reviews.

In any event, @cguardia or @alecpm can you please deploy this to staging?

**Comment by MatthewWilkes** [comment]
@paregorios This has been deployed to staging

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by MatthewWilkes** [comment]
Deployed this to live

**Comment by MatthewWilkes** [comment]
Deployed this to live

**Comment by paregorios** [comment]
Looks good on production. Closing as resolved.
