### ISSUE TITLE
Via Campana?

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#346]
There was a duplicate stub in drafting state for [Via Campana?](https://pleiades.stoa.org/places/231839930/?searchterm=via%20campana*) so I attempted to merge resources and then to delete the duplicate stub, but I've done something wrong as the non-deleted [place](https://pleiades.stoa.org/places/231839930/?searchterm=via%20campana*) now produces this error -->

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 110, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 70, Column 4
Expression: <PathExpr standard:u'context/@@where'>
Names:
{'container': <Place at /plone/places/231839930>,
'context': <Place at /plone/places/231839930>,
'default': <object object at 0x7fc79847abc0>,
'here': <Place at /plone/places/231839930>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fc75bff8628>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/231839930/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/231839930/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.geographer.views, line 9, in __call__
Module pleiades.geographer.geo, line 571, in coords
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 539, in reprPoint
Module pleiades.geographer.geo, line 427, in preciseExtents
Module pleiades.geographer.geo, line 426, in <lambda>
Module pleiades.geographer.geo, line 502, in precision
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 473, in reprExtent
Module pleiades.geographer.geo, line 421, in __init__
Module Products.PleiadesEntity.content.Named, line 155, in getConnectedPlaces
AttributeError: 'NoneType' object has no attribute 'UID'

**Comment by paregorios** [comment]
Looks like a broken connection link. I’ll hunt it down through the 
ZMI.

**Comment by paregorios** [comment]
This is resolved.
