### ISSUE TITLE
Home Page Search Needs Feedback for Negative Results - 2

### ISSUE THREAD

**Issue by sarcanon** [isawnyu/pleiades-gazetteer#351]
When performing a search from home page, if the query produces no results, no feedback is given to the user at all. This potentially creates the impression the query was not performed.

Steps to reproduce:
1. From home page, enter "XYZXYZ" into form field, and hit Enter.
2. Observe that no user feedback is provided to indicate query failed.

Test environment: Chrome Version 67.0.3396.99, Windows 10 (x64)

**Comment by paregorios** [comment]
Ideally, we'd provide some text with a suggestion like:

> We found zero results for 'XYZXYZ' - did you mean "Xylopolis"?

How expensive would it be to make the suggestion based on the first place or a random place initially matching the first letter or two (as here) in the failed query? If we did such a suggestion, I'd say link the "Xylopolis" (or whatever) to the place record so they can click through, but don't provide a map.

**Comment by skleinfeldt** [comment]
The standard - that is Google - way of presenting "did you mean XYZ" in response to a misspelling is to link XYZ to the results of an XYZ search. You are proposing a different behavior - which could be the right thing to do, but it's always worth pausing to think when breaking a norm.

**Comment by paregorios** [comment]
In retrospect, I think @skleinfeldt's suggestion is better. Maybe something like:

> We found zero names that start with 'XYZXYZ' - do an advanced search instead?

The "do an advanced search instead" text should link to the advanced search section.

In addition to being more similar, I suspect it would cover more use cases in discovery failure recovery.

**Comment by paregorios** [comment]
I would like to hold off on work on this ticket until we have assessed #405 and how costly the downstream work from it is going to be. This particular issue, though important, is lower priority than making our maps as modern and as price-conscious as they can be.

**Comment by paregorios** [comment]
cc @skleinfeldt ^^^

**Comment by paregorios** [comment]
@MatthewWilkes please work on #405 before you address this ticket. See further https://github.com/isawnyu/pleiades-gazetteer/issues/405#issuecomment-525411609

**Comment by cguardia** [comment]
This is on staging now.

**Comment by paregorios** [comment]
I cannot review this ticket until staging is working again. It is currently timing out.

**Comment by alecpm** [comment]
The instance seems to be offline. Stopping and starting it now.

**Comment by alecpm** [comment]
It's back up.

**Comment by alecpm** [comment]
Issue seems likely related to high RAM usage. I'll need to tweak the staging memmon to kill the processes at lower RAM usage, or have fewer plone instances running.

**Comment by paregorios** [comment]
This looks great! Please merge to master and deploy to production.
