### ISSUE TITLE
Connection Maps Weight

### ISSUE THREAD

**Issue by rmhorne** [isawnyu/pleiades-gazetteer#355]
It might be a good idea to weight the different types of connections differently for generating a representative point. For instance "borders" and "is near / close / etc" should be more heavily weighted than "part of". Some connection types, like "allied to", (especially if we expand the connection types) should be excluded from representative points altogether, and perhaps excluded from the map as well.

**Comment by paregorios** [comment]
duplicate for #316; closing after transferring initial comment as it bears on suggested weighting algorithm
