### ISSUE TITLE
Search result map assigns incorrect coordinates to names - 3

### ISSUE THREAD

**Issue by rmhorne** [isawnyu/pleiades-gazetteer#356]
Every name with the same name is getting the same wrong coordinates on the search result map (at least as related to popups). See https://pleiades.stoa.org/search?b_start:int=0&_authenticator=9cab0223c063dbfdf19d09210eb21363b9498664&submit=Search&SearchableText=phrygia%2A for this in action with Phyrgia. 

As a Pleiades user conducting an advanced search, I will see all matching content items in a batch displayed in a list with a map alongside. In the map, each matching content item will be represented with a map symbol at the correct coordinates. For a ```place```, the coordinates will be the "representative point" for that ```place```. For a ```location```, the coordinates will be the centroid of that ```location```'s geometry. For a ```name``` or a ```connection```, the coordinates will be drawn from the "representative point" of the containing ```place```.

__Currently__, ```name```s are being incorrectly mapped when there are multiple, identical ```name```s drawn from different ```place```s in the search results.

**Comment by paregorios** [comment]
Confirmed by @rmhorne just now. I need to make sure I understand this ahead of planning poker so I can answer questions.

**Comment by paregorios** [comment]
priority:high because user task failure is possible in this context

**Comment by rmhorne** [comment]
In the Phyrgia example, the last Phyrgia is the location chosen by the map. If I find other cases of this error I will confirm if this is "standard" bug behavior.

**Comment by alecpm** [comment]
Tasks:

* [x] Determine cause of incorrect name/id based coordinate assignment
* [x] Use unique identifier to determine coordinates.

**Comment by paregorios** [comment]
See now #408 and its prerequisite #405. Should we defer work on this ticket until we know whether we're going to have to rewrite our map code on this page?

**Comment by alecpm** [comment]
I think the issues are somewhat orthogonal, but if this isn't urgent it might be more expedient to upgrade the map JS as needed before making these changes. Task 1 can certainly be done independently of the specific client-side map implementation.

**Comment by paregorios** [comment]
Let's go ahead with this one for now.

**Comment by alecpm** [comment]
I think I fixed this on staging. The results there are a bit different, but there appear to be multiple `Phrygia` map points now.

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
This is live on production.

**Comment by paregorios** [comment]
@rmhorne how does this look to you?

**Comment by paregorios** [comment]
This seems to be working well on production.
