### ISSUE TITLE
places rdf ttl throws parse error

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#359]
From Emmanouil Ntoulias via email:

> Hello,
>
> I've download the pleiades dataset from
https://lod-cloud.net/dataset/pleiades and tried to store it in a local
endpoint. Unfortunately I get a parse error in multiple files: ERROR
org.openrdf.rio.helpers.ParseErrorLogger  - [Rio fatal] Expected an RDF
value here, found ']' (16439, -1) . This example is from the
"places-8.tll" file. The line is:
> 
>     cito:citesAsRelated [ ];
>
> According to turtle syntax (https://www.w3.org/TR/turtle/#sec-grammar) i
believe the inside of the brackets should not be empty.
> 
>      ([14] 	blankNodePropertyList 	::= 	'[' predicateObjectList ']')
>
> Or am I wrong? Regardless, thank you for your time

**Comment by paregorios** [comment]
Note to self:

First step: check to see if this problem is present in the up-to-date exports at https://pleiades.stoa.org/downloads/

**Comment by manosntoulias** [comment]
Hello again,

I've checked with the latest dataset you suggested and the error is still there. :(

**Comment by paregorios** [comment]
priority:high because data corruption

**Comment by paregorios** [comment]
I'm unclear as to what best practice would be here. I guess there are at least the following options:

 - when there are no items in list, emit [rdf:nil](https://www.w3.org/TR/rdf-schema/#ch_nil) instead of ```[]```
 - omit the entire term (e.g., as here ```cito:citesAsRelated```)
 - something else

Suggestions? @manosntoulias @rybesh @sfsheath @gabrielbodard @ryanfb @aboutgeo

**Comment by rybesh** [comment]
I think this is a bug in the parser the OP is using; `[]` is valid Turtle indicating an anonymous (blank) node with no properties. Try converting the following to ntriples at http://www.easyrdf.org/converter:

```turtle
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
[] foaf:knows [] .
```

You will get:

```
_:genid1 <http://xmlns.com/foaf/0.1/knows> _:genid2 .
```

To verify this I used the riot (Jena) parser on `places-8.ttl`, and it validates (`riot --validate places-8.ttl` returns no output).

**Comment by manosntoulias** [comment]
But according to rule [7] of the syntax I linked predicatedObjectList can't be empty. It must have at least one verb and followed by one objectList:

[7] | predicateObjectList  ::=  verb objectList (';' (verb objectList)?)*

Is this not the official turtle syntax?

**Comment by rybesh** [comment]
`[]` is not a `blankNodePropertyList`, it is an [`ANON`](https://www.w3.org/TR/turtle/#grammar-production-ANON).

**Comment by paregorios** [comment]
In any case, I don't think we should be writing citation-type triples when there's no object (and this will only be happening when we have malformed bibliographic data in the database -- i.e., legacy stuff that hasn't been updated). 

Implementation for developer:

 - if serialization a citation and there is none of [accessURI, alternateURI, bibliographicURI] then do not emit citation-type triple at all because it is a mal-formed citation

**Comment by paregorios** [comment]
blocked for #396

**Comment by paregorios** [comment]
Resolution of issue #396 should eliminate the case of empty lists of objects for these citation-related verbs in our ttl. Will double-check after next full export.
