### ISSUE TITLE
prepare to migrate to new server -- 8

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#360]
tummy has provisioned a new production server for us. I'd like to get pleiades fully up and running on this server and switch it over to being the production box. I'd like to ride shotgun with the developer(s) implementing this ticket so that I have a better idea of what and how we'd have to do things to provision yet another server in future. I thinik the main tasks are:

 - [x] verify developer logins and sudo on the new box
        - [ ] ~~get tummy help to fix as necessary~~
 - [x] install and verify prerequisites for running our ansible setup
        - [ ] update pleiades.ansible documentation to reflect these steps
 - [x] run and verify pleiades.ansible to deploy the full server (iterate as necessary)
       - [ ] update pleiades.ansible documentation to reflect these steps
 - [x] copy over the production database and blob content
 - [x] get key members of the isaw community to test and verify
 - [x] get another developer not so far involved to do a configuration and security audit

Moved remaining steps to separate ticket: #390 for which this ticket is now a "blocker"

**Comment by paregorios** [comment]
priority: high because performance is a grant deliverable and this new server has SSD and MOAR POWRRR

**Comment by alecpm** [comment]
The server at 66.35.62.81 is now running the full pleiades stack with the original SSL certs in place. You should be able to test it by editing your local `/etc/hosts` file to add the following line:

```66.35.62.81 pleiades.stoa.org atlantides.org api.pleiades.stoa.org```

Then you should be able to visit any of the above IPs/hostnames and test the site.

**Comment by paregorios** [comment]
I've given it a workout this morning and cannot find anything to complain about. :)

I'll get tummy rolling on the security audit and try to recruit somebody else to poke around on the new server and see if they can get anything to break.

**Comment by paregorios** [comment]
Security audit has been requested. I will update here when scheduled and when complete.

**Comment by paregorios** [comment]
/me to split out actual production swap 0ut steps to a separate ticket for iteration 2

**Comment by paregorios** [comment]
@alecpm were there any documentation changes needed for our ansible setup based on the above work that still need to be done? If not, then I'm prepared to close this ticket.

**Comment by alecpm** [comment]
It does not appear that any updates are needed for the ansible documentation.
