### ISSUE TITLE
remove google analytics from pleiades -- 1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#362]
Performance and privacy ftw.

**Comment by paregorios** [comment]
priority:high because performance is a grant deliverable

**Comment by alecpm** [comment]
I've updated the profile to remove the GA script from the resource registry (https://github.com/isawnyu/pleiades-notredame/pull/4) and remove GA from the static frontpage html (https://github.com/isawnyu/pleiades-frontpage/pull/11). These have been merged to staging branches and deployed to https://pleiades.jazkarta.com for review.

**Comment by paregorios** [comment]
Looks good. Please merge to master and deploy to production.
