### ISSUE TITLE
default text for content "publish" action - 5

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#365]
As an authenticated pleiades user with the "Reviewer" role preparing to __publish__ a piece of content, I am currently presented with an empty "comments" field on the "Publishing Process" page:

<img width="636" alt="Screen Shot 2019-03-25 at 3 13 15 PM" src="https://user-images.githubusercontent.com/263285/54951024-a6526700-4f10-11e9-8cf0-fcecdb0b2dca.png">

Instead, I would like to see the comments box pre-populated with:

 - the most recent "submit" comment made to the top-level object at the last workflow transition
 - any and all iterate save messages made since that last "submit" state transition (if there were any).

These should be concatenated with semicolon+space as delimiter.  If there are subordinate content items getting submitted at the same time, ignore their message/history.

I will be able to modify this text prior to submitting the content item for publication.

**Comment by paregorios** [comment]
See also nos. #76 and #366

**Comment by alecpm** [comment]
This is up on staging for review.

**Comment by paregorios** [comment]
This is working on staging as I would like. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
Deployed
