### ISSUE TITLE
default text for content "check in" action - 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#366]
As an authenticated pleiades user with the "Reviewer" role preparing to *check in* a working copy of a piece of content, I am currently presented with an empty "comments" field on the "Checkin" page:

![Screen Shot 2019-03-25 at 10 19 23 AM](https://user-images.githubusercontent.com/263285/54951227-1660ed00-4f11-11e9-81ee-30e757e1dc21.png)

Instead, I would like to see the comments box pre-populated with:

 - the most recent "submit" comment made to the top-level object at the last workflow transition
 - any and all iterate save messages made since that last "submit" state transition (if there were any).

These should be concatenated with semicolon+space as delimiter. If there are subordinate content items getting submitted at the same time, ignore their message/history.

I will be able to modify this text prior to submitting the content item for publication.

**Comment by paregorios** [comment]
See also issues nos. #76 and #365

**Comment by alecpm** [comment]
I think this is ready for review.

**Comment by paregorios** [comment]
This is working as desired on staging. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
Deployed
