### ISSUE TITLE
include both raw term keys and full term URIs in vocabulary content serialized into JSON -- 3

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#367]
The following has been split out separately from #271:

As a user of Pleiades export JSON, I will find the following terms in JSON data (both the individual files provided for each place using the /json stub and those provided via download):

## association certainty

Where we emit "associationCertainty" also emit "associationCertaintyURI":

```json
...
"associationCertainty": "certain",
"associationCertaintyURI": "https://pleiades.stoa.org/vocabularies/association-certainty/certain",
...
```

## attestation confidence and time periods

Under "attestations" when we emit "confidence" also emit "confidenceURI" and when we emit "timePeriod" also emit "timePeriodURI":

```json
...
"confidence": "confident",
"confidenceURI": "https://pleiades.stoa.org/vocabularies/attestation-confidence/confident",
"timePeriod": "roman",
"timePeriodURI": "https://pleiades.stoa.org/vocabularies/time-periods/roman",
...
```

## feature types

Wherever we emit "featureType" also emit "featureTypeURI":

```json
...
"featureType": [
    "plaza"
],
"featureTypeURI": [
    "https://pleiades.stoa.org/vocabularies/place-types/plaza"
],
...
```

## place types

Wherever we emit "placeTypes" also emit "placeTypeURIs":

```json
...
"placeTypes": [
    "plaza"
],
"placeTypeURIs": [
    "https://pleiades.stoa.org/vocabularies/place-types/plaza"
],
...
```

## location type

Wherever we emit "locationType" also emit "locationTypeURI":

```json
...
"locationType": [
    "representative"
],
"locationTypeURI": [
    "https://pleiades.stoa.org/vocabularies/location-types/representative"
],
...
```

## reference citation type

Wherever we emit "type" **under "references"***, also emit "citationTypeURI":

```json
...
"type": "citesAsDataSource",
"citationTypeURI": "http://purl.org/spar/cito/citesAsDataSource",
...
```

**Comment by paregorios** [comment]
It looks like @cguardia has finished review of the pull request, so I think the next step (right @skleinfeldt ?) is to put this change on staging so that I can look at the json output from a live system.

**Comment by skleinfeldt** [comment]
See https://github.com/isawnyu/pleiades-gazetteer/issues/345#issuecomment-480434404

**Comment by MatthewWilkes** [comment]
@paregorios This has been deployed to staging

**Comment by paregorios** [comment]
This looks good. Please merge to master and deploy to production.

**Comment by MatthewWilkes** [comment]
Deployed this to live

**Comment by paregorios** [comment]
Looks good on production. Closing as resolved.
