### ISSUE TITLE
figure out branches and staging

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#369]
From @skleinfeldt in email:

> there are various branches outstanding on various packages with unknown code quality, and we really don't understand the current state of staging.... 
> 
> @alecpm has a tentative plan in mind ...

**Comment by paregorios** [comment]
Blocker for isawnyu/PleiadesEntity#37

**Comment by alecpm** [comment]
I've set all the `staging` branches to match the tips of their respective `master` branches. In the cases where there were commits on `staging` that weren't on master I backed up the branch as `staging-20190403`. That was the case for [PleiadesEntity](https://github.com/isawnyu/PleiadesEntity) and [pleiades.notredame](https://github.com/isawnyu/pleiades-notredame), the rest were either some commits behind their respective `master` branches or already synced.

I also updated the buildout to add some missing version pins and use the latest New Relic integration in the `staging.cfg`.

**Comment by paregorios** [comment]
I will investigate the two repositories that had derelict changes on staging prior to the changes, but I see no reason to wait to embrace these changes. 

@alecpm is there really anything else that needs to be done here (e.g., re-deploying on staging), or should I just close this as complete?

**Comment by paregorios** [comment]
@alecpm do you concur that this ticket is ready to close?

**Comment by alecpm** [comment]
We've had a couple successful staging deployments, so I believe the answer is yes..
