### ISSUE TITLE
finish move to new production server

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#390]
Blocked by prep work outlined in #360 

Remaining steps:

 - [x] decide on a switchover window (date and time)
 - [x] alert tummy and pleiades community to switchover date
 - [x] reboot new server to verify that all processes restart correctly
 - [x] disable changes on legacy production and post notice about same; also email community list
 - [x] do final content copy-over and archive a copy 
 - [x] fire up pleiades on the new box and double-check everything from both a development and user point of view
 - [x] update DNS settings to make the new box the production machine
 - [x] verify all is well
 - [x] alert the community
 - [x] shut down pleiades on the machine being retired

**Comment by alecpm** [comment]
I did a reboot and all services appear to have restarted and were working correctly. In addition I made a preliminary copy of all data.

**Comment by paregorios** [comment]
I've ticked off several of the tasks above that I think are now done. @alecpm do you concur that that's all correct?

**Comment by alecpm** [comment]
I believe so, yes.

**Comment by paregorios** [comment]
waiting for DNS changes to propagate
