### ISSUE TITLE
citation information missing from RDF XML files - 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#397]
Consider the example of https://pleiades.stoa.org/places/872503244/rdf wherein we find references to nodes with auto-generated IDs:

```xml
<cito:citesForInformation rdf:nodeID="EMyJNUBS14792"/>
<cito:citesForInformation rdf:nodeID="EMyJNUBS14793"/>
```

but the referenced node ids do not appear as subjects anywhere else in the RDF file. 

This is presumably related to the problem we're seeing in #396.

**Comment by paregorios** [comment]
blocked for #396

**Comment by alecpm** [comment]
I believe this should have been fixed by the fix for #396.

**Comment by alecpm** [comment]
This appears to be fixed:

https://pleiades.stoa.org/places/140481/rdf

**Comment by paregorios** [comment]
Yet more joy! Please merge to master and deploy to production.
