### ISSUE TITLE
illegal trapped space in capgrid URI in RDF dump

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#398]
Somewhere between isawnyu/pleiades-capgrids and isawnyu/pleiades-rdf the following illegal URIs get serialized. There should be no spaces:

```
<http://atlantides.org/capgrids/79#A2 >
<http://atlantides.org/capgrids/79#A2 -extent>
```

The only place they seem to appear in the dumps is in places-7.ttl

> My original complaint was about unescaped spaces appearing in some IRIs.  E.g., the last character of the subject term and the character before the hyphen in the object term:
>
```
<http://atlantides.org/capgrids/79#A2 > osgeo:extent <http://atlantides.org/capgrid/79#A2 -extent> .
```
>
>Notice that the main issue may not even be that the spaces are unescaped, but that they appear in the first place.  Are they no simply the result of incorrect IRI creation?
>

_Originally posted by @wouterbeek in https://github.com/isawnyu/pleiades-gazetteer/issues/9#issuecomment-485065154_

**Comment by paregorios** [comment]
Here is where those URIs get serialized:

https://github.com/isawnyu/pleiades-rdf/blob/263454c72c6b3ad5a59836d5c6aa38bdf8ec9cc8/pleiades/rdf/common.py#L503

It looks like there must be a location(s) somewhere in Pleiades that has a trailing space in the grid square. Solution looks like:

 - find and clean up the offending content
 - add ```.strip()``` to the gridsquare formulation to be on the safe side (though no new BAtlas grid square locations should ever be created)

**Comment by paregorios** [comment]
There seems to be only one Pleiades place reference that still has a published location derived from BAtlas 79 A2: https://pleiades.stoa.org/places/776198/. Upon inspection, RDF exhibits the diagnostic problem:

```xml
<rdf:Description rdf:about="http://atlantides.org/capgrids/79#A2 "><osgeo:extent><osgeo:AbstractGeometry rdf:about="http://atlantides.org/capgrids/79#A2 -extent"><osgeo:asWKT>POLYGON ((29.5000000000000000 25.5000000000000000, 29.5000000000000000 26.0000000000000000, 29.0000000000000000 26.0000000000000000, 29.0000000000000000 25.5000000000000000, 29.5000000000000000 25.5000000000000000))</osgeo:asWKT><osgeo:asGeoJSON>{"type": "Polygon", "coordinates": [[[29.5, 25.5], [29.5, 26.0], [29.0, 26.0], [29.0, 25.5], [29.5, 25.5]]]}</osgeo:asGeoJSON></osgeo:AbstractGeometry></osgeo:extent></rdf:Description><pleiades:Location rdf:about="https://pleiades.stoa.org/places/776198/undetermined"><dcterms:contributor rdf:resource="http://viaf.org/viaf/59162760"/><dcterms:contributor rdf:resource="https://pleiades.stoa.org/author/sgillies"/><dcterms:contributor rdf:resource="https://pleiades.stoa.org/author/thomase"/><osspatial:partiallyOverlaps rdf:resource="http://atlantides.org/capgrids/79#A2 "/>
```

And the problem is also present in the TTL.

**Comment by paregorios** [comment]
I've retracted the BAtlas location associated with 776198, which has the effect of removing the problematic data from the online TTL and RDF/XML serializations for same. We'll know if that clears out the full dump after Sunday, when it runs again.

**Comment by paregorios** [comment]
This is resolved.

**Comment by wouterbeek** [comment]
@paregorios Thanks for improving the IRIs, but I just tried to upload <http://atlantides.org/downloads/pleiades/rdf/pleiades-latest.tar.gz> and still ran into illegal characters in IRIs.  The first issue occurs in entry `places-1.ttl` line 60,604 where an IRI contains an unescaped caret (`^`) characters.

The corresponding line in the Turtle grammar is as follows:
```
[18] | IRIREF | ::= | '<' ([^#x00-#x20<>"{}\|^`\] \| UCHAR)* '>' /* #x00=NULL #01-#x1F=control codes #x20=space */
```

It would be best to escape or remove all illegal characters from IRIs.
