### ISSUE TITLE
Downgrade Plone 5 staging server -- 1

### ISSUE THREAD

**Issue by skleinfeldt** [isawnyu/pleiades-gazetteer#399]
Now that the upgrade has run we can have a smaller, less expensive server.

**Comment by alecpm** [comment]
I've downgraded the server from a `t3.xlarge` ($0.1984/hr) to a `t3.small` ($0.0248/hr). You should be able to safely stop (but don't terminate) and start the instance at any time. It's named `Pleiades Plone 5` and lives in the N. Virginia (us-east-1) region.
