### ISSUE TITLE
supervisorctl on production throws "permission denied" error on startup

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#402]
Steps to recreate:

 - login to production
 - sudo to the appropriate username
 - cd to the pleiades4 directory
 - type "supervisorctl"
 - read the following error message:

```
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
supervisor>
```

Impact: cannot restart plones to pick up new vocabulary terms; consequence is any place using a new vocabulary term throws a traceback.

**Comment by alecpm** [comment]
`supervisor` is now an OS installed service that runs as root so that it can start it's various sub-services as whichever user it needs to. You should be able to use the following steps:

* Login to production
* type `sudo supervisorctl`
* `restart` whichever services need to be restarted

**Comment by paregorios** [comment]
Thanks @alecpm. This is resolved.
