### ISSUE TITLE
Pelagios portlet is failing again - 2

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#404]
Sigh.

**Comment by paregorios** [comment]
I've written to Rainer asking for pointers to the currently supported API.

**Comment by paregorios** [comment]
Rainer responds:

> the docs, including sample requests, are at
>
> https://github.com/pelagios/peripleo/blob/master/README.md
>
> The "REST-style access" bit will be most relevant for you
>
> https://github.com/pelagios/peripleo/blob/master/README.md#rest-style-access
>
> in particular the /place route. E.g. something like:
>
> https://peripleo.pelagios.org/peripleo/places/http:%2F%2Fpleiades.stoa.org%2Fplaces%2F423025?prettyprint=true 
>
> The response format should be unchanged to what you already had. Do let me know if you run into any trouble.

**Comment by paregorios** [comment]
Things that seem to need changing include:

## URI base

Our pelagios/peripleo portlet client is using a no-longer-supported URI for the pelagios API. I thought this was fixed previously, but can find no record of it in code so I guess I dreamed it. Anyway, we need to change [the pelagios URI base used in our portlet client](https://github.com/isawnyu/pleiades.portlet.pelagios/blob/master/pleiades/portlet/pelagios/client.py#L23) from

```http://pelagios.org/peripleo/places/```

to

```https://peripleo.pelagios.org/peripleo/places/```

(note that the protocol, the netloc, and the path all change). 

Beware: pelagios does __NOT__ recognize https URIs in the API, so [the code we have now that prefixes the Pleiades ID number](https://github.com/isawnyu/pleiades.portlet.pelagios/blob/master/pleiades/portlet/pelagios/client.py#L20) for a place with our old "http" base URI __is still correct and should not be changed__.

## Pelagios result URI cleanup

[Our client has code](https://github.com/isawnyu/pleiades.portlet.pelagios/blob/master/pleiades/portlet/pelagios/client.py#L38-L39) that grabs the "peripleo_url" from the "referenced in" results that we get back. This is still good, but [it looks like](https://peripleo.pelagios.org/peripleo/places/http:%2F%2Fpleiades.stoa.org%2Fplaces%2F550696) we don't need the step that replaces ```localhost``` netlocs anymore. So, where we currently have:

```python
uri = dataset['peripleo_url'].replace(
    '127.0.0.1:9002', 'peripleo.pelagios.org')
```

we can probably now just go to

```python
uri = dataset['peripleo_url']
```

**Comment by alecpm** [comment]
I think this is working on staging now:

https://pleiades.jazkarta.com/places/579885

**Comment by paregorios** [comment]
Looks good on staging. Please merge to master and deploy to production.

**Comment by alecpm** [comment]
This is live on production

**Comment by paregorios** [comment]
Verified working on production. cc @rsimon
