### ISSUE TITLE
Suppress stock DC "Location" field on all content types (3 story points)

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#433]
This field appears on the "Categorization" Tab for places, names, locations, and connections, as well as the plone stock content types. As Pleiades uses the term "Location" to mean something different, this causes confusion for users. Moreover, given that our content is specifically geographic in a detailed way, this core functionality is both redundant and inadequate. 

This default "Location" field should be suppressed on all user-facing interfaces.

**Comment by alecpm** [comment]
This is merged to master and deployed to https://pleiades.jazkarta.com for review.

**Comment by paregorios** [comment]
Looks great!
