### ISSUE TITLE
expire daily backups (2 story points)

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#435]
Pleiades performs a daily backup(?) and stores the results in ```/srv/python27-apps/pleiades4/var/backup/```, which eats up disk space. We need an automated process to keep a reasonable back number of these and archive or delete earlier ones.

-----

Epics: [Migrate to New Server](https://github.com/isawnyu/pleiades-gazetteer/wiki/Epic:-Migrate-to-New-Server)

**Comment by paregorios** [comment]
Retain 2 weeks.

**Comment by alecpm** [comment]
This change is on the new server. The prior configuration was manually running backups. The new configuration uses [`collective.recipe.backup`](https://pypi.org/project/collective.recipe.backup/) to provide pruning, etc. It's configured to retain 2 full backups and incrementals from those. Full backups are taken after every ZODB pack, which happens once a week, so it should retain 2 weeks worth of daily incremental backups.
