### ISSUE TITLE
hitting enter kills the current front page process (2 story points)

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#437]
No results are displayed if this happens too fast.

Steps to reproduce:

1. Visit https://pleiades.stoa.org/
2. Focus the search box.
3. Quickly type (without quotes) "Roma" and hit the enter key immediately.
4. Note that no results appear below.
5. Compare with what happens if you type "Roma" but do not hit the enter key.

Desired behavior:

If/when user hits enter key, results of a substring search are displayed below just as if they paused typing but didn't hit enter key.

**Comment by cguardia** [comment]
While I was able to duplicate this problem in the website, I have not been able to duplicate it locally. Will keep trying to find out what's going on.

**Comment by paregorios** [comment]
@cguardia production was running a modified code branch ("coverage") other than "master", so that is probably why you were not seeing the error locally. I have just merged "coverage" into "master", so if you update your local copy from isawnyu/pleiades-frontpage:master, I suspect you will start seeing the error locally. Sorry for the churn.

**Comment by cguardia** [comment]
Pushed a fix for this to master.

**Comment by paregorios** [comment]
This looks good on pleiades.jazkarta.com. Since it's merged to master, I think this one can be closed as resolved.
