### ISSUE TITLE
apply plone 4.3 minor version upgrades

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#439]
Let's get fully up-to-date if possible.

**Comment by alecpm** [comment]
https://pleiades.jazkarta.com is now running Plone 4.3.19. The upgrade was pretty painless when performed in the ZMI via `portal_setup/manage_upgrades`, but when performed in the Plone Control Panel it triggered a spurious full catalog reindex. Looking through the upgrade steps performed, none of them required a reindex. Best to run this via the ZMI when we do the final run.

It may make sense to perform this upgrade on current production before we clone the data, alternatively we will have to re-do this upgrade once the final data clone is completed.

**Comment by alecpm** [comment]
I think I see what triggered the reindex. There's an implicit upgrade of `plone.app.discussion` which made a change in the default comment workflow (does pleiades use comments?). That upgrade reindexes the permission settings for any `Discussion Item` content. The Plone migration tool tries to be clever and intercept any reindex attempts, skip them and set a flag. At the end of the migration path if it sees the flag set it reindexes the whole catalog, as an optimization to avoid multiple reindex operations in an extended migration. So a reindex that took about 5 seconds on its own was "optimized" by replacing it with  reindex operation that might have taken a day. Fun!

**Comment by alecpm** [comment]
pleiades.jazkarta.com is now on 4.3.20, the upgrade will need to be re-run after data migration using `portal_setup`.
