### ISSUE TITLE
instrument plone with new relic

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#44]
From [the Pleiades 3 proposal narrative](http://pleiades.stoa.org/files/pleiades-3-2015/proposal.pdf), pages 4-5:

> We will also gain the ability to equip the system with performance-monitoring capabilities provided by the New Relic application analytics platform by adding and configuring a plugin that is already widely used in the Plone community. The New Relic service will enable us to identify the most time-consuming operations remaining following the upgrade so that we can introduce targeted improvements to remedy them. Note: https://newrelic.com/. Plone plugin: https://github.com/collective/collective.newrelic.

**Comment by alecpm** [comment]
Unfortunately, it appears that there is not presently a Python 2.4 compatible release of the New Relic Python Agent, so we cannot instrument Plone 3.x.  This will have to be done post Plone 4 upgrade.  David has suggested we make an initial pass at using Products.signalstack (https://pypi.python.org/pypi/Products.signalstack/).  I may also try some of the old-school profiling tools (collective.profiler, Products.CallProfiler, ...)

**Comment by paregorios** [comment]
That seems reasonable to me, with the caveat that I don't think I want to spend time and money diagnosing and repairing problems that may disappear or that may be easier to spot after the upgrade to Plone 4.

**Comment by paregorios** [comment]
We can consider this done, right?

**Comment by davisagli** [comment]
Yes
