### ISSUE TITLE
Error on place page 445545537: Forum Iulium

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#440]
Navigating to a Pleiades [place](https://pleiades.stoa.org/places/445545537) produces the error below, although the associated [location resource](https://pleiades.stoa.org/places/445545537/osm-location-of-temple-of-venus-genetrix/?searchterm=genetrix*) functions properly.

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 112, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 95, Column 4
Expression: <PathExpr standard:u'context/@@where'>
Names:
{'container': <Place at /plone/places/445545537>,
'context': <Place at /plone/places/445545537>,
'default': <object object at 0x7f2516aaa7b0>,
'here': <Place at /plone/places/445545537>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f24a24d4170>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/445545537/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/445545537/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.geographer.views, line 9, in __call__
Module pleiades.geographer.geo, line 636, in coords
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 563, in reprPoint
Module pleiades.geographer.geo, line 404, in preciseGeoms
Module pleiades.geographer.geo, line 560, in <lambda>
AttributeError: value

Manage portlets

**Comment by paregorios** [comment]
I'm not seeing this error as of 8:30 EST 12/4/20. @cguardia has it been addressed?

**Comment by paregorios** [comment]
Update: I am seeing this error, but only when authenticated. Anonymous visits don't trigger it, which makes me suspicious that it involves a piece of content that's in draft or pending.

**Comment by paregorios** [comment]
I've looked at folder_contents and don't see any obvious troublemakers. There's no recent new content here that I can see. Another edge case in the new reprPoint algorithm?

**Comment by paregorios** [comment]
Error is in the recently modified code: https://github.com/isawnyu/pleiades-geographer/commit/49f2174431841dbe1902a4d400b122a4766b2772

I wonder if we have another edge case here with some kind of unexpected value condition. If so, we should not only delete the offending content item after identifying it, but also script a check of the entire dataset for similar problems like we did for the weird "list" values problem last week.

**Comment by cguardia** [comment]
It's the lambda expression that we were going to change anyway. Looks like my old nemesis getAccuracy is returning None. Pushed the fix to master. but not deployed or tagged.

**Comment by alecpm** [comment]
Deploying the change now.

**Comment by alecpm** [comment]
The error seems to be gone now.
