### ISSUE TITLE
Weird bug on new place with connections

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#441]
A place for [Regio I, Pompeii](https://pleiades.stoa.org/places/222138654) was created yesterday and there is now some weird behavior - there is some iteration of the place at this [url](https://pleiades.stoa.org/places/copy2_of_222138654) and it generates this area. I can't see an active working copy that is checked out so not certain where the copy is coming from.

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 112, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 95, Column 4
Expression: <PathExpr standard:u'context/@@where'>
Names:
{'container': <Place at /plone/places/copy2_of_222138654>,
'context': <Place at /plone/places/copy2_of_222138654>,
'default': <object object at 0x7f7366b2b7e0>,
'here': <Place at /plone/places/copy2_of_222138654>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f72e4acbc50>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/copy2_of_222138654/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/copy2_of_222138654/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.geographer.views, line 9, in __call__
Module pleiades.geographer.geo, line 636, in coords
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 615, in reprPoint
Module pleiades.geographer.geo, line 424, in __init__
Module Products.PleiadesEntity.content.Named, line 155, in getConnectedPlaces
AttributeError: 'NoneType' object has no attribute 'UID'

**Comment by paregorios** [comment]
I think this is fixed, but I don't know how it happened in the first place. I examined the catalog through the Zope Management Interface and found entries for ```/plone/places/copy2_of_222138654``` (with contents matching the baseline copy) and an apparently identical set at ```/plone/places/copy_of_222138654``` (ditto). I deleted all of these content items from the catalog and now everything seems to be ok. 

I'm not nervous.
