### ISSUE TITLE
Working copy produces error

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#442]
My attempt to check-in this [working copy](https://pleiades.stoa.org/places/copy_of_894019/@@content-checkin?_authenticator=7d6c62964820c77881d67d0189b176d0b41cbf15) results in this error:

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.app.iterate.browser.checkin, line 59, in __call__
Module Products.Five.browser.pagetemplatefile, line 125, in __call__
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 112, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: /srv/python27-apps/pleiades4/src/pleiades.notredame/pleiades/notredame/browser/template_overrides/plone.app.iterate.browser.checkin.pt
Line 31, Column 14
Expression: <PythonExpr (credit_info and credit_info.history_comments('publish'))>
Names:
{'args': (),
'container': <Place at /plone/places/copy_of_894019>,
'context': <Place at /plone/places/copy_of_894019>,
'default': <object object at 0x7fc986e6b7e0>,
'here': <Place at /plone/places/copy_of_894019>,
'loop': {},
'nothing': None,
'options': {},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fc92daa6dd0>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/copy_of_894019/@@content-checkin>,
'root': <Application at >,
'template': <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7fc9390525d0>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>,
'view': <Products.Five.metaclass.SimpleViewClass from /srv/python27-apps/pleiades4/eggs/plone.app.iterate-2.1.18-py2.7.egg/plone/app/iterate/browser/checkin.pt object at 0x7fc968caf550>,
'views': <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7fc97e957690>}
Module zope.tales.pythonexpr, line 59, in __call__
__traceback_info__: (credit_info and credit_info.history_comments('publish'))
Module <string>, line 1, in <module>
Module Products.PleiadesEntity.browser.credits, line 231, in history_comments
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 102: ordinal not in range(128)

**Comment by paregorios** [comment]
The traceback is thrown [at the point in the code](https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/browser/credits.py#L231) where all previous history comments are concatenated in order to pre-populate the checkin comment box. Given the error -- and the fact that one of the prior history comments on this place contains a non-ascii character -- seems to imply that some of the comment strings are unicode or utf8 and some others are ascii.

**Comment by paregorios** [comment]
The working copy is now checked in. I still need to incorporate revised code into the main branch on PleiadesEntity so this doesn't happen again somewhere else in future.
