### ISSUE TITLE
error on working copy of Sublanuvio

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#451]
I discovered an unintentional instance of place duplication (this [place](https://pleiades.stoa.org/places/40617124) duplicates this [place](https://pleiades.stoa.org/places/423077)). In attempting to check out a working copy and combine resources, I stumbled into some kind of error.
We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 87, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Warning: Macro expansion failed
Warning: <type 'exceptions.KeyError'>: 'macro'
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
Module newrelic.api.function_trace, line 112, in literal_wrapper
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
Module zope.tales.tales, line 696, in evaluate
URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
Line 89, Column 4
Expression: <PathExpr standard:u'context/@@where'>
Names:
{'container': <Place at /plone/places/copy_of_423077>,
'context': <Place at /plone/places/copy_of_423077>,
'default': <object object at 0x7fadf291e7e0>,
'here': <Place at /plone/places/copy_of_423077>,
'loop': {},
'nothing': None,
'options': {'args': ()},
'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7fad5a878050>,
'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/copy_of_423077/base_view>,
'root': <Application at >,
'template': <FSPageTemplate at /plone/places/copy_of_423077/base_view>,
'traverse_subpath': [],
'user': <PloneUser 'jbecker'>}
Module zope.tales.expressions, line 217, in __call__
Module Products.PageTemplates.Expressions, line 155, in _eval
Module Products.PageTemplates.Expressions, line 117, in render
Module pleiades.geographer.views, line 9, in __call__
Module pleiades.geographer.geo, line 630, in coords
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 593, in reprPoint
Module pleiades.geographer.geo, line 547, in centroid_by_connection_type
Module pleiades.geographer.geo, line 547, in <lambda>
Module pleiades.geographer.geo, line 505, in precision
Module plone.memoize.instance, line 51, in memogetter
Module pleiades.geographer.geo, line 476, in reprExtent
Module pleiades.geographer.geo, line 424, in __init__
Module Products.PleiadesEntity.content.Named, line 155, in getConnectedPlaces
AttributeError: 'NoneType' object has no attribute 'UID'

**Comment by paregorios** [comment]
This looks like a bad connection somewhere. I will investigate.

**Comment by paregorios** [comment]
There are two connections inside the working copy (https://pleiades.stoa.org/places/copy_of_423077/folder_contents) that do not have connected places. That's causing an error to be thrown on various resources that try to calculate coordinates based on these connections. I'm looking at options for the least destructive fix.

**Comment by paregorios** [comment]
This is fixed for this particular content item.

Here's what I think happened: two "connections" from the retracted duplicate place were copy+pasted into the working copy. Unfortunately, connections do not retain the target place ID when copy+pasted. So, these connections were unmoored from their targets. The `getConnectedPlaces` function in `PleiadesEntity.content.Named` doesn't protect itself from connections that are malformed in this way, hence the error.

We should keep this ticket open until we can create a new ticket for adding a trap for this particular error.
