### ISSUE TITLE
add "Create" and "Publish externally" events to history in JSON dumps: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#463]
State transitions are not currently included in object histories written to JSON by [the pleiades-json package](https://github.com/isawnyu/pleiades-json/blob/master/pleiades/json/browser.py). It would be useful, especially for generating accurate and complete [human-readable monthly changelogs](https://atlantides.org/changelogs/), if object "Creation" and "Publish externally" events were included in the JSON history or otherwise represented in the JSON.

**Comment by paregorios** [comment]
The JSON already provides, outside the "history" list, a "creation" key with a datetime, and that's sufficient for object creation. But the "publish" workflow transition is completely missing; it should be added to the "history" for each object, so that it looks like this:

```json
{
    ⋮
    "history": [
        {
            "comment": "Published",
            "modifiedBy": "thomase",
            "modified": "2009-11-02T18:37:30Z"
        },
        ⋮
]
```

**Comment by paregorios** [comment]
The value for "modifiedBy" of course should be the userid of whoever the actor was that published the item.

**Comment by jessesnyder** [comment]
@paregorios I think I've patched something together. Here's an example of a resulting history list for a single `Place`:

```json
{
    "history":
    [
        {
            "action": "Publish externally",
            "modified": "2016-11-08T21:58:28Z",
            "modifiedBy": "thomase"
        },
        {
            "action": "Submit for review",
            "modified": "2016-11-04T23:35:51Z",
            "modifiedBy": "jbecker"
        },
        {
            "comment": "added reference",
            "modified": "2016-11-04T23:35:45Z",
            "modifiedBy": "jbecker"
        },
        {
            "comment": "Migrated from location",
            "modified": "2016-11-04T16:36:16Z",
            "modifiedBy": "thomase"
        },
        {
            "action": "Create",
            "modified": "2016-11-04T16:36:09Z",
            "modifiedBy": "thomase"
        }
    ]
}
```

Look right (and is the order [most recent first] as desired?)

**Comment by jessesnyder** [comment]
Made some more refinements so events that happen in the same second are sorted properly. Here's a sample of the first 100 Places:

[pleiades-places.json.zip](https://github.com/isawnyu/pleiades-gazetteer/files/9966156/pleiades-places.json.zip)

**Comment by paregorios** [comment]
@jessesnyder this looks great to me. I'm ready to see it merged to master and deployed to production.

**Comment by paregorios** [comment]
@jessesnyder @alecpm is there a problem that is holding up deployment of this functionality to production?

**Comment by paregorios** [comment]
This seems to be running perfectly on production now.
