### ISSUE TITLE
add subheadings to Locations list on place view: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#464]
As a Pleiades user viewing a place page with a web browser, I would like to see subheadings, based on `location type` in the "Locations" section of the place page.

As `location type` is a multi-valued field, the logic in the following deceptively pythonesque pseudocode should be applied in creating the labels and grouping the portions of the list (actual implementation should of course vary, but this reflects the logic of label selection and formatting I'd like to see).

```python
labeled = {
    "associated_modern": set(),
    "relocated_modern": set(),
    "central_point": set(),
    "legacy": set(),
    "representative": set(),
}

for location in place.locations:
    loc_types = set(location.location_types)
    if "associated_modern" in loc_types:
        labeled["associated_modern"].add(location)
    elif "relocated_modern" in loc_types:
        labeled["relocated_modern"].add(location)
    elif "central_point" in loc_types:
        labeled["central_point"].add(location)
    elif "legacy" in loc_types:
        labeled["legacy"].add(location)
    else:
        labeled["representative"].add(location)

previous_loc_type = ""
for loc_type in ["representative", "central_point", "relocated_modern", "associated_modern", "legacy"]:
    if previous_loc_type != loc_type:
        if loc_type == "central_point":
            label = "Central Point:"
        else:
            label = f"{loc_type.replace('_', ' ').title} Locations:"
        write_label(label)
        previous_loc_type = loc_type
    for location in sorted(labeled[loc_type]):
        write_location_bullet(location)
```

**Comment by paregorios** [comment]
It turns out that "locationType" is a multivalued list, rather than a single value, so a group-by approach ([like we use for names](https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/browser/attestations.py#L290)) won't work.

**Comment by paregorios** [comment]
As a Pleiades user viewing a place page with a web browser, I would like to see subheadings, based on `location type` in the "Locations" section of the place page.

As `location type` is a multi-valued field, the logic in the following deceptively pythonesque pseudocode should be applied in creating the labels and grouping the portions of the list (actual implementation should of course vary, but this reflects the logic of label selection and formatting I'd like to see).

```python
labeled = {
    "associated_modern": set(),
    "relocated_modern": set(),
    "central_point": set(),
    "legacy": set(),
    "representative": set(),
}

for location in place.locations:
    loc_types = set([t for t in location.location_types if t])
    if "associated_modern" in loc_types:
        labeled["associated_modern"].add(location)
    elif "relocated_modern" in loc_types:
        labeled["relocated_modern"].add(location)
    elif "central_point" in loc_types:
        labeled["central_point"].add(location)
    elif "legacy" in loc_types:
        labeled["legacy"].add(location)
    else:
        labeled["representative"].add(location)

previous_loc_type = ""
for loc_type in ["representative", "central_point", "relocated_modern", "associated_modern", "legacy"]:
    if previous_loc_type != loc_type:
        if loc_type == "central_point":
            label = "Central Point:"
        else:
            label = f"{loc_type.replace('_', ' ').title} Locations:"
        write_label(label)
        previous_loc_type = loc_type
    for location in sorted(labeled[loc_type]):
        write_location_bullet(location)
```

**Comment by paregorios** [comment]
Examples:

## [Tell Ras Budran](https://pleiades.stoa.org/places/555858016)

### Locations:
 - **Representative Locations:**
   - [OSM location of Tell Ras Budran](https://pleiades.stoa.org/places/555858016/osm-location-of-tell-ras-budran) (3000 BC - 2000 BC)

## [Nērebtum](https://pleiades.stoa.org/places/357565832)

### Locations:
- **Central Point:**
  - [Imagery location of Išẖālī](https://pleiades.stoa.org/places/357565832/imagery-location-of-tall-sakhali) (2335 BC - 1600 BC)
- **Representative Locations:**
  - [OSM location of Tall Šajālī](https://pleiades.stoa.org/places/357565832/osm-location-of-tall-sahali) (2335 BC - 1600 BC)

## [Attaleia](https://pleiades.stoa.org/places/550472)

### Locations:
- **Associated Modern Locations:**
  - [OSM Location of modern settlement of Selcikli](https://pleiades.stoa.org/places/550472/osm-location-of-selcikli) (AD 1800 - AD 2099)

##  [Ophryneion](https://pleiades.stoa.org/places/550787)

### Locations:
- **Associated Modern Locations:**
  - [OSM location of modern Erenköy](https://pleiades.stoa.org/places/550787/osm-location-of-modern-erenkapy) (modern)
- **Representative Locations:**
  - [DARMC location 14023](https://pleiades.stoa.org/places/550787/darmc-location-14023) (330 BC - AD 300)

## [Tabula Traiana](https://pleiades.stoa.org/places/207484)

### Locations:
- **Relocated Modern Locations:**
  - [OSM location of Tabula Traiana](https://pleiades.stoa.org/places/207484/osm-location-of-tabula-traiana) (modern) 

## [London Mithraeum](https://pleiades.stoa.org/places/17649950)

### Locations:
- **Relocated Modern Locations:**
  - [OSM location of reassembled remains of Temple of Mithras](https://pleiades.stoa.org/places/17649950/osm-location-of-temple-of-mithras) (30 BC - AD 300)
- **Representative Locations:**
  - [Centerpoint of the ancient site](https://pleiades.stoa.org/places/17649950/centerpoint-of-the-ancient-site) (30 BC - AD 300)

**Comment by silviot** [comment]
@paregorios Deployed to staging for testing

**Comment by paregorios** [comment]
Logic for the various subheadings seems to be working as desired on staging. Labels for those subheadings do not yet exactly match the text in [the examples above](https://github.com/isawnyu/pleiades-gazetteer/issues/464#issuecomment-1075513246). I note also [the suggestions made by @alecpm on the related PR](https://github.com/isawnyu/PleiadesEntity/pull/52#pullrequestreview-921900765); I think these should be addressed and their results double-checked on staging before we move further toward deployment.

**Comment by silviot** [comment]
@paregorios I fixed the problems pointed out by @alecpm and added `:` and `Location` that were missing from the subheading. Am I still missing something?

**Comment by paregorios** [comment]
@silviot that's everything, thanks! This is now working perfectly on staging. Please move forward by merging for deployment.

**Comment by paregorios** [comment]
This is working perfectly on production.
