### ISSUE TITLE
show complex geometries on place and location maps instead of convex hulls: 5pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#466]
Currently, the maps shown on place and location pages display convex hulls around polyline and polygon geometries in locations, rather than the complete geometries themselves. These convex hulls are provided by code running in the plone when the javascript asks for the location geometries; they are not constructed by the map javascript itself. 

As a viewer of a map on a pleiades place or location page, I would like to see the complex geometry, not the convex hull. 

Note: I believe this behavior was introduced in order to avoid overwhelming browser clients with complex draw tasks for complex geometries (e.g., river systems imported from OSM). I doubt that this is any longer a concern with modern browsers and the javascript map frameworks we are using.

**Comment by jessesnyder** [comment]
@paregorios Sorry for only asking this now: do you have an example Place where this is evident?

**Comment by paregorios** [comment]
Example:

Consider the Meander river: https://pleiades.stoa.org/places/599777

The map shows a big, honkin' polygon:
![Screen Shot 2022-04-25 at 4 39 09 PM](https://user-images.githubusercontent.com/263285/165179533-8ad32cea-337d-4f01-a3c8-918d3d8fcefa.png)

But lurking inside the subordinate location [OSM Location of the modern Maeander river basin](https://pleiades.stoa.org/places/599777/osm-location-of-the-modern-maeander-river-basin) is a beautiful, complex `MultiLineString`

**Comment by jessesnyder** [comment]
Looks like I'm now butting up against #481:
![Maeander__river___a_Pleiades_place_resource](https://user-images.githubusercontent.com/63560/165194067-a88e810e-3a56-46bb-bb85-d40e863d2e4c.png)

**Comment by alecpm** [comment]
Yup.

**Comment by alecpm** [comment]
@jessesnyder If you want to try my fix see isawnyu/PleiadesEntity#53

**Comment by paregorios** [comment]
Various examples of LineStrings and MultiLineStrings: https://github.com/isawnyu/pleiades-gazetteer/issues/481#issuecomment-1109823682

**Comment by alecpm** [comment]
I've merged @jessesnyder's branch to staging for testing.

**Comment by alecpm** [comment]
It's looking good here:

http://pleiades.jazkarta.com/places/599777
http://pleiades.jazkarta.com/places/599777/osm-location-of-the-modern-maeander-river-basin

**Comment by alecpm** [comment]
Looks like the location map may still be treating these as some kind of polygon when rendering them. Probably some style tweak is needed in `location_map.js`.

**Comment by paregorios** [comment]
@alecpm that didn't seem to be the case for the Maeander example [you posted above](https://github.com/isawnyu/pleiades-gazetteer/issues/466#issuecomment-1111542185). Or am I confused?

**Comment by alecpm** [comment]
@paregorios you can see it if you zoom in close on the map at the location link. There are some light blue triangular areas linking various points for some reason.

**Comment by paregorios** [comment]
Ah, yes: 
![Screen Shot 2022-04-27 at 5 46 06 PM](https://user-images.githubusercontent.com/263285/165643593-a8d5c9a3-04c6-4b4f-887d-51bcd0675292.png)

**Comment by paregorios** [comment]
@jessesnyder I'm moving this into "needs work" in the project so we can try to address the polygon-like behaviors of some of these. OK?

**Comment by alecpm** [comment]
@jessesnyder I think this is just a matter of changing this [`style`](https://github.com/isawnyu/PleiadesEntity/blob/770bccd139b74d945263865aa4ab419ed1d17ab0/Products/PleiadesEntity/skins/PleiadesEntity/location_map.js#L157) function to return different Leaflet styles for different feature types (e.g. omit `fill...` properties for `LineString` and `MultiLineString`).

**Comment by jessesnyder** [comment]
I've made this change and it works locally. I've merged again to the staging branch, but am unable to ssh into the server. Maybe my IP changed? I'm currently at 216.160.64.51

**Comment by alecpm** [comment]
@paregorios @jessesnyder Looking good after updating and shift-reloading.

**Comment by paregorios** [comment]
Beauty!

**Comment by paregorios** [comment]
All my examples now look good on staging.

**Comment by paregorios** [comment]
@jessesnyder @alecpm if you guys think this is ready, I do ... let's merge and deploy to production
