### ISSUE TITLE
optionally draw accuracy buffers around locations on place and location maps: 8pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#467]
As a user (authenticated or anonymous) viewing a place page in my browser, I will see a new option on the map on the page to toggle display of an "accuracy buffer" around all location geometries shown in the map. When active, this option causes [a convex hull](https://shapely.readthedocs.io/en/stable/manual.html#object.convex_hull) to be drawn around each location geometry at a notional distance equivalent to the the value of the "accuracy" field in the "Positional Accuracy Assessment" associated with each location.

Note: this change applies ONLY to maps on place pages, not locations, search, or anywhere else.

Preferred Details:
- For points, buffer(s) should be circular
- The stroke color for buffer(s) should be a bright yellow
- The fill color for buffer(s) should be yellow as well, with opacity similar to that used for the blue fill in location geometry polygons.
- All buffer(s) should be stacked UNDER all other markers on the map (locations, connections) so that all location and connection symbols/polygons/polylines can be seen clearly
- When buffer(s) are toggled ON by the user, if the map zoom and pan are such that the full extent of the buffer(s) are not shown, then pan/zoom/recenter automatically so that they are.
- When buffer(s) are toggled OFF by the user, retain the existing map zoom/pan/extent (i.e. make no change)

**Comment by paregorios** [comment]
# Examples:

## Gasr-Silu ([P375237](https://pleiades.stoa.org/places/375237))

A single location, with +/- 2000m horizontal accuracy.

![gasr_silu_2_buffered](https://user-images.githubusercontent.com/263285/223263209-6aed2ec4-9f26-48d7-9d46-935eb52cae13.png)

## Kellis

Two locations. The polygon has a +/- 20m horizontal accuracy. The point has a +/- 5m accuracy.

![kellis_buffered](https://user-images.githubusercontent.com/263285/223260023-db168481-0fb9-48aa-829e-e9d579d690bf.png)

**Comment by alecpm** [comment]
@paregorios Would it be acceptable to add a new JS dependency for this? I don't see a particularly efficient or effective way of generating these buffer geometries using Shapely on the server and providing them to the browser map. However, there's a JS library [Turf.js](https://turfjs.org) which seems to provide [exactly](https://turfjs.org/docs/#buffer) the [functionality](https://turfjs.org/docs/#convex) you're looking for, and should be able to generate these buffers in the browser on demand.

**Comment by paregorios** [comment]
@alecpm implementing this functionality in the browser with Javascript is fine.

**Comment by alecpm** [comment]
@paregorios Would it be possible for you to share a link or two to places with interesting geometries for me to test this locally?

**Comment by paregorios** [comment]
How about these?

- three locations, each a complex polygon: [Dionysiades islands](https://pleiades.stoa.org/places/589763)
- two locations (a point and a polygon): [Pausilipum](https://pleiades.stoa.org/places/442113997)
- one location (a single polygon): [Tartas-1](https://pleiades.stoa.org/places/214401079)
- three locations, each a linestring: [Nemea (river)](https://pleiades.stoa.org/places/570505/)
- one location (a gnarly, multipart polygon): [Agora of Athens](https://pleiades.stoa.org/places/807514119)
- no locations, but lots of connections: [Athenae](https://pleiades.stoa.org/places/579885)

**Comment by alecpm** [comment]
Those look great. Re: Athenae Do we also want to draw buffers around the connection locations or just the current place locations?

**Comment by paregorios** [comment]
If there are no locations, let's disable drawing any buffers.

**Comment by alecpm** [comment]
@paregorios In such cases do we keep the checkbox and disable it or not render the checkbox?

**Comment by paregorios** [comment]
Let's keep the checkbox and disable it.

**Comment by alecpm** [comment]
@paregorios the turf.js `buffer` function makes buffers for polygons that look like this:

<img width="475" alt="Screenshot 2024-02-19 at 2 31 18 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/202854/93f39b65-01b7-4a0a-adbd-cb5f767f7f02">

Which seems like a good representation of a +/- accuracy, but is different from the solid polygon described in the ticket. Wrapping the `buffer` in a `convex` call gives something more similar to the description, if that's preferable:

<img width="475" alt="Screenshot 2024-02-19 at 2 35 56 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/202854/223d6f2f-58ec-4bce-b381-1a23dcb2ba0c">

**Comment by alecpm** [comment]
@paregorios FWIW, there's a pretty big difference in how the buffer with convex hull treats `LineString` features:

<img width="475" alt="Screenshot 2024-02-19 at 2 57 27 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/202854/dee1b397-5a17-4bbc-9ebc-9c1339dc5dd8">

vs. buffer without a convex hull:

<img width="475" alt="Screenshot 2024-02-19 at 2 59 41 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/202854/2761a7fe-27f8-4713-887d-16d3fdc89509">

**Comment by alecpm** [comment]
@paregorios one concern about the auto-zoom out feature described above. If I've zoomed it to a particular location, say one polygon out of many, and then enable the buffer visibility, this behavior would zoom out to show all locations with their buffers, potentially making the buffers too small to see relative to the distances between locations. I think I'd expect the checkbox to leave me zoomed in where I am and show the accuracy buffer for the specific location on which I'm zoomed.

**Comment by alecpm** [comment]
@paregorios I've got this up on the staging server for review (minus the zooming behavior, though the default zoom now incorporates the invisible accuracy buffers). Most of the sample locations you gave are not quite as interesting on staging as on production, but it seems to be working as expected. [Pausilipum](https://pleiades.jazkarta.com/places/442113997) is probably the most interesting of them. Let me know if you want a different UI than that checkbox, and if the popup language on the buffers is acceptable. I think we could probably use a better indicator of the disabled checkbox state when there are no locations, but I'm not sure what that is.

**Comment by jessesnyder** [comment]
> I think we could probably use a better indicator of the disabled checkbox state when there are no locations, but I'm not sure what that is

@paregorios I second this concern. I thought maybe there was some transparent HTML element with a higher z-index than the checkbox that was preventing me from clicking it, and only figured out what was going on by looking at the browser dev tools.

**Comment by paregorios** [comment]
@alecpm regarding what seem to be the open questions:

- when there are no locations: how hard would it be to completely omit the checkbox and its label, perhaps supplying alternate text like: "no locations are assigned to this place"?
- I agree we should not implement the zoom out feature. This is intuitive as it is.
- I think I like convex hull + buffer, even with what it does to linestrings. Linestrings are often rivers for us, and these often have different modern courses than their ancient ancestors, so I'm ok with the additional, sometimes huge, footprint.

Did I miss anything?

**Comment by alecpm** [comment]
@paregorios That's everything. I'll hide the checkbox and change the label when there are no locations with accuracy info, and then I think everything should be set.

**Comment by paregorios** [comment]
@alecpm it looks like you've updated staging with the checkbox suppression, but not the label change, is that correct? I'm looking at https://pleiades.stoa.org/places/579885

**Comment by paregorios** [comment]
I'm running amok accidentally deleting comments in here sorry. I think the status is that @alecpm is planning to suppress the checkbox and provide alternative label and then we'll be ready for final review on staging. Sorry about the update noise.

**Comment by alecpm** [comment]
@paregorios The label change is up on staging for review.

**Comment by paregorios** [comment]
@alecpm this looks great on staging. Once any pending code reviews are done, I would be happy to see this merged and deployed to production.

**Comment by alecpm** [comment]
@paregorios This is live on production and seems to be working well on the example places I've tested.

**Comment by paregorios** [comment]
This is working great on production. Thanks!
