### ISSUE TITLE
stop overwriting non-empty "access URI" field on Zotero import: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#468]
When importing data from Zotero into a "reference", the "access URI" field gets overwritten if there is content in the Zotero "url" field. That Zotero.url is normally the landing/title page of online resources that may have many subordinate pages. It is a manual task for the user who is creating the reference to paste in the specific access URI.  Many users' process involves filling in the "citation detail" field and the "access URI" field before performing the Zotero import. The result: the access URI gets overwritten by the import and the user does not notice. It would be better for us to check the "access URI" field at import time and, if it is other than empty, to skip over-writing with the Zotero.url.

Pseudocode:
```
on import from Zotero:
    if Zotero.url is non-empty and PleiadesReference.accessURI is empty:
        PleiadesReference.accessURI = Zotero.url
    otherwise:
        pass

**Comment by paregorios** [comment]
## Steps to reproduce the undesireable behavior:

1. Login to Pleiades.
2. Navigate to https://pleiades.stoa.org/places
3. Select "Add new ..." > "Place" from the grey, tertiary menu bar.
4. In the "Add Place" form, enter a Title like "Foo".
5. Select the "References" tab.
6. Select the "Add Reference" button.
7. In the "Citation Detail" textbox, enter "Strab. 6.2.2"
8. In the "Access URI" textbox, enter "http://data.perseus.org/citations/urn:cts:greekLit:tlg0099.tlg001.perseus-grc1:6.2.2".
9. At the bottom of the page, select the "Save" button.
10. After saving, in the page view, select the link "Strab. 6.2.2" under "References" > "See Further" and verify that it redirects and resolves to https://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0099.tlg001.perseus-grc1:6.2.2
11. Return to the "Foo" place page and select "Edit" from the secondary menu bar.
12. Select the "References" tab.
13. In the previously created reference's "Bibliographic URI" enter "https://www.zotero.org/groups/2533/items/FEVTVBA7".
14. Select the "Fetch Zotero" button.
15. Note that the following previously empty fields have been populated: "Short Title", "Formatted Citation".
16. Note also that the value you previously entered (step 8) in the "Access URI" box has been overwritten with "http://data.perseus.org/texts/urn:cts:greekLit:tlg0099.tlg001.perseus-grc1".
17. Scroll to the bottom of the page and select the "Save" button.
18. After saving, in the page view, select the link that now reads "Str. (Meineke: Perseus) Strab. 6.2.2" under "References" > "See Further". Note that it no longer resolves to the page indicated in step 10, above. Instead, it resolves to the first page of Strabo (i.e., Strab. 1.1.1), which has a different URL: https://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0099.tlg001.perseus-grc1

## What we want to have happen instead (steps 1-15 remain exactly as above):

16. Note that the value you previously entered (step 8) in the "Access URI" box **HAS NOT BEEN CHANGED**.
17. Scroll to the bottom of the page and select the "Save" button.
18. After saving, in the page view, select the link that now reads "Str. (Meineke: Perseus) Strab. 6.2.2" under "References" > "See Further" and see that it **DOES STILL RESOLVE** to the same URI you entered in step 10, above, i.e., https://www.perseus.tufts.edu/hopper/text?doc=urn:cts:greekLit:tlg0099.tlg001.perseus-grc1:6.2.2

**Comment by silviot** [comment]
@paregorios The fix is deployed to staging.

**Comment by paregorios** [comment]
This is working perfectly on staging. Please deploy to production.

**Comment by paregorios** [comment]
This is working perfectly on production.
