### ISSUE TITLE
unreliable reprPoint (centroid) recalculation: 5pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#469]
Given a place resource with a single, published location, upon retraction to drafting of the location, [one would expect recalculation of the "representative point" (centroid) on the basis of any connections](https://github.com/isawnyu/pleiades-geographer/blob/62d2772b9d34cec48881bffb630c4f1f34145643/pleiades/geographer/geo.py#L562). In the experience of editors, this does not happen reliably. The previous centroid lingers in the place view and the associated map (even on forced browser refresh) until an admin (1) uses the ZMI to update the portal_catalog for the place and all its contents and (2) restarts varnish and then the user refreshes the browser.

Editor users have the impression that this undesireable "stale reprPoint" behavior sometimes also occurs when publishing or retracting a connection child or when making changes to connected places that ought to alter the representative point.

This behavior may be intermittent as it has been hard to pin down and describe.

Desired behavior: reprPoint is recalculated for a place whenever:

1.  any of its currently-published location or connection children is altered live, or
2. any location or connection child leaves/enters "published" workflow state, or
3. any inbound-connection is altered live or leaves/enters "published" workflow state, or
4. the representative point of any place connected to this place experiences an update in its representative point on the basis of the preceding 3 rules.
 
This recalculation should be reflected immediately upon next display of the place view in both the "prepresentative point" field and in the map.

**Comment by paregorios** [comment]
A current example, which of course may disappear on its own, is https://pleiades.stoa.org/places/585129/. The sole published location was retracted this morning, and connections added. We would expect to see a new reprPoint calculated solely on the basis of the connections -- and indeed one can see that this has happened for the SEARCH MAP ONLY (see second screen capture below) -- but the place page still retains the old behavior (below is a screen capture of an anonymous session). Note also the blue geometry for the location that has been retracted, which we should not be seeing at all as an anonymous visitor!

![Screen Shot 2022-03-08 at 11 05 16 AM](https://user-images.githubusercontent.com/263285/157288909-3db4e4ec-30c3-4b74-a029-da0d8a23f8ba.png)

But here's the map on the search page, showing the reprPoint where I would expect to find it after recalculation based on the connections only:

![Screen Shot 2022-03-08 at 11 08 53 AM](https://user-images.githubusercontent.com/263285/157289200-8604b76b-70ec-4023-b1d5-9ea49f5a0e80.png)

**Comment by alecpm** [comment]
I thought I was seeing this on staging even after the caching changes, but that was because the staging branch of pleiades.geographer didn't have the latest changes to the `reprPoint` calculations merged and was only using the centroid of the most certain location for the calculation instead of using the centroid of multiple locations. Once I merged those changes to staging it seems like the caching fixes have resolved this issue.

Updates to publication state of locations immediately update the representative point both on the page and on the map.

**Comment by paregorios** [comment]
This seems to be working well on staging.

**Comment by paregorios** [comment]
This is working perfectly on production. 

For future reference, the following behaviors are observed and appreciated:
- Adding locations in states other than published do not affect reprPoint calculations.
- Adding a new location to an existing, published place and publishing that new location causes an instant and correct update to the place's "representative point".
- Retracting a published location on an existing, published place causes an instant and correct update to the place's "representative point".
- Publishing a new place and its subordinate location(s) cause an instant and correct calculation and display of the reprPoint.
