### ISSUE TITLE
implement relationships beyond "connection"

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#47]
From [the Pleiades 3 proposal narrative](http://pleiades.stoa.org/files/pleiades-3-2015/proposal.pdf), pages 5:

> Having streamlined, upgraded, and optimized Plone and our other software components, we will be in a position to enhance the database, interfaces, and serializations by adding support for more nuanced place relationships than we currently handle and publishing a formal specification for them so that other projects can benefit. Note: Only simple relationships are currently supported (Gillies 2013). The planning document for new relationships: http://pleiades.stoa.org/docs/content-development-projects/relationships-beyond-simple-connections.

**Comment by davisagli** [comment]
We now have a full-blown Connection content type.
