### ISSUE TITLE
bump deployed version of pleiades-dumps: 1pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#470]
In order to pick up and deploy a modest modification to the README for the CSV dumps: https://github.com/isawnyu/pleiades-dump/commit/50d589cf4d5c0e1d2366275973493c1b6760cfa4

**Comment by paregorios** [comment]
@alecpm @jessesnyder post-deployment I expect to see this at https://atlantides.org/downloads/pleiades/dumps/README.txt but the new version is not there

**Comment by jessesnyder** [comment]
It's definitely merged:
https://github.com/isawnyu/pleiades3-buildout/commit/a42585ec7750646034ce75225fc3f67e7be44a3e

I'm not sure what's going on. Maybe deployment doesn't overwrite which commit is checked out for some reason? I'm going to have to punt this to @alecpm.

**Comment by paregorios** [comment]
@alecpm I'm still seeing the old version of the README.txt file at https://atlantides.org/downloads/pleiades/dumps/README.txt as of this morning

**Comment by alecpm** [comment]
@paregorios That url links to the file [here](https://github.com/isawnyu/pleiades-dump/blob/master/README.rst) rather than the updated one [here](https://github.com/isawnyu/pleiades-dump/blob/master/docs/README.txt). I can change the symbolic link at `/var/www/atlantides.org/downloads/pleiades/dumps/README.txt` or we can update the README at the root (or turn it into a symlink).

**Comment by paregorios** [comment]
@alecpm I would prefer that we change the symbolic link at /var/www/atlantides.org/downloads/pleiades/dumps/README.txt

so that, instead of 

```
README.txt -> /srv/python27-apps/pleiades4/src/pleiades.dump/README.rst
```

we have

```
README.txt -> /srv/python27-apps/pleiades4/src/pleiades.dump/docs/README.txt
```

Does ansible create this symbolic link or something else?

**Comment by alecpm** [comment]
@paregorios is there a reason to have two similar READMEs in the repo? Perhaps we could make the one at the root (useful for GitHub purposes) a symlink to the one in docs also?

**Comment by paregorios** [comment]
@alecpm see now https://github.com/isawnyu/pleiades-dump/pull/7

**Comment by alecpm** [comment]
Should be updated.

**Comment by paregorios** [comment]
Looks good!
