### ISSUE TITLE
foaf:primaryTopicOf should be foaf:isPrimaryTopicOf: 1pts

### ISSUE THREAD

**Issue by rybesh** [isawnyu/pleiades-gazetteer#471]
Pleiades uses `foaf:primaryTopicOf` to link features to place concepts, but the actual name of the predicate is [`foaf:isPrimaryTopicOf`](http://xmlns.com/foaf/spec/#term_isPrimaryTopicOf).

**Comment by paregorios** [comment]
code appears to be here: https://github.com/isawnyu/pleiades-rdf/blob/6d29a3d34b5615780d0810d78ef3b8eafea2f618/pleiades/rdf/common.py#L358

**Comment by alecpm** [comment]
The incorrect spelling also appears in page metadata [here](https://github.com/isawnyu/pleiades-notredame/blob/ddd9ada347a7d8d0d836cc32a17bb6089a0273df/pleiades/notredame/browser/templates/rich_meta.pt#L60) and [here](https://github.com/isawnyu/PleiadesEntity/blob/bd7c2ee2629657f2ce3ac8e1d52ef5af0e412cac/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt#L15).

**Comment by silviot** [comment]
@alecpm The two instances you linked are `foaf:PrimaryTopic`, not `primaryTopicOf`. I'll double check the specs.

**Comment by alecpm** [comment]
@silviot Oh right, I think that's OK then since `isPrimaryTopicOf` is the inverse reference for `PrimaryTopic`. Sorry.

**Comment by silviot** [comment]
The foaf specs about [primaryTopic](http://xmlns.com/foaf/spec/#term_primaryTopic) and [isPrimaryTopicOf](http://xmlns.com/foaf/spec/#term_isPrimaryTopicOf) specify they should be used like this:
```mermaid
graph LR
    A[Document] -- primaryTopic --> B[Thing]
    C[Thing] -- isPrimaryTopicOf --> D[Document]
```
I'm not familiar with `foaf` enough to fully understand what `Document`s and `Thing`s are, in particular if a `Document` is also a `Thing` or not. 
[Inspecting the source of a page](https://pleiades.stoa.org/places/314848) I can see that there are two `<link rel="foaf:primaryTopic">` elements, with different capitalizations, both pointing to the current page. Those might require fixing, but it sounds to me like it's out of the scope of this ticket.
@alecpm I just read your comment right before submitting this

**Comment by paregorios** [comment]
I agree that fiddling with the `primaryTopic` stuff in the page template is outside the scope of this ticket.

The HTML page identified by a URI like `https://pleiades.stoa.org/places/91371094` is a `Document` ("information resource"). We use URIs like `https://pleiades.stoa.org/places/91371094#this` to refer to the real-world `Thing` (place = "non-information resource") described by the corresponding `Document`. In order to avoid confusing human users, we resolve both in the browser and deliver the same content (this is a very old implementation decision).

**Comment by silviot** [comment]
@paregorios Makes sense. Thanks for clearing that out!

**Comment by silviot** [comment]
@paregorios The fix for this is now deployed to staging

**Comment by paregorios** [comment]
## Staging Error

RDF serializations (both XML and TTL) on staging are throwing tracebacks like this:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module pleiades.rdf.browser, line 47, in __call__
  Module pleiades.rdf.browser, line 24, in graph
  Module pleiades.rdf.common, line 397, in place
  Module pleiades.rdf.common, line 223, in dcterms
  Module pleiades.rdf.common, line 118, in user_info
  Module Products.PlonePAS.tools.memberdata, line 335, in getProperty
  Module Products.CMFCore.MemberDataTool, line 339, in getProperty
ValueError: The property viaf_link does not exist
```

## Steps to recreate:
1. Visit http://pleiades.jazkarta.com/places/462172
2. Under "Alternate representations", select [the link for "RDF+XML"](http://pleiades.jazkarta.com/places/462172/rdf)
3. Observe the traceback above.
4. Return to http://pleiades.jazkarta.com/places/462172
5. Under "Alternate representations", select [the link for "Turtle"](http://pleiades.jazkarta.com/places/462172/turtle)
6. Observe the same traceback.

## Compare:
- https://pleiades.stoa.org/places/462172
- https://pleiades.stoa.org/places/462172/rdf
- https://pleiades.stoa.org/places/462172/turtle

**Comment by silviot** [comment]
@paregorios I don't see the error in my local (`master` based) install nor I see anything in the traceback that hints at a connection with the work I did. I suspect we should reset the various `staging` branches to their respective `master`s before going on with testing on staging. @alecpm opinions?

**Comment by paregorios** [comment]
hmm yeah there must be some other branch's changes to `pleiades-rdf/pleiades/rdf/common.py` lurking on staging because line 118 from the traceback points to a seemingly innocuous "else" directive in old code both in [@silviot's branch](https://github.com/isawnyu/pleiades-rdf/blame/story/471-isPrimaryTopicOf/pleiades/rdf/common.py#L118) and [master](https://github.com/isawnyu/pleiades-rdf/blame/master/pleiades/rdf/common.py#L118). Or something even more fun is going on.

**Comment by alecpm** [comment]
I've merged all `master` changes from the various pacakges with `staging` branches into those `staging` branches. There was some funny business with a bad merge or something in `pleiades.rdf` staging, so I rebased it to bring it in line with master plus changes from @silviot and @jessesnyder. Now aside from the couple of outstanding changes from this iteration I'm not seeing any additional differences between the various master and staging branches.

The changeset that was in `pleiades.rdf` staging looked like this:

```
diff --git a/pleiades/rdf/common.py b/pleiades/rdf/common.py
index fd191af..56d413c 100644
--- a/pleiades/rdf/common.py
+++ b/pleiades/rdf/common.py
@@ -114,9 +114,13 @@ def user_info(context, username):
         return {
             "id": member.getId(),
             "fullname": member.getProperty('fullname'),
-            'url': "https://pleiades.stoa.org/author/" + member.getId()}
+            'url': "https://pleiades.stoa.org/author/" + member.getId(),
+            'viaf': member.getProperty('viaf_link'),
+            'orcid': member.getProperty('orcid_link'),
+        }
     else:
-        return {"id": None, "fullname": un, 'url': None}
+        return {"id": None, "fullname": un, "url": None, "viaf": None,
+                "orcid": None}
 
 def principals(context):
     creators =  getattr(context, 'Creators', [])
@@ -194,19 +198,26 @@ class PleiadesGrapher(object):
                     username, url = self.authority.get(principal)
                     if username and not url:
                         url = "https://pleiades.stoa.org/author/" + username
+
             if url:
-                old_url = url.replace('https://', 'http://')
                 pnode = URIRef(url)
-                opnode = URIRef(old_url)
             else:
                 pnode = BNode()
-                opnode = None
+
+            if url.startswith('https://pleiades.stoa.org'):
+                old_url = url.replace('https://', 'http://')
+                opnode = URIRef(old_url)
+
             g.add((subj, DCTERMS['creator'], pnode))
             if not url and p.get('fullname'):
                 g.add((pnode, RDF.type, FOAF['Person']))
                 g.add((pnode, FOAF['name'], Literal(p.get('fullname'))))
                 if opnode:
                     g.add((pnode, OWL['sameAs'], opnode))
+                if p.get('viaf'):
+                    g.add((pnode, OWL['sameAs'], URIRef(p.get('viaf'))))
+                if p.get('orcid'):
+                    g.add((pnode, OWL['sameAs'], URIRef(p.get('orcid'))))
 
         for principal in contributors:
             p = user_info(context, principal)
@@ -217,19 +228,28 @@ class PleiadesGrapher(object):
                     username, url = self.authority.get(principal)
                     if username and not url:
                         url = "https://pleiades.stoa.org/author/" + username
+
             if url:
-                old_url = url.replace('https://', 'http://')
                 pnode = URIRef(url)
-                opnode = URIRef(old_url)
             else:
                 pnode = BNode()
-                opnode = None
+
+            if url.startswith('https://pleiades.stoa.org'):
+                old_url = url.replace('https://', 'http://')
+                pnode = URIRef(url)
+                opnode = URIRef(old_url)
+
             g.add((subj, DCTERMS['contributor'], pnode))
             if not url and p.get('fullname'):
                 g.add((pnode, RDF.type, FOAF['Person']))
                 g.add((pnode, FOAF['name'], Literal(p.get('fullname'))))
                 if opnode:
                     g.add((pnode, OWL['sameAs'], opnode))
+                if p.get('viaf'):
+                    g.add((pnode, OWL['sameAs'], URIRef(p.get('viaf'))))
+                if p.get('orcid'):
+                    g.add((pnode, OWL['sameAs'], URIRef(p.get('orcid'))))
+
 
         return g
 
@@ -811,23 +831,28 @@ class PersonsGrapher(PleiadesGrapher):
                 subj = URIRef(info['url'])
                 g.add((subj, RDF.type, FOAF['Person']))
                 g.add((subj, FOAF['name'], Literal(fullname)))
-
-                if fullname in self.authority:
+                if info.get('viaf'):
+                    g.add((subj, OWL['sameAs'], URIRef(info.get('viaf'))))
+                elif fullname in self.authority:
                     username, uri = self.authority[fullname]
                     g.add((subj, OWL['sameAs'], URIRef(uri)))
+                if info.get('orcid'):
+                    g.add((subj, OWL['sameAs'], URIRef(info.get('orcid'))))
 
             # Non-user authors listed in the authority file.
             elif u in self.authority:
                 username, uri = self.authority[u]
+                old_uri = None
                 if username and not uri:
                     uri = "https://pleiades.stoa.org/author/" + username
+                    old_uri = uri.replace('https://', 'http://')
                 if not uri:
                     continue
                 subj = URIRef(uri)
                 g.add((subj, RDF.type, FOAF['Person']))
-                g.add((subj, FOAF['name'], Literal(label)))
-                old_uri = uri.replace('https://', 'http://')
-                g.add((URIRef(uri), OWL['sameAs'], URIRef(old_uri)))
+                g.add((subj, FOAF['name'], Literal(u)))
+                if old_uri and old_uri != uri:
+                    g.add((URIRef(uri), OWL['sameAs'], URIRef(old_uri)))
 
         return g
```

**Comment by alecpm** [comment]
That seems to have come from this commit by me in 2016:

https://github.com/isawnyu/pleiades-rdf/commit/5b65a2252d5b5dc7b51bf9dc2e93cc9c92719062

I'm not seeing any issues indicating what the intention of that commit was, but it was part of the following branches:

https://github.com/isawnyu/pleiades-rdf/compare/remove-ssl-sameas
https://github.com/isawnyu/pleiades-rdf/compare/profile-links

**Comment by paregorios** [comment]
I think that work pre-dated our use of github issue trackers. There are also evident modifications to profiles to provide the corresponding ORCID and VIAF fields running on staging now.

**Comment by paregorios** [comment]
@silviot this now looks ready to deploy

**Comment by paregorios** [comment]
This is working perfectly on production.
