### ISSUE TITLE
place maps autozoom fails on places with inbound connections 

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#480]
When the HTML page for a place with inbound connections renders in a browser, instead of zooming to a notional bounding box around the connected features, the map incorrectly zooms **out** to the maximum map extents. Examples:

- Rome: https://pleiades.stoa.org/places/423025
- Athens: https://pleiades.stoa.org/places/579885
- Asia Minor: https://pleiades.stoa.org/places/837
- Los Tocanos: https://pleiades.stoa.org/places/131166124

**Comment by alecpm** [comment]
I think this is fixed on staging (you may need to clear your cache to refresh the js).

**Comment by alecpm** [comment]
http://pleiades.jazkarta.com/places/423025

**Comment by paregorios** [comment]
@alecpm this is fixed gloriously on staging. Please merge and deploy to production.

**Comment by alecpm** [comment]
This is on production now, but Athens is still being a bit weird for presumably different reasons.

**Comment by paregorios** [comment]
It took Athens a few minutes and a few refreshes on staging before it got its act together.

**Comment by paregorios** [comment]
All is well on production.
