### ISSUE TITLE
Pleiades place maps do not display geometries other than polygons and points: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#481]
This is an omission in the JavaScript code for the maps: https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/skins/PleiadesEntity/place_map.js#L280

**Comment by paregorios** [comment]
Desired behavior:

Javascript for maps on the place view should display any and all geometry types found in our locations:

- [x] Point
- [x] LineString
- [x] Polygon
- [x] Multilinestring

Add support for LineString and MultilineString

**Comment by alecpm** [comment]
You'll probably need to clear your cache, but LineString geometries should render on staging now. They seem a bit subtle with the shade of blue it's currently using so color suggestions would be appreciated.

I believe MultiLineString geometries should also work, but currently they are converted into Polygon geometries on the server side (see #466).

**Comment by paregorios** [comment]
Some test linestrings:

- Single two-point linestring:
   - Pont du Gard: `/places/149496`
   - Aqueduct (Mérida): `/places/256708`
- Single multi-point linestring:
   - Atlas Montes ridgeline: `/places/846`
   - Portus Lemanis: `/places/79647`
- Multiple locations, each containing a linestring:
   - Roman Bridge at Albertville: `/places/169140`
   - Walls of Caerwent (Venta Silurum): `/places/122572946`
- MultiLineString:
   - Marta River: `/places/413193`
   - Tiber River: `/places/423080`

**Comment by paregorios** [comment]
Yes, I can see the linestrings on the maps! As to color, I see what you're saying about contrast. The challenge is we have color-coding trying to happen here: orange for "representative point", blue for "location geometry", and green for "connection representative point". If we switch to red, we would need to change that for all location geometries, not just the lines.

**Comment by alecpm** [comment]
@paregorios That makes sense, let me know if you'd like to play with a different color for the location geometries. Otherwise I think this is ready apart from needing better handling of MultiLineString geometries via #466.

**Comment by paregorios** [comment]
A quick color experiment ... also, I wonder if it's possible to increase the stroke width by a pixel. That might help alot.

![color_options](https://user-images.githubusercontent.com/263285/165348455-99bb5bad-3b27-4e86-8135-a349243b9d00.png)

**Comment by paregorios** [comment]
Let's leave color as it is for now, since changing the point symbols to match would require changes to our MapBox style definition. I'm happy for this to be deployed to production.

**Comment by alecpm** [comment]
This is live on production.

**Comment by paregorios** [comment]
I'm still seeing a polygon here: https://pleiades.stoa.org/places/846

**Comment by paregorios** [comment]
And this: https://pleiades.stoa.org//places/122572946

**Comment by alecpm** [comment]
@paregorios I think that's expected for everything except two point LineStrings until the fix for #466 is deployed.

**Comment by paregorios** [comment]
ah, ok

**Comment by alecpm** [comment]
See, e.g. http://pleiades.jazkarta.com/places/122572946 and http://pleiades.jazkarta.com/places/846

**Comment by paregorios** [comment]
Working as intended on production. See #466 for additional functionality around multilinestrings etc.
