### ISSUE TITLE
some OSM relation imports silently produce empty MultiLineString geometry: 5pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#482]
## Steps to reproduce:

- Login to Pleiades
- Navigate to the place entry for the [*Alisina (river)](https://pleiades.stoa.org/places/118555)
- Select the drop-down arrow on the "Add Location" button to open the "Add OpenStreetMap Location" pop-up
- In the "Add OpenStreetMap Location" popup:
   - Select the "relation" radio button 
   - Enter "2335018" in the "OSM Unique Identifier" text box
   - Enter "test relation" in the "Title" text box
   - Select the "Add" button
- Note that the "Add Location" form opens with some fields pre-populated as you would expect; however, 
   - Select the "Coordinates" tab
   - Note that the "Geometry and Coordinates" box contains the invalid, empty MultiLineString geometry `{"type": "MultiLineString", "coordinates": []}`
   - Select the "Save" button at the bottom of the "Add Location" form.
- From the "test relation" location view, navigate up one level to the containing place view by clicking in the breadcrumbs on the "[*Alisina (river)](https://pleiades.stoa.org/places/118555)" link.
- Note the following traceback because of the empty MultiLineString geometry in the new location:

```python
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module Shared.DC.Scripts.Bindings, line 322, in __call__
    Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
    Module Products.CMFCore.FSPageTemplate, line 237, in _exec
    Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
    Module Products.PageTemplates.PageTemplate, line 87, in pt_render
    Module zope.pagetemplate.pagetemplate, line 132, in pt_render
    Warning: Macro expansion failed
    Warning: <type 'exceptions.KeyError'>: 'macro'
    Module zope.pagetemplate.pagetemplate, line 240, in __call__
    Module collective.newrelic.patches.talinterpreter, line 17, in monkeypatch
    Module newrelic.api.function_trace, line 112, in literal_wrapper
    Module zope.tal.talinterpreter, line 271, in __call__
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 858, in do_defineMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 954, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 946, in do_defineSlot
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 858, in do_defineMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 533, in do_optTag_tal
    Module zope.tal.talinterpreter, line 518, in do_optTag
    Module zope.tal.talinterpreter, line 513, in no_tag
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 888, in do_useMacro
    Module zope.tal.talinterpreter, line 343, in interpret
    Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
    Module zope.tales.tales, line 696, in evaluate
    URL: file:/srv/python27-apps/pleiades4/src/Products.PleiadesEntity/Products/PleiadesEntity/skins/PleiadesEntity/place_view.pt
    Line 89, Column 4
    Expression: <PathExpr standard:u'context/@@where'>
    Names:

    {'container': <Place at /plone/places/118555>,
     'context': <Place at /plone/places/118555>,
     'default': <object object at 0xffff908c6820>,
     'here': <Place at /plone/places/118555>,
     'loop': {},
     'nothing': None,
     'options': {'args': ()},
     'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0xffff4fa8c6b0>,
     'request': <HTTPRequest, URL=https://pleiades.stoa.org/places/118555/base_view>,
     'root': <Application at >,
     'template': <FSPageTemplate at /plone/places/118555/base_view>,
     'traverse_subpath': [],
     'user': <PloneUser 'youruser'>}

    Module zope.tales.expressions, line 217, in __call__
    Module Products.PageTemplates.Expressions, line 155, in _eval
    Module Products.PageTemplates.Expressions, line 117, in render
    Module pleiades.geographer.views, line 9, in __call__
    Module pleiades.geographer.geo, line 636, in coords
    Module plone.memoize.instance, line 51, in memogetter
    Module pleiades.geographer.geo, line 565, in reprPoint
    Module pleiades.geographer.geo, line 541, in average_centroid_of_geometries
    Module pleiades.geographer.geo, line 541, in <genexpr>
    Module shapely.geometry.point, line 55, in x

IndexError: list index out of range  
```

## Preferred behavior

1. If a relation is successfully mapped on the OSM map, it should be successfully imported by Pleiades as a location (i.e., there should not be invalid geometry after the import). 
2. If -- despite our best efforts -- invalid geometry is created, we should test for it and raise an error, rather than leaving the user to notice it or later stumble over it because of the traceback on the parent place.

**Comment by paregorios** [comment]
This also is currently happening with another OSM relation: https://www.openstreetmap.org/relation/28737 . Many other OSM relations work fine.

**Comment by paregorios** [comment]
Another example: https://pleiades.stoa.org/places/118547/osm-location-of-the-modern-inn-river

**Comment by paregorios** [comment]
And another: https://pleiades.stoa.org/places/118583/osm-location-of-modern-naab-river

**Comment by paregorios** [comment]
@serviliusahala any location that's imported from an OSM Relation right now is suspect. Before submitting (or in these cases publishing or checking-in) please eyeball the "Geometry and Coordinates" field in the Location view. If you see `"coordinates": []` as in the image below, please don't proceed. In fact, send back to "drafting" and then put a link to the pleiades location in a comment on this issue. Thanks.

**Comment by paregorios** [comment]
Another one: https://pleiades.stoa.org/places/857166/karadere

**Comment by paregorios** [comment]
I note that MultiLineString is not a supported type in our place maps (see #481).

**Comment by paregorios** [comment]
If it's useful to be able to compare OSM relations that were successfully imported as MultiLinestrings to these failing ones, see the final entries in the list here: https://github.com/isawnyu/pleiades-gazetteer/issues/481#issuecomment-1109823682

**Comment by silviot** [comment]
The current code fails to extract meaningful information from this XML document: https://www.openstreetmap.org/api/0.6/relation/2335018/full

It's looking for a `<member type="way" role="main_stream">` but can't find one, hence the empty `MultiLineString`.
There's a condition in the code that adds the `role` requirement only for waterways:

```python
            if relation_type == 'waterway':
                way_xpath += "[@role='main_stream']"
```

Removing that condition would probably fix the problem, but I don't feel comfortable changing the code that way since I don't fully understand why the condition was there in the first place.

**Comment by paregorios** [comment]
Aha! @silviot rather than removing the condition entirely, could we give it a fallback? Pseudocode:

```
if relation_type == 'waterway':
    if there are `ways` with `@role='main_stream'`, use them
    elif there are `ways` that contain `<tag k="waterway" v="river"/>`, use them
    otherwise use all `ways`
```

Stuff I looked at other than the XML file you included:

- https://wiki.openstreetmap.org/wiki/Rivers
- https://help.openstreetmap.org/questions/22364/riverbank-to-relation

**Comment by silviot** [comment]
@paregorios The pseudocode is super helpful. Thanks! Can you provide example ids for the three cases the code needs to deal with?

**Comment by paregorios** [comment]
Examples:

- OSM relation with `@role="main_stream"`: https://www.openstreetmap.org/api/0.6/relation/2573905/full
- OSM relation lacking `@role="main_stream"` but possessing `<tag k="waterway" v="river">`: https://www.openstreetmap.org/api/0.6/relation/2335018/full

I can't easily find an example of the third case I listed above (the "otherwise" in my pseudocode). Perhaps instead of trying to use "all ways" we should report an error to the Pleiades user who is trying to import a location from OSM as we do for "invalid geometry". Perhaps some text like "cannot import OSM relation: unexpected encoding lacks role=main_stream or tag k=waterway v=river"

**Comment by silviot** [comment]
@paregorios The fix is now deployed on staging

**Comment by paregorios** [comment]
@silviot this is working great! I even managed to provoke the error I requested in the "otherwise" discussion above. It was created by this lovely beastie: https://www.openstreetmap.org/api/0.6/relation/14059404/full, wherein we find a mix of nodes with `<tag k="waterway" v="river">` and `<tag k="waterway" v="stream">`. How hard would it be to modify code to accept several different values for the "v" attribute on `<tag k="waterway"`? Based on the [Key:waterway documentation](https://wiki.openstreetmap.org/wiki/Key:waterway), we should probably support the following values for "v":

- river
- stream
- tidal_channel
- canal
- waterfall
- rapids

**Comment by silviot** [comment]
@paregorios Currently we're checking which `<way>`s to include by looking into the `<relation>` tag. [The item you mention](https://www.openstreetmap.org/api/0.6/relation/14059404/full) has this one:

```xml
<relation id="14059404" visible="true" version="8" changeset="119960687" timestamp="2022-04-20T15:47:45Z" user="gm95" uid="5457499">
  <member type="way" ref="230740870" role=""/>
  <member type="way" ref="288805758" role=""/>
  <member type="way" ref="297167515" role=""/>
  <member type="way" ref="297167506" role=""/>
  <member type="way" ref="297167502" role=""/>
  <member type="way" ref="297167510" role=""/>
  <member type="way" ref="297167511" role=""/>
  <member type="way" ref="328881325" role=""/>
  <member type="way" ref="287835589" role=""/>
  <tag k="name" v="Karadere"/>
  <tag k="name:tr" v="Kara Dere"/>
  <tag k="type" v="waterway"/>
 </relation>
```

If I understand correctly we should look into the linked `<way>`s when we can't find a `<tag>` with  `k="waterway"`. If the linked `<way>` contains a `<tag k="waterway" v="A_WHITELISTED_VALUE"/>` we should include it.
Does it sound right?

**Comment by paregorios** [comment]
@silviot yes I think so

**Comment by silviot** [comment]
@paregorios The new logic is now on staging.

**Comment by paregorios** [comment]
This is working perfectly on staging for all known test cases. Let's merge and deploy to production please.

**Comment by paregorios** [comment]
This is working perfectly on production and I have successfully reimported and published locations for all the ones that had problems previously and were annotated above.
