### ISSUE TITLE
erroneous list formatting in "Locations" list on place page: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#489]
This is not right:

![Screen Shot 2022-12-20 at 8 34 11 AM](https://user-images.githubusercontent.com/263285/208691687-a1bb0562-4aee-415f-bb93-9df86bb438f4.png)

**Comment by paregorios** [comment]
Previous screenshot was anonymous visitor. The problem seems to disappear when user has been authenticated:

![Screen Shot 2022-12-20 at 8 36 32 AM](https://user-images.githubusercontent.com/263285/208692049-4571f3d4-e9ab-41cf-ad0d-2a9c5a321922.png)

**Comment by alecpm** [comment]
Looks like maybe [here somewhere](https://github.com/isawnyu/PleiadesEntity/blob/d9ff26b3a185c06520a5f67cec9acd91c18280fa/Products/PleiadesEntity/browser/attestations.py#L517)

**Comment by silviot** [comment]
@paregorios I was not able to observe the bad behavior on https://pleiades.stoa.org/places/442113997, neither with Chrome nor with Firefox. There are no "Associated modern locations" listed. I tried some random elements but could not find a bad example.

I see this as anonymous user:
![image](https://github.com/isawnyu/pleiades-gazetteer/assets/396425/8d5b874b-ddb3-4ca9-b4b7-96f0bca0a841)

**Comment by paregorios** [comment]
@silviot another editor withdrew the associated modern location to "drafting". I have republished it temporarily so you can see the behavior in question when anonymous.

**Comment by silviot** [comment]
https://pleiades.jazkarta.com/places/442113997/ seems to work on staging

**Comment by paregorios** [comment]
I can confirm that this seems fixed on staging. I have also looked at several other place views on staging and found no problems with the locations listings thereon. So, I am happy to see these changes merged and deployed to production once any related PRs are complete.

**Comment by paregorios** [comment]
This is working well on production.
