### ISSUE TITLE
add work lookup functionality to references add/enter form components: 13pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#490]
# Overview 
It should be easier for authenticated contributors adding references via an add/edit form (place, location, name, connection) so they don't have to go search zotero and copy and paste a URI. Instead, they should be able to look up works by short title or some other query options, ideally in two modes/stages:

1. Typeahead to match a short title in an alphanumerically-ordered list that combines frequently-cited works and works the user has cited previously (in the current session, or longer ago if that's easy).
2. Query the Zotero API for a match using part of title, short title, author, and/or date (i.e., the Zotero "quick search" api function: parameter "q").

# How it should work

1. Add somewhere in "Pleiades Settings" to record short-title + Zotero URI pairs that constitute the "default works" list.
2. Keep track of short titles and URIs of works that this user has fetched from Zotero. Add them to a "combined works" list for the user that is initiated with everything in the "default works" list.
3. On the "Reference" tab of the add/edit form, move the "Bibliographic URI" widget so it comes immediately after the "Short Title" widget and add a "Copy Zotero URI" button immediately to the right of the "Short Title" text box (see graphic below).
4. When a user types in the "Short Title" text box, offer type-ahead suggestions drawn from the "combined works" list.
5. When a user clicks the "Copy Zotero URI" button, check to see if the "Short Title" text box contains something more than whitespace. If whitespace only, do nothing. If there is content that matches a short title in the "combined works" list, copy the corresponding URI into the "Bibliographic URI" text box. If there is content, but it doesn't match anything in the "combined works" list, issue a query via the Zotero API and provide the user with the ability (in a pop-up?) to select one (or none) of the possible matches (show them a full citation as retrieved via the Zotero API), copying the short title into the "short title" box and the URI into the "Bibliographic URI" box.

![ux](https://user-images.githubusercontent.com/263285/215225045-e3844c60-da64-4153-a88c-4f15d7456d77.jpg)

**Comment by paregorios** [comment]
So, for example, if a user typed "Balkan 1960" in the "Short Title" text box and then clicked the "Copy Zotero URI" button, a query would be issued to the Zotero API like `https://api.zotero.org/groups/2533/items?q=Balkan+1960` ([with appropriate "Zotero-API-Key" and "Zotero-API-Version" headers](https://www.zotero.org/support/dev/web_api/v3/basics)). 

Zotero would return a list of items, each member of which is a JSON object with information about matching works. In this case, it is a single item list:

```json
[
    {
        "key": "RCUKGP34",
        "version": 24360,
        "library": {
            "type": "group",
            "id": 2533,
            "name": "Pleiades",
            "links": {
                "alternate": {
                    "href": "https://www.zotero.org/groups/pleiades",
                    "type": "text/html"
                }
            }
        },
        "links": {
            "self": {
                "href": "https://api.zotero.org/groups/2533/items/RCUKGP34",
                "type": "application/json"
            },
            "alternate": {
                "href": "https://www.zotero.org/groups/pleiades/items/RCUKGP34",
                "type": "text/html"
            }
        },
        "meta": {
            "createdByUser": {
                "id": 6284585,
                "username": "Sobekneferu",
                "name": "Carolin Johansson",
                "links": {
                    "alternate": {
                        "href": "https://www.zotero.org/sobekneferu",
                        "type": "text/html"
                    }
                }
            },
            "lastModifiedByUser": {
                "id": 465,
                "username": "paregorios",
                "name": "Tom Elliott",
                "links": {
                    "alternate": {
                        "href": "https://www.zotero.org/paregorios",
                        "type": "text/html"
                    }
                }
            },
            "creatorSummary": "Balkan",
            "parsedDate": "1960",
            "numChildren": 0
        },
        "data": {
            "key": "RCUKGP34",
            "version": 24360,
            "itemType": "journalArticle",
            "title": "Patnos Yakınında Anzavurtepe'de Bulunan Urartu Tapınağı Ve Kitabeleri",
            "creators": [
                {
                    "creatorType": "author",
                    "firstName": "Kemal",
                    "lastName": "Balkan"
                }
            ],
            "abstractNote": "",
            "publicationTitle": "Anatolia",
            "volume": "V",
            "issue": "",
            "pages": "133-158",
            "date": "1960",
            "series": "",
            "seriesTitle": "",
            "seriesText": "",
            "journalAbbreviation": "",
            "language": "",
            "DOI": "",
            "ISSN": "",
            "shortTitle": "Balkan 1960",
            "url": "",
            "accessDate": "",
            "archive": "",
            "archiveLocation": "",
            "libraryCatalog": "",
            "callNumber": "",
            "rights": "",
            "extra": "",
            "tags": [
                {
                    "tag": "⛔ No DOI found",
                    "type": 1
                }
            ],
            "collections": [],
            "relations": {
                "owl:sameAs": "http://zotero.org/groups/2345127/items/JBG29ZTH"
            },
            "dateAdded": "2023-01-24T11:16:40Z",
            "dateModified": "2023-01-24T14:18:07Z"
        }
    }
]
```

The user will be presented with the option of choosing this item, or none as indicated above.

**Comment by paregorios** [comment]
Note that, in order to provide users with a full citation for each work (see step 5 above), a separate Zotero API call is required for each work. Therefore, if an initial search result includes more than 10 matches, show only the first ten (plus a warning). Here for example is an API call to get the citation Balkan 1960:

```https://api.zotero.org/groups/2533/items/RCUKGP34?format=bib```

and the result:

```xml
<?xml version="1.0"?>
<div class="csl-bib-body" style="line-height: 1.35; padding-left: 1em; text-indent:-1em;">
  <div class="csl-entry">Balkan, Kemal. &#x201C;Patnos Yak&#x131;n&#x131;nda Anzavurtepe&#x2019;de Bulunan Urartu Tap&#x131;na&#x11F;&#x131; Ve Kitabeleri.&#x201D; <i>Anatolia</i> V (1960): 133&#x2013;58.</div>
</div>
```

**Comment by paregorios** [comment]
IIRC the standard python wrapper for the Zotero API is used for our other Zotero interactions. I assume it is also capable of handling the relevant calls discussed above.

**Comment by silviot** [comment]
An initial draft is visible on staging.
It includes:
* [A new element in the control panel to specify default works](https://pleiades.jazkarta.com/@@pleiades-settings)
* A new "Copy Zotero URI" button next to the "Short title" field that works when you use a query that returns a single element. For instance typing "balkan 1960" and clicking the button will properly capitalize the "short title" field and place the URL https://www.zotero.org/groups/pleiades/items/RCUKGP34 in the "Bibliographic URL" field.

@paregorios Can you fill in a couple of example entries in the new "default works" settings? That will help with my testing.

**Comment by paregorios** [comment]
@silviot 

- I have added some content in the default works settings
- I was able to get the "copy zotero uri" button working intermittently.
   - I successfully added Muñoz Sogas 2022 at https://pleiades.jazkarta.com/places/87897140 by pasting the short title "Muñoz Sogas 2022" into the "short title" text box, then clicking the "copy zotero uri" button. This is great! (After that was loaded, I clicked the "fetch zotero" button.)
   - I added another reference and pasted the short title "Hatt 1980" into it, but couldn't get the "copy zotero uri" button to stop being grayed out and let me click it. I tried various things (typing, re-pasting, tabbing out), but none of them worked. With the cursor in the "short title" textbox, I hit the enter key in frustration and the zotero URI loaded into the bibliographic URI box. This is spooky behavior that will confuse our users.

**Comment by silviot** [comment]
@paregorios Thanks for the feedback! I'll fix the field/button interaction in case of multiple references.

**Comment by paregorios** [comment]
## Tom's tests (2023-03-30)

1. Add a single reference using the new functionality (works)
    a. Navigate to https://pleiades.jazkarta.com/places/87897140, click "edit", select "references" tab
    b. On an empty references tab, click "add reference".
    c. Paste "Euzennat 1994" (no quotes) in the "Short Title" text box and click the "Copy Zotero URI" button.
    d. Wait for the "Bibliographic URI" field to populate and then verify that its contents match "https://www.zotero.org/groups/pleiades/items/KJMEUVN5".
     e. Click the "fetch Zotero" button and note that the "formatted citation" and "access URI" text boxes are properly filled.
     f. Click the "Save" button and after the view reloads, verify that "Euzennat 1994" appears under **References: See Further** and the link takes you to the access URI, i.e., https://www.persee.fr/doc/crai_0065-0536_1994_num_138_2_15385.

2. Add a second reference to the same place as no. 1 using the new functionality (works)
    a. Click "edit", select "references" tab, note the presence of one reference already ("Euzennat 1994").
    b. Scroll to the bottom of the references form and click the "add reference" button.
    c. Paste "Ferdi 2005" (no quotes) into the "Short Title" text box on the second reference entry and click the "Copy Zotero URI" button.
    d. Wait for the "bibliographic uri" field to populate and then verify that its contents match "https://www.zotero.org/groups/pleiades/items/PVWNNWMN".
    e. Check the first reference to make sure nothing has changed. All good!
    f. Click "fetch zotero" button and check results. Click the save button and check results.

**Comment by silviot** [comment]
@paregorios oops! Should be fixed now.

**Comment by paregorios** [comment]
3. Add two more references during the same edit session (works)
    a.  Click "edit", select "references" tab, note the presence of two references already (Euzennat 1994 and Ferdi 2005).
    b. Scroll to the bottom of the reference form and click "add reference" and then add "Peyras 1988" and use the procedure above.
    c. Scroll below the new entry for "Peyras 1988" and click "add reference". In the short title box, paste "Ferchiou 1990".
    d. Click "Copy Zotero URI" and wait until the appropriate boxes are updated as for previous entries.

**Comment by silviot** [comment]
@paregorios I updated staging. Now the case when there's more than one result is usable (albeit quite ugly - I didn't work on styling it yet).

Some search results don't have a `shortTitle`, so the routine that puts together the citation errors out. In these cases you'll see links turn red.

The autocomplete is not yet integrated: I need to solve a timing problem before deploying it.

**Comment by paregorios** [comment]
@silviot this functionality is now all working as I could expect, but I've noticed a new wrinkle:

We need to exclude "attachments" from the query of the Zotero library. For example, for the short title "Ferchiou 1990", we get two hits:

![Screen Shot 2023-03-31 at 11 47 36 AM](https://user-images.githubusercontent.com/263285/229183646-9247a748-63f4-4c47-8755-8d0e92e735aa.png)

The first of these (in red) is a PDF file attached to the bibliographic record, which is the second entry in our list. For this functionality in Pleiades we only want to see the bibliographic record, not attached files. I think this can be accomplished by adding `itemType=-attachment` to the Zotero API query (note the `-` sign before the word "attachment"; see https://www.zotero.org/support/dev/web_api/v3/basics#search_syntax).

**Comment by silviot** [comment]
@paregorios Thanks for providing the condition to add! I added it and deployed to staging.

**Comment by silviot** [comment]
@paregorios I added the autocomplete. It's still not working on fields that are not present at page load, i.e. if you click "Add reference".

**Comment by paregorios** [comment]
@silviot I have not been able to test autocomplete, but I do have some more comments on the zotero API search/results aspect.

I'm still seeing items I don't want to see in the pick list when the search gets multiple hits. For example, the item in red below:

![Screen Shot 2023-03-31 at 5 15 29 PM](https://user-images.githubusercontent.com/263285/229242577-ed15cc12-f8a5-401c-a23d-2607e1ae1e2c.png)

That's another kind of item (a "snapshot") that is a child of the bibliographic item we do want. 

A tangentially related [post in the zotero developers' google group](https://groups.google.com/g/zotero-dev/c/_Kak0uh7B4A/m/Pbj83fgNAAAJ) makes me want to try a slightly different pattern for the Zotero API call: `<userOrGroupPrefix>/items/top` instead of `<userOrGroupPrefix>/items` ([see cryptic API docs](https://www.zotero.org/support/dev/web_api/v3/basics#items)). I hope that will exclude anything and everything that is a subordinate (child) item, since in addition to `attachment` and `snapshot` there are also `note` and `annotation` objects and maybe other types.

The hierarchy is clear when I look at the library in the Zotero desktop client. Here's a relevant screen capture, showing some items (including the one in question here) that have subordinate `attachments` (pdfs) and `snapshots` (html).

![Screen Shot 2023-03-31 at 5 21 48 PM](https://user-images.githubusercontent.com/263285/229243386-32dfe48e-34a7-4cd3-96ee-b4a5fedce9ba.png)

**Comment by silviot** [comment]
@paregorios I updated staging to use `items/top` instead of `items` endpoint.

**Comment by paregorios** [comment]
@silviot the query change on staging seems to be working well.

Can you share the query URI structure with me (and any pre-processing on the short title value before it goes into the query)? There are a few strings I'm trying to use that are not returning any results and I'm curious about the reasons.

**Comment by silviot** [comment]
@paregorios Here is the line where the URL for the query is constructed:
https://github.com/isawnyu/PleiadesEntity/pull/59/files#diff-65b7d50658cfcc3c8d90e4e45658265677485a5b0218e8d1a106087d6be55bf6R93

There's no pre-processing of the query string besides `encodeURIComponent`.

**Comment by paregorios** [comment]
@silviot attempting to test typeahead on staging I'm seeing no effect in the UI. I fired up the console and see:
```
Uncaught ReferenceError: pleiades_default_works is not defined
    at HTMLDocument.<anonymous> (forms-cachekey-c848c7a5dcd15d07172c3533e89eeb9a.js:32:440)
    at o (resourceplone.app.jquery-cachekey-04ab6c6cba52660325f209264eea79ba.js:12:14733)
    at Object.fireWith (resourceplone.app.jquery-cachekey-04ab6c6cba52660325f209264eea79ba.js:12:15502)
    at Function.ready (resourceplone.app.jquery-cachekey-04ab6c6cba52660325f209264eea79ba.js:12:9594)
    at HTMLDocument.B (resourceplone.app.jquery-cachekey-04ab6c6cba52660325f209264eea79ba.js:12:14290)
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by silviot** [comment]
@paregorios The site-wide frequently used should now work fine. Now the last part of the ticket (per user list of most recently used titles) needs to be implemented.

I suggest testing and deploying what we have so far, and working on the per-user dictionary as a separate task that improves on this.

**Comment by paregorios** [comment]
@silviot thanks. I'll take a look at this on staging at my earliest opportunity today,  but it may be some hours. I think your suggestion about splitting this up is a good one, so I'll follow up on that too.

**Comment by silviot** [comment]
@paregorios Perfect!

In the new story we'll need to expand on what exactly this means:

> Keep track of short titles and URIs of works that this user has fetched from Zotero

i.e. at what time precisely should a short title/URI be considered "used"? If we go with form submission, edits to existing documents might introduce items we didn't mean to include.
We might consider an item "used" when it's selected in the form UI, before the "Save" button is clicked. This also might introduce spurious items, but probably less.

**Comment by paregorios** [comment]
@silviot I have reviewed on staging and have the following observations about what works:

1. Typing and matching/selecting items from the "default works" list in the drop-down from the "short title" body text works perfectly.
2. Creating a new `place` object, editing it, adding a reference, entering text in the shortTitle, and pressing the return key issues a query to Zotero that then populates the drop-down perfectly.
3. This procedure also works for new `location`, `name`, and `connection` objects, as desired.
4. Edit a `place`, `name`, `location`, or `connection` object that already has one or more references, add a new reference, click in the shortTitle text box for the new (empty) reference, type a value from the "default works" list, select it from the drop down. That works great.

Here's what's not working yet:

1. Edit a place that already has one of more references, add a new reference, click in the shortTitle text box for the new (empty) reference, type a word or phrase in the text box that is NOT in the "default works" list and press the RETURN key to initiate a Zotero search. The drop-down box does not appear on this shortTitle text box. Instead, it appears on the shortTitle text box for the very first reference in the References tab. The query sent to Zotero (as observed in the Network console) is also incorrect: it contains the shortTitle value from the first reference, not the reference where the cursor is focused. 

For example, consider the following screen capture. I created the reference for "CosmasInd" and saved the place. Then I edited it again, created a new reference, typed "Lagash" in the second reference's "Short Title" field, and pressed the RETURN key. You can see the pink-colored "No results found" warning under the first "Short Title" field, instead of the one where I entered the data. You can also tell from that message that it didn't search for "Lagash" but instead searched for "CosmasInd". Indeed, the URL generated and sent to the Zotero URI is `https://api.zotero.org/groups/2533/items/top?limit=10&itemType=-attachment&q=CosmasInd` instead of `...q=Lagash` as expected.

![Image](https://github.com/isawnyu/pleiades-gazetteer/assets/263285/9e73818e-65f3-4075-ba12-7b4f90b624f6)

**Comment by silviot** [comment]
@paregorios Wow! This (hopefully) last problem took way more than I expected. It should be fixed now though!

**Comment by paregorios** [comment]
@silviot this is working great on staging. Please merge to master and deploy to production.

**Comment by silviot** [comment]
@paregorios Deployed to production.

Dev note:
I had to create the registry entry manually. I suspect I did the same on my machine and in staging but didn't document what I did. Note to self: always document what you do!

This is the script that I used to create the entry:
```python
from zope.site.hooks import setSite
setSite(app.plone)

from plone.registry.interfaces import IRegistry
from zope.component import getUtility
from pleiades.vocabularies.interfaces import IPleiadesSettings

registry = getUtility(IRegistry)
settings = registry.forInterface(IPleiadesSettings, check=False)

registry.records._values[settings.__prefix__ + 'default_works'] = [{'zotero_uri': 'https://www.zotero.org/groups/2533/items/DUTS58MJ', 'short_title': u'New Pauly'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/HSGNAEBR', 'short_title': u'RE'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/MIAGQ5C6', 'short_title': u'BAtlas'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/9377UUFB', 'short_title': u'BAtlDir'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/CI6F6W7W', 'short_title': u'Wikipedia (English)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/BUR4V79V', 'short_title': u'Wikipedia (Greek)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/B4HPCZIK', 'short_title': u'Wikipedia (French)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/QVRBJVTM', 'short_title': u'Wikipedia (German)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/UMFZH98D', 'short_title': u'Wikipedia (Italian)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/BCQIKDKS', 'short_title': u'Wikidata'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/QT8GLGGI', 'short_title': u'TP (Talbert: CUP)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/FEVTVBA7', 'short_title': u'Str. (Meineke: Perseus)'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/CMCPFLWG', 'short_title': u'Roller 2022'}, {'zotero_uri': 'https://www.zotero.org/groups/2533/items/XFWEA9BC', 'short_title': u'Basarrate 2022'}]

import transaction
transaction.commit()
```

**Comment by paregorios** [comment]
@silviot The UI functionality is working on production, but I tried removing and adding references to the vocabulary in "Pleiades settings" and when I click save, I get a traceback:

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 145, in update
    Module plone.app.z3cform.csrf, line 21, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module plone.app.registry.browser.controlpanel, line 61, in handleSave
    Module z3c.form.group, line 114, in applyChanges
    Module z3c.form.form, line 51, in applyChanges
    Module z3c.form.datamanager, line 91, in set
    Module plone.registry.recordsproxy, line 49, in __setattr__
    Module plone.registry.registry, line 47, in __setitem__
    Module plone.registry.registry, line 212, in __getitem__
    Module plone.registry.registry, line 269, in _getField

KeyError: 'pleiades.vocabularies.interfaces.IPleiadesSettings.default_works' 
```

**Comment by paregorios** [comment]
Steps to reproduce:

1. As an authenticated user with Admin privileges, navigate to https://pleiades.stoa.org/@@pleiades-settings
2. Scroll down to "Default works"
3. Using the minus sign at the right, remove the reference in the last row (Basarrate 2022)
4. Click the "save" button.
5. Observe the traceback:

```
Traceback (innermost last):

    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.z3cform.layout, line 66, in __call__
    Module plone.z3cform.layout, line 50, in update
    Module plone.z3cform.fieldsets.extensible, line 59, in update
    Module plone.z3cform.patch, line 30, in GroupForm_update
    Module z3c.form.group, line 145, in update
    Module plone.app.z3cform.csrf, line 21, in execute
    Module z3c.form.action, line 98, in execute
    Module z3c.form.button, line 315, in __call__
    Module z3c.form.button, line 170, in __call__
    Module plone.app.registry.browser.controlpanel, line 61, in handleSave
    Module z3c.form.group, line 114, in applyChanges
    Module z3c.form.form, line 51, in applyChanges
    Module z3c.form.datamanager, line 91, in set
    Module plone.registry.recordsproxy, line 49, in __setattr__
    Module plone.registry.registry, line 47, in __setitem__
    Module plone.registry.registry, line 212, in __getitem__
    Module plone.registry.registry, line 269, in _getField

KeyError: 'pleiades.vocabularies.interfaces.IPleiadesSettings.default_works' 
```

**Comment by paregorios** [comment]
Additional works can be added without difficulty. I am going to break the traceback out as a bug to fix in a future iteration and close this ticket shortly, since it is not a show-stopper.

**Comment by paregorios** [comment]
This is working on production. There is one bug I've noticed. I opened #497 to track it; it's on the backlog for now so we will address in a future iteration.
