### ISSUE TITLE
ensure isaw1staging is ready for March 2023 iteration

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#491]
- [x] ensure OS and server package updates match production isaw1
- [x] ensure all staging branches at github are up-to-date vs. production branches and that these are cleanly deployed on isaw1staging
- [x] copy production zope database and blob storage from isaw1 to isaw1staging

**Comment by alecpm** [comment]
The servers are identically configured. Both are running Ubuntu 20.04 LTS. It may make sense to consider Ubuntu Pro + Extended Security Maintenance to get security updates for some packages, including `python2.7`.

**Comment by paregorios** [comment]
Now that [the ticket for Ubuntu Pro ESM](https://github.com/isawnyu/isaw.web/issues/463) has been created, I am closing this ticket as complete.
