### ISSUE TITLE
add "reimport from OSM" affordance to Pleiades locations: 3 pt

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#492]
For authenticated users with the "editor" role on a Pleiades `location` object, add a "reimport from OSM" affordance (either as a button or an actions menu option, perhaps). When activated, this affordance does the following:

- Check to see if the referenced OSM object still exists.
    - If the referenced OSM object has been deleted, report this error to the user and do nothing further
- If the referenced OSM object does exist, use the OSM API to get the latest information about the object (there may be a newer revision at OSM than the one originally used in Pleiades -- use the most recent at OSM). Repopulate the following fields on the Pleiades `location` object, using corresponding data from the OSM object:
    - write the OSM geometry as a GeoJSON fragment to the "coordinates" field (i.e., the same format we use on initial import)
    - verify/ensure that the Pleiades location references the ["Generic OSM" Positional Accuracy Assessment](https://pleiades.stoa.org/features/metadata/generic-osm-accuracy-assessment)
    - rewrite the "Provenance" field using the same format that we use on an initial import
- save the changes along with an appropriate comment in the object history: "reimported full [Node|Way|Relation] geometry and updated provenance"

**Comment by jessesnyder** [comment]
@paregorios Draft ready for your review/testing. 

Preview video [here](https://www.screencast.com/t/LqQeP5RDFIQ).

I'm not entirely sure what this means, and whether I'm complying with it:
> verify/ensure that the Pleiades location references the ["Generic OSM" Positional Accuracy Assessment](https://pleiades.stoa.org/features/metadata/generic-osm-accuracy-assessment)

Also, I did a fair amount of refactoring since the creation and updating of Locations shares a lot in common. This means creation should also be tested to make sure I didn't break that.

**Comment by paregorios** [comment]
@jessesnyder this looks good to go. I've moved it to "merge" column in project. I'm happy to see it deployed to production.
