### ISSUE TITLE
update text and links in homepage

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#493]
The text in `/home` is hard-coded into [the page template](https://github.com/isawnyu/pleiades-notredame/blob/1a37d7fc04f53d63bf6ab6ad6ef0a4c4774bb9ab/pleiades/notredame/skins/pleiades_notredame_custom_templates/home.pt). 
The "about" section needs updates to drive readers to our "reports", "papers", and "help" sections.

**Comment by jessesnyder** [comment]
pleiades.gazetteer <- update tag in buildout and in Ansible

**Comment by paregorios** [comment]
@jessesnyder is this ready to deploy in your view?

**Comment by jessesnyder** [comment]
Pin update is merged to `master` in isawnyu/pleiades3-buildout, but I wasn't able to SSH into production to deploy the change.

**Comment by paregorios** [comment]
Looks good on production!
