### ISSUE TITLE
json serializations have incorrect values in reference "type" field 2pt

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#495]
JSON serializations of references (on places, locations, names, and connections) repeat the `citationTypeURI` value in the `type` field instead of providing the actual value used the [ReferenceCitation.schema["type"].vocabulary](https://github.com/isawnyu/PleiadesEntity/blob/master/Products/PleiadesEntity/content/ReferenceCitation.py#L31).

For example, we get:

```json
{
    "alternateURI": "",
    "accessURI": "",
    "citationDetail": "",
    "citationTypeURI": "http://purl.org/spar/cito/seeFurther",
    "shortTitle": "",
    "bibliographicURI": "http://openlibrary.org/works/OL8327792W",
    "formattedCitation": "BAtlas 55 B4 Euenos fl.",
    "otherIdentifier": " ",
    "type": "http://purl.org/spar/cito/seeFurther"
}
```

when what we should see is

```json
{
    "alternateURI": "",
    "accessURI": "",
    "citationDetail": "",
    "citationTypeURI": "http://purl.org/spar/cito/seeFurther",
    "shortTitle": "",
    "bibliographicURI": "http://openlibrary.org/works/OL8327792W",
    "formattedCitation": "BAtlas 55 B4 Euenos fl.",
    "otherIdentifier": " ",
    "type": "seeFurther"
}
```

**Comment by jessesnyder** [comment]
@paregorios Remind me: how do I generate said JSON?

**Comment by paregorios** [comment]
You can get it two ways:

- per place object by appending `/json` to the URI (for example: https://pleiades.stoa.org/places/295374/json)
- as a dump of the entire database contents using a script; see this link for the script installed by ansible for cron nightly: https://github.com/isawnyu/pleiades-ansible/blob/master/files/pleiades-dump-all#L13

**Comment by jessesnyder** [comment]
@Tom Elliott (he/they, him/them) Some interesting reading here:
https://github.com/isawnyu/pleiades-gazetteer/issues/416

Back in November 2020, @alecpm added infrastructure to support prepending the URL prefix-y bit (see https://github.com/isawnyu/PleiadesEntity/commit/009317498e0672e498359f044a24834a650332a7)

Are you confident about this proposed change (~which seems like it might just be a reversion~ correction: it looks like it was always a URI, but previously it was a URI internal to the site)?

**Comment by paregorios** [comment]
PR discussion between @alecpm and @jessesnyder seems to be ongoing here: https://github.com/isawnyu/PleiadesEntity/pull/60

**Comment by jessesnyder** [comment]
This is now on staging, @paregorios 
https://pleiades.jazkarta.com/places/579885/json

**Comment by paregorios** [comment]
This is looking great! Please merge to master, deploy to production, and unleash the Kraken.

**Comment by paregorios** [comment]
this is working as desired on production. Thanks.
