### ISSUE TITLE
cannot add new place type to Pleiades settings

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#499]
Steps to reproduce:

- Login to the Pleiades plone with an account with admin privileges
- Navigate to `@@pleiades-settings`
- Scroll to the bottom of the "Place Types" table and enter this data in the new line:

| Id | Title | Description | Same As |
| --- | --- | --- | --- | 
| stupa | stupa | A stupa as defined by the Getty Art and Architecture Thesaurus: Buddhist relic mounds of earth, brick, or stone, dominated by a hemispherical or bulbous dome set on a square or circular base and topped by a small pavilionlike structure and a spire. Stupas often serve as pilgrimage sites and symbols of the Buddha or his teachings. | https://vocab.getty.edu/aat/300007576 |

- Scroll to the bottom of the page and click the "save" button. 
- Wait for the page to save and reload, then check for the new place type. You will not find it.

**Comment by silviot** [comment]
See [this comment](https://github.com/isawnyu/pleiades-gazetteer/issues/498#issuecomment-1652596863).

As an interim solution I ran this code:

```
app.plone.portal_registry._records["pleiades.vocabularies.interfaces.IPleiadesSettings.place_types"]._set_value(app.plone.portal_registry._records["pleiades.vocabularies.interfaces.IPleiadesSettings.place_types"].value + [{'id': u'stupa', 'same_as': 'https://vocab.getty.edu/aat/300007576', 'description': u'A stupa as defined by the Getty Art and Architecture Thesaurus: Buddhist relic mounds of earth, brick, or stone, dominated by a hemispherical or bulbous dome set on a square or circular base and topped by a small pavilionlike structure and a spire. Stupas often serve as pilgrimage sites and symbols of the Buddha or his teachings.', 'hidden': False, 'title': u'stupa'}])
```

**Comment by paregorios** [comment]
This is working on production.
