### ISSUE TITLE
Enable work lookup functionality for names, locations, connections

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#501]
I feel like this came up early in development too, but I can't find documentation. In any case, right now on production, work lookup functionality (implemented in #490) is only working for `place` objects, even though it has previously worked for `name`, `location`, and `connection` objects (and that's what we originally were seeking).

**Note the "Uncaught ReferenceError: pleiades_default_works is not defined" we're throwing when loading location and name pages as identified in #505.**

**Comment by silviot** [comment]
Should be fixed on staging.

**Comment by paregorios** [comment]
This is working on staging. I would be pleased to see it merged and deployed to production once another developer has reviewed and approved the PR.

**Comment by silviot** [comment]
Deployed to production.

**Comment by paregorios** [comment]
This is working perfectly on production. Thanks!
