### ISSUE TITLE
OSM refresh function produces error

### ISSUE THREAD

**Issue by serviliusahala** [isawnyu/pleiades-gazetteer#504]
The dropdown function to refresh already-published OSM data produces an error on multiple pages, e.g.,

We’re sorry, but there seems to be an error…
Here is the full error message:

[Display traceback as text](https://pleiades.stoa.org/places/393414/location-of-jesolo/error_log/getLogEntryAsText?id=1701616690.140.126107457127)

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.PleiadesEntity.browser.osm, line 282, in __call__
Module Products.PleiadesEntity.browser.osm, line 94, in fetch_osm_by_type_and_id
Module requests.api, line 75, in get
Module requests.api, line 61, in request
Module requests.sessions, line 529, in request
Module requests.sessions, line 645, in send
Module requests.adapters, line 532, in send
ReadTimeout: HTTPSConnectionPool(host='www.openstreetmap.org', port=443): Read timed out. (read timeout=3.0)

**Comment by paregorios** [comment]
@serviliusahala the cryptic last line in the traceback:

> ReadTimeout: HTTPSConnectionPool(host='www.openstreetmap.org', port=443): Read timed out. (read timeout=3.0)

usually indicates that either the OpenStreetMap API is having a problem or is down for maintenance, or that there is some sort of network routing problem or DNS problem occurring between the Pleiades server and the OSM server.

I don't see mention of a problem [here](https://en.osm.town/@osm_tech) that corresponds to the timing of your ticket, but I'm not clear how frequently or completely that account is updated. 

Can you try one or two of the updates that failed for you again and let me know here whether they go through now or continue to produce the error?

**Comment by serviliusahala** [comment]
@paregorios I have not been able to reproduce the error. I have tried a few random places and refreshed OSM data and the function seems normal, so perhaps I caught the matrix at a bad moment on the weekend.
