### ISSUE TITLE
Maps on location pages have stopped working

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#505]
Where we would expect to see a map on a location page, we only now see a blank rectangle. The only error I see in the FF browser console is not obviously related, but maybe it's halting execution before we get to run the map-related Javascript? 

```
Uncaught ReferenceError: pleiades_default_works is not defined
    <anonymous> https://pleiades.stoa.org/portal_javascripts/Notre Dame/forms-cachekey-1ad9541b6091895a705c56f3b1d410db.js:36
    jQuery 11
        o
        fireWith
        ready
        B
        bindReady
        ready
        init
        e
        support
        <anonymous>
        <anonymous>
[forms-cachekey-1ad9541b6091895a705c56f3b1d410db.js:36:452](https://pleiades.stoa.org/portal_javascripts/Notre%20Dame/forms-cachekey-1ad9541b6091895a705c56f3b1d410db.js)
    <anonymous> https://pleiades.stoa.org/portal_javascripts/Notre Dame/forms-cachekey-1ad9541b6091895a705c56f3b1d410db.js:36
    jQuery 11
        o
        fireWith
        ready
        B
        (Async: EventListener.handleEvent)
    bindReady
        ready
        init
        e
        support
        <anonymous>
        <anonymous>
```

Chrome behaves similarly, both in terms of appearance and the traceback.

**Comment by paregorios** [comment]
I wonder if this is related to #501? I see the same `Uncaught ReferenceError: pleiades_default_works is not defined` getting thrown when loading a "name" view, like https://pleiades.stoa.org/places/452399/Palinurus-Pr

**Comment by silviot** [comment]
It looks like the fox for #501 also took care of this one, as expected. [This is the location](https://pleiades.jazkarta.com/places/950560042/osm-location-of-augusta-bagiennorum-amphitheatre) I checked, that's currently working in staging [but not on production](https://pleiades.stoa.org/places/950560042/osm-location-of-augusta-bagiennorum-amphitheatre).

**Comment by paregorios** [comment]
I can confirm this is working on staging. Of course we can't close the issue until #501 is reviewed, approved, merged, and deployed to production.

**Comment by paregorios** [comment]
This is now working on production. Thanks.
