### ISSUE TITLE
Disable and completely remove "Related Content from Pelagios" portlet: 3pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#506]
The Pelagios/Peripleo API that we used for this portlet has been shut down and will not be replaced, so we need to get rid of the non-functional portlet.

**Comment by jessesnyder** [comment]
Looks like our speculation was correct, and this is assigned to the Place content type (I don't see it assigned to anything else):

![Image](https://github.com/isawnyu/pleiades-gazetteer/assets/63560/811f8867-2069-40ac-ab87-4dda08ee3fd1)

@paregorios Was it your belief that it only appears on Places?

**Comment by paregorios** [comment]
@jessesnyder yes, it is my belief that this portal only appears on Places.

**Comment by jessesnyder** [comment]
@paregorios Updates:
1. The portlet has been removed on staging and production
2. The `pleiades.policy` package has an upgrade step which removes the portlet registered and assigned by the `pleiades.portlet.pelagios` package, in case there are more installs that need to remove the portlet
3. The updated version of `pleiades.policy` is installed on staging and prod
4. There's a [PR](https://github.com/isawnyu/pleiades3-buildout/pull/15) to remove `pleiades.portlet.pelagios` from the buildout when we're ready

**Comment by paregorios** [comment]
@jessesnyder confirm that the portal is gone from production. Yay! Let me know if/when you want me to close this ticket.

**Comment by jessesnyder** [comment]
@paregorios Buildout updates made on staging and production, and all seems well. Maybe give it a quick test yourself, but then I'd say we're ready to close the issue 📕
