### ISSUE TITLE
surface location accuracies on place page in locations list: 2pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#507]
Currently, the location listings on our place pages look like this:

<img width="336" alt="Screen Shot 2024-02-01 at 1 07 18 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/263285/e24a87ce-75ae-4880-9c5c-c156df67d285">

i.e., they include the title of each location (linked to the corresponding object), followed by a calculated date range comprising the time periods assigned to the location. 

The goal of this ticket is to enhance the listing by indicating the horizontal accuracy of each location's geometry, thus:

> __Locations:__
> - [DARE Location](https://pleiades.stoa.org/places/334641/dare-location) (30 BC - AD 640). Accuracy: +/- 10 meters.
> - [DARMC location 15159](https://pleiades.stoa.org/places/334641/darmc-location-15159) (30 BC - AD 640). Accuracy: +/- 100 meters.

The numeric accuracy value can be found by traversing from the location to its linked "Positional Accuracy Assessment" object and taking the value in its "positional accuracy" field. For example, for the first location (DARE) in the example above, the linked PAA is [DARE Precision 3](https://pleiades.stoa.org/features/metadata/dare-3).

If there is no linked PAA or if the PAA's positional accuracy field is empty, the listing should read: "Accuracy: undefined (data missing)".

**Comment by silviot** [comment]
Visible on staging for review. I did not include the period before `Accuracy` since omitting it simplified my work and I was not sure how important it is.

**Comment by paregorios** [comment]
I think it looks fine. Maybe lower-case "a" to start "accuracy" (to keep pedantic grammarian users from losing their minds ... ;).

**Comment by paregorios** [comment]
looks great, thanks!
