### ISSUE TITLE
remove text links for AWMC alacarte and peripleo from place view map border: 1pt

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#508]
Currently, we have the following links immediately below the maps on our place pages:

<img width="557" alt="Screen Shot 2024-02-01 at 12 31 00 PM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/263285/e28b9f18-e12c-4f58-b62b-974a05420356">

The first line should be changed to read:

```
Show place in Google Earth.
```

where the text "Google Earth" remains a link to the KML serialization of the corresponding place resource. I.e., remove the links to AWMC Antiquity A-la Carte and to Peripleo because both of these services no longer exist.

**Comment by jessesnyder** [comment]
@paregorios I see the same set of links with the same format in the both the view for Places and for Locations. Should they both be changed?

**Comment by paregorios** [comment]
@jessesnyder yes please if at all possible

**Comment by jessesnyder** [comment]
@paregorios Ready for review on staging...
Place: https://pleiades.jazkarta.com/places/579885
Location: https://pleiades.jazkarta.com/places/168254096/parthenon

**Comment by paregorios** [comment]
@jessesnyder this is looking and working as desired. Once any outstanding PR reviews are complete, I would be happy to see it merged and deployed to production.

**Comment by jessesnyder** [comment]
@paregorios This has been deployed 🚀

**Comment by paregorios** [comment]
Working great on production.
