### ISSUE TITLE
RSS portlet doesn't work: 3 pts

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#513]
As an anonymous or authenticated visitor to the ISAW website, I should see titles and summaries of recent public posts and boosts from the Pleiades mastodon account via the RSS portlet where deployed on the site. We've been running it for weeks, and posting to the referenced account, but seeing no content in the portlet.

- Portlet is currently deployed at and below https://pleiades.stoa.org/news/blog.
- Referenced RSS feed is configured as https://botsin.space/@pleiades.rss

The referenced RSS feed is being updated with content:

```
curl https://botsin.space/@pleiades.rss
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:webfeeds="http://webfeeds.org/rss/1.0" xmlns:media="http://search.yahoo.com/mrss/">
  <channel>
    <title>Pleiades Gazetteer</title>
    <description>Public posts from @pleiades@botsin.space</description>
    <link>https://botsin.space/@pleiades</link>
    <image>
      <url>https://files.botsin.space/accounts/avatars/000/031/802/original/f9cc6a09c3f05dec.png</url>
      <title>Pleiades Gazetteer</title>
      <link>https://botsin.space/@pleiades</link>
    </image>
    <lastBuildDate>Tue, 30 Apr 2024 12:46:35 +0000</lastBuildDate>
    <webfeeds:icon>https://files.botsin.space/accounts/avatars/000/031/802/original/f9cc6a09c3f05dec.png</webfeeds:icon>
    <generator>Mastodon v4.2.7</generator>
    <item>
      <guid isPermaLink="true">https://botsin.space/@pleiades/112360239619107846</guid>
      <link>https://botsin.space/@pleiades/112360239619107846</link>
      <pubDate>Tue, 30 Apr 2024 12:46:35 +0000</pubDate>
      <description>&lt;p&gt;Export Updates 2024-04-30:&lt;br /&gt;Pleiades gazetteer of ancient places&lt;/p&gt;&lt;p&gt;21 updated places.&lt;/p&gt;&lt;p&gt;1. Downloads: &lt;a href="https://pleiades.stoa.org/downloads" target="_blank" rel="nofollow noopener noreferrer" translate="no"&gt;&lt;span class="invisible"&gt;https://&l
⋮
```

**Comment by paregorios** [comment]
Given the nature of the feed entries, I think we want to see something like:

___

__{date - nicely formatted for an international audience so like 4 March 2024}__
{description as html}

___

the `date` line should link to the original post

**Comment by alecpm** [comment]
@paregorios Would it be acceptable to format any RSS input that is missing a title field in this manner when loaded into the portlet?

**Comment by paregorios** [comment]
Yes

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

pronouns: he, him
https://paregorios.org/
Humanities Commons: @paregorios <https://hcommons.org/members/paregorios/>
OrcID: 0000-0002-4114-6677 <http://orcid.org/0000-0002-4114-6677>

**Comment by alecpm** [comment]
@paregorios I've got this working locally, but it doesn't look great:

<img width="255" alt="Screenshot 2024-05-02 at 10 39 00 AM" src="https://github.com/isawnyu/pleiades-gazetteer/assets/202854/8ba9790f-58db-4f7a-9ec4-855a32e2428c">

Any ideas?

**Comment by alecpm** [comment]
This is [live on staging](https://pleiades.jazkarta.com/news/blog) for review. Hopefully we can figure out how to make it look halfway decent.

**Comment by paregorios** [comment]
@alecpm I've made some suggestions on the PR https://github.com/isawnyu/pleiades-notredame/pull/7

**Comment by paregorios** [comment]
@alecpm This looks good to me on staging,. From my perspective it's ready to merge and deploy  to production.

**Comment by paregorios** [comment]
I restarted varnish on production and now this is looking as desired. Closing as "fixed".
