### ISSUE TITLE
modify maps code to fetch json from separate URI rather than using encoded URL in page link

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#52]
Construction of the embedded JSON URIs in place views has been identified as a source of significant slow-down for page rendering (see background discussion, mixed with other issues, at #51). Removing these would speed page load. Maps would still need to fetch the JSON, which would take time, but it wouldn't hold up initial painting of the HTML page. 

Itemization (incomplete?) of map-related templates that use the embedded JSON URL and therefore need to be changed:

 * [place_map.js](https://github.com/isawnyu/PleiadesEntity/blob/master/skins/PleiadesEntity/place_map.js#L54) 
 * [location_map.js](https://github.com/isawnyu/PleiadesEntity/blob/master/skins/PleiadesEntity/location_map.js#L54)

**Comment by alecpm** [comment]
This is completed and deployed to the staging server.  Once tested we can safely deploy to production.

**Comment by davisagli** [comment]
On the plone 4 site I've optimized the `temporalRange` method. It now caches the temporal ranges of the temporal vocab terms on the request so they only need to be calculated once per request, rather than once per item that temporalRange is called on.
