### ISSUE TITLE
expand map bounds for place, search, and home pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#521]
All maps in Pleiades have maximum bounds except locations, and these are now insufficient for some content that has recently been added (e.g., [Teniky in Madagascar](https://pleiades.stoa.org/places/377313804), which has a reprPoint lat/lon of -22.302631, 45.307556 but currently doesn't display because our maps won't zoom that far south. We need to expand our maximum bounds to include all of Europe, Africa, and Asia.

**Comment by paregorios** [comment]
Desired new maximum bounds for all bounds-limited maps (i.e., all except locations) are:

West bounds: -30 longitude
North bounds: 80 latitude
East bounds: 180 longitude
South bounds: -45 latitude

**Comment by paregorios** [comment]
Relevant code:
- https://github.com/isawnyu/PleiadesEntity/blob/c6362b51e1cfec7898e111d8d236d85ce8ea45eb/Products/PleiadesEntity/skins/PleiadesEntity/place_map.js#L29
- https://github.com/isawnyu/pleiades-notredame/blob/6b080c2ee617695cff84c128d95c7bd8e236d970/pleiades/notredame/skins/pleiades_notredame_custom_templates/search_map.js#L21
- https://github.com/isawnyu/pleiades-notredame/blob/6b080c2ee617695cff84c128d95c7bd8e236d970/pleiades/notredame/skins/pleiades_notredame_custom_templates/recent_map.js#L21

Location maps already work correctly; [they use different code](https://github.com/isawnyu/PleiadesEntity/blob/c6362b51e1cfec7898e111d8d236d85ce8ea45eb/Products/PleiadesEntity/skins/PleiadesEntity/location_map.js) than the other maps.

**Comment by jessesnyder** [comment]
@paregorios Imported [Teniky](https://pleiades.jazkarta.com/places/377313804) into staging and seems to be working.

Wasn't sure where to test `search_map.js` and `recent_map.js`?

**Comment by paregorios** [comment]
Am away from computer but

Search_map should show up on advanced search result pages and recent_map
iirc is used on /home

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

pronouns: he, him
https://paregorios.org/
Humanities Commons: @paregorios <https://hcommons.org/members/paregorios/>
OrcID: 0000-0002-4114-6677 <http://orcid.org/0000-0002-4114-6677>

**Comment by paregorios** [comment]
@jessesnyder this is looking good on staging (all three map types). Please merge and deploy to production.

**Comment by jessesnyder** [comment]
@paregorios Deployed and looking good to me. :shipit:

**Comment by paregorios** [comment]
@jessesnyder agree. Closing as resolved!
