### ISSUE TITLE
lists of locations and names missing from place view on staging

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#57]
Compare ```/places/579885``` on production and staging. 

On production, an anonymous user sees:

![athens-production](https://cloud.githubusercontent.com/assets/263285/13400074/b3d74fca-decb-11e5-934f-8d1248bf1ea4.jpg)

But on staging, the listings of published names and locations are missing:

![athens-staging](https://cloud.githubusercontent.com/assets/263285/13400085/c61216c0-decb-11e5-95c3-17cea92c5f9f.jpg)

**Comment by alecpm** [comment]
Should be fixed.

**Comment by paregorios** [comment]
This looks good in both P3 and P4 staging. Closing as resolved.
