### ISSUE TITLE
specify a complete JSON export format

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#58]
To support both our comprehensive export requirement (#41) and our batch create/update import story (#38). 

Specific tasks:
- [x] Create a separate repository for work on this component: see now [pleiades-comprehensive](https://github.com/isawnyu/pleiades.comprehensive)
- [ ] Create a complete JSON example file (i.e., includes all fields from place, name, and location): [in-progress](https://raw.githubusercontent.com/isawnyu/pleiades.comprehensive/master/json/example.json)
- [ ] Create a JSON Schema to facilitate validation of JSON components: [in-progress](https://github.com/isawnyu/pleiades.comprehensive/blob/master/json/schema.json)
- [ ] TBD

**Comment by ryanfb** [comment]
Any interest/use in hooking up Travis continuous validation for this? I think you would just need the following in `.travis.yml`:

```
language: node_js
sudo: false
before_script:
  - npm install -g jsonlint
script: jsonlint -q -V json/schema.json json/example.json
```

**Comment by paregorios** [comment]
Travis is hooked up and I've added status message to the README and the first build has run and passed. Thanks @ryanfb
