### ISSUE TITLE
Credits not working

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#62]
part of #49 

When logged in, http://pleiades.jazkarta.com/credits does not list any individuals (likely related to absence of LDAP on the staging server).

When logged out, http://pleiades.jazkarta.com/credits shows the login form rather than the credits page.

**Comment by davisagli** [comment]
Both fixed.

**Comment by paregorios** [comment]
Looks good. Closing as resolved.
