### ISSUE TITLE
Remove Poi leftovers

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#64]
part of #49 

Uninstalling Poi leaves behind some catalog indexes and metadata that we can remove:
- getArea
- getRelease
- getIssueType
- getSeverity
- getTargetRelease
- getResponsibleManager

**Comment by paregorios** [comment]
I've noticed (by way of the full review list) a number of Poi content items (tickets?) that seem to still be hanging around in staging in pending state. Is that part of this cleanup as well?

**Comment by davisagli** [comment]
Done
