### ISSUE TITLE
Convert LDAP users to standard Plone users

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#66]
part of #49 

Tom mentioned that there's no particular need to keep users in LDAP. Since there aren't a large number of users and depending on LDAP makes it harder to upgrade, we recommend converting the existing LDAP users to standard Plone users.

This probably consists of writing a script to get LDAP users, disable the LDAP plugins, then recreate them in source_users with the same properties and groups.

We can test this on the plone 3 site on the staging server once you're done testing the performance fixes, and then run the conversion on production independently of the plone 4 upgrade.

**Comment by davisagli** [comment]
Properties currently mapped:
- cn => fullname
- mail => email
- uid => user id
- uid => login

Groups mapped from LDAP to Plone roles:
- managers -> Manager role
- members -> Member role

LDAP also has a committers group which is unused by Plone (I guess it's related to svn access).

**Comment by paregorios** [comment]
When converting these we'll want to watch out for clobbered non-ASCII characters in fullname. We had a lot of problems around unicode-or-not between Plone and LDAP and I don't know what all was patched, upgraded, replaced, or duct-taped to make it all work.

**Comment by davisagli** [comment]
Thanks for the heads-up. Can you find a page that includes a fullname with non-ASCII characters so that we have a test case?

**Comment by paregorios** [comment]
These users (note that some also have full names containing more than 2 words, which iirc was at one point also an issue):

- dadima
- holgerj
- jmartinez
- jahlfeldt

Not an exhaustive list, but exemplary I think.

**Comment by davisagli** [comment]
I wrote a script to export users from the production site, and another script to import users to a site that's not using LDAP. I've done a trial run so the plone 4 staging site now has native Plone users based on the ones that were in LDAP. Assigning to @paregorios for testing.

**Comment by paregorios** [comment]
I've successfully logged into staging (p...jazkarta.com) with both my own account and our test account. Everything seems to be in order. I'm OK with closing this ticket if the step is incorporated into whatever repeatable checklist we're going to need for subsequent staging and production deployment.

**Comment by davisagli** [comment]
I've got this in the launch checklist, so am going to close this ticket.
