### ISSUE TITLE
Missing pieces of place view

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#67]
part of #49 

The place view appears to be missing a few things at the bottom: history toggle, print link, commenting.

e.g. compare http://pleiades.stoa.org/places/540726 to http://pleiades.jazkarta.com/places/540726

Also, the description is no longer styled the same, and the Canonical URI is now clearing the map.

**Comment by davisagli** [comment]
@paregorios where do you want the "history" link? At the bottom where it currently appears, or in the byline where it usually goes in Plone 4? No technical concerns from me for either way, since we're already customizing the byline.

**Comment by davisagli** [comment]
Aside from the history link, I've fixed the other issues.

**Comment by paregorios** [comment]
I'd prefer having the history link with the byline.

On Tuesday, March 8, 2016, David Glick <notifications@github.com> wrote:

> Aside from the history link, I've fixed the other issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isawnyu/pleiades-gazetteer/issues/67#issuecomment-194000945>
> .
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Done
