### ISSUE TITLE
unpublished locations leaking into extent/replatlon in dumps?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#7]
tcarlson reports: There is another odd discrepancy between what I see on Pleiades and the data dump: Sozopolis (638758) has two locations (one from DARMC, one from DARE), yet the "extent" field in the data dump describes a triangle (admittedly a very flat triangle) with third point not located on the line which goes through the other locations. The reprLatLong is then the average of these three points, two of them locations of the place and the third a little farther afield.

Migrated from http://pleiades.stoa.org/docs/site-issue-tracker/64

**Comment by paregorios** [comment]
Possibly related to #12 and/or #37

**Comment by davisagli** [comment]
Confirmed. This happens because the dump is made using the extent stored in the catalog metadata, which was updated when a logged-in user made edits. We should make sure that we filter to only consider items that are visible to the public when updating the catalog metadata.

**Comment by davisagli** [comment]
There was already an attempt in place to calculate the representative point from the perspective of an anonymous user when indexing, but it was not correct and the real user was getting restored before the calculation was actually performed. I'm working on fixing this.

I need to clarify one thing. For the representative point that is shown on the place view (coordinates and marker on the map), should we take into account what the current user can view, or only published items?

**Comment by paregorios** [comment]
Unless it's exceptionally the more costly option, either in terms of
programmer time or processing cycles once deployed, I would prefer the
representative point only be calculated against published items.

## 

Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
No, it's both easier and less processing.

**Comment by paregorios** [comment]
Great, then let's do representative point only on the basis of published items.

**Comment by davisagli** [comment]
This should be working on staging now. You can test after tonight's dump.

**Comment by paregorios** [comment]
Looks good on staging. Please deploy to production.

**Comment by davisagli** [comment]
deployed

**Comment by paregorios** [comment]
thanks
