### ISSUE TITLE
"representative point" doesn't show on place map

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#72]
Part of #49. May be related to #71 (see specific error there, which also seems to involve reprPoint).

This problem appears to affect both anonymous and logged-in users.

Steps to reproduce (as an anonymous user):

- Navigate to ```places/511181```
- Select the layers menu icon on the map and activate the checkbox next to "representative point"

Here's what the map looks like on production after doing that:

![bathynias-production](https://cloud.githubusercontent.com/assets/263285/13674687/1bfca372-e6a4-11e5-9815-466153b34848.jpg)

Here's what it looks like on P4 staging:
![bathynias-p4](https://cloud.githubusercontent.com/assets/263285/13674703/282dbd0c-e6a4-11e5-9f13-4d7ce462112c.jpg)

**Comment by davisagli** [comment]
This could easily be related to the changes @alecpm made to load the map JSON asynchronously. Do you want to look at it first, Alec?

**Comment by alecpm** [comment]
Should be fixed now.  It was related to the async loading, the repr point was placed on the map before the JSON had been loaded.
