### ISSUE TITLE
copyright character getting munched on place creation

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#73]
Part of #49.

Copyright character in rights statement in byline appears fine for existing content, but after creating a new place with defaults, it's escaped or something.

Steps to reproduce:

- login to P4 staging
- navigate to /places/
- select "add new" -> "place" from the actions menu
- put title and description in "add place" form and select the save button
- inspect the byline

Here's an example:

![copyright](https://cloud.githubusercontent.com/assets/263285/13679995/30c466ba-e6bc-11e5-8363-0f31c1bda6d1.jpg)

**Comment by davisagli** [comment]
Looks like it is already escaped in the edit form, so probably something wrong with lookup up the default value.

**Comment by davisagli** [comment]
Fixed. I think the live site has the same problem; okay for me to fix it there too?

**Comment by paregorios** [comment]
Yes, please fix on live site.

-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Okay, fixed on live site now too.

p.s. Congrats, this issue made me look at a piece of Plone (the CMF metadata tool) that I've managed to avoid knowing anything about for 8 years.
