### ISSUE TITLE
radio button groups and combo boxes positioned oddly on edit forms

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#78]
Some examples:

![odd1](https://cloud.githubusercontent.com/assets/263285/13708338/afcac852-e773-11e5-9b8f-6aeb0f1bc940.jpg)

![odd2](https://cloud.githubusercontent.com/assets/263285/13708340/b76116fc-e773-11e5-94f0-0b6265b7d660.jpg)

![odd3](https://cloud.githubusercontent.com/assets/263285/13708345/befcc58c-e773-11e5-846e-6f7340723319.jpg)

![odd4](https://cloud.githubusercontent.com/assets/263285/13708358/c61a85b6-e773-11e5-9e79-9c55742880fa.jpg)

**Comment by davisagli** [comment]
Fixed (also fixed field help text styles)
