### ISSUE TITLE
Map icons are broken on working copies of places

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#79]
This is happening on both P3 production and P4 staging.

P3 production:

![mapicons-production](https://cloud.githubusercontent.com/assets/263285/13708770/03f63bc6-e776-11e5-9d5f-e117eae7a7fa.jpg)

P4 staging:

![mapicons-staging](https://cloud.githubusercontent.com/assets/263285/13708776/0dabf2b4-e776-11e5-9a14-745483a24dc9.jpg)

Steps to reproduce:

- Login
- Navigate to any published place
- Choose "actions" -> "check out" from the menu bar.
- Inspect the map in the resulting working copy.

**Comment by davisagli** [comment]
For locations from the baseline it's coded to use `location-gray.png` which doesn't exist. Do you by any chance have a copy of the gray icon?

**Comment by paregorios** [comment]
Ah, evidence of my past misdeeds. So, I've just [created a repository](https://github.com/isawnyu/pmapi) that contains all the map icons that should have been copied into ```/var/www/pleiades.stoa.org/images/pmapi``` on production, but weren't. How hard would it be to get righteous here and incorporate these image files into [PleiadesEntity](https://github.com/isawnyu/PleiadesEntity) instead of having them floating around disconnectedly on the file system?

**Comment by davisagli** [comment]
Yeah, that sounds good to me.

**Comment by paregorios** [comment]
Great!

On Wednesday, April 6, 2016, David Glick <notifications@github.com> wrote:

> Yeah, that sounds good to me.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/isawnyu/pleiades-gazetteer/issues/79#issuecomment-206438315>
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by davisagli** [comment]
Done
