### ISSUE TITLE
place map doesn't auto-zoom on working copy checkout

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#80]
On production, when viewing a working copy of a place, the map auto-zooms to the immediate locale:

![mapicons-production](https://cloud.githubusercontent.com/assets/263285/13708873/79e27dd6-e776-11e5-88a7-82674a03fd5f.jpg)

This isn't happening on P4 production:

![mapicons-staging](https://cloud.githubusercontent.com/assets/263285/13708885/87b474dc-e776-11e5-8986-f8f4aba80868.jpg)

**Comment by davisagli** [comment]
Fixed. This was a side effect of the change to load the JSON via separate requests. I adjusted the javascript to wait for both the baseline and working copy JSON responses before setting the map bounds.
