### ISSUE TITLE
location icons are broken in /recently_modified

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#82]
Tested with an authenticated user. Occurs on P4 staging, but not on P3 production:

![recently](https://cloud.githubusercontent.com/assets/263285/13718020/85cf4e50-e7ab-11e5-9e83-1eb2b0a7b8b7.jpg)

**Comment by davisagli** [comment]
Seems to be working for me (may have gotten fixed already)
