### ISSUE TITLE
pdf icons are broken in /docs/reports

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#83]
Tested with an authenticated user. Problem manifests on P4 staging but not P3 production:

![pdf](https://cloud.githubusercontent.com/assets/263285/13718090/3ade733e-e7ac-11e5-939f-786052f778b7.jpg)

**Comment by paregorios** [comment]
Not PDF, but see also: ```/docs/papers-and-presentations``` where one icon is busted.

**Comment by davisagli** [comment]
Fixed
