### ISSUE TITLE
Determine cause of CPU usage spikes

### ISSUE THREAD

**Issue by davisagli** [isawnyu/pleiades-gazetteer#85]
The staging server occasionally has its CPU usage spike to the point where the server is inaccessible. @paregorios notes that this happens on the Plone 3 production instance too.

I should probably rig up something to dump out a stacktrace when it detects that, so that we can figure out what it's doing.

**Comment by davisagli** [comment]
"It may be a red herring, but it was behaving well until I clicked on the site map link in the header."

**Comment by davisagli** [comment]
I was able to reproduce the problem by loading the sitemap. There's a setting to limit how deep to make the sitemap; I changed it from 3 to 2 and now it seems to load fine.

**Comment by davisagli** [comment]
Btw, let me know if you want to show the link to the sitemap or not. I think it got turned on as an accidental side effect of one of the Plone upgrade steps.

**Comment by paregorios** [comment]
Closing resolved. Will answer [@davisagli's question](https://github.com/isawnyu/pleiades-gazetteer/issues/85#issuecomment-196129193) in a new ticket.
