### ISSUE TITLE
paged connection nav links are doubled on place pages

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#87]
In the rare cases where we have more than 50 connections to a place, the results list gets automatically batched. On production, the associated navigation controls appear at both top and bottom of the "Has a connection with" section. This seems sensible.

On P4 staging, the navigation controls also appear at both top and bottom of the "Has a connection with" section, but at the bottom of the listing, the nav component is repeated. There don't seem to be any differences between the three, but the doubling at the bottom of the "Has a connection with" listing doesn't match P3 production and seems likely to confuse users.

Here's a screenshot of P3 production at the bottom of a batched "Has a connection with" list:

![p3-connav-end](https://cloud.githubusercontent.com/assets/263285/13728423/06e917ce-e8e6-11e5-8e1a-ce5a7288874e.jpg)

And here's such a listing in P4 staging:

![p4-connav-end](https://cloud.githubusercontent.com/assets/263285/13728424/1f95e11c-e8e6-11e5-912a-3ea3bf495ede.jpg)

Steps to reproduce:

- open ```/places/423025``` in browser
- scroll down to the bottom of the "Has a connection with" listing

**Comment by davisagli** [comment]
@cguardia this looks like a good one to start on. This list appears in the place view (place_view.pt in Products.PleiadesEntity).

**Comment by cguardia** [comment]
The Plone folder listing now adds navigation at the bottom, so removed the one we added.

**Comment by paregorios** [comment]
staging is refusing connections this morning, so I am unable to check

**Comment by paregorios** [comment]
staging is back now

**Comment by paregorios** [comment]
I see no indication that this is fixed as deployed on staging, e.g. see e.g. ```/places/423025/base_view```

**Comment by davisagli** [comment]
@cguardia hasn't deployed this yet (note that it's not assigned to you for review yet, @paregorios)

**Comment by davisagli** [comment]
This is now deployed.
