### ISSUE TITLE
extraneous workflow and states?

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#88]
This issue applies to both P3 production and P4 staging, but probably only needs to be addressed for P4.

The list of "review status" states shown on the "Workflow Details" tab on the ```/search_form``` page leads me to believe that we have multiple workflows defined (probably unnecessarily). P3 production shows even more, but removing Poi from the P4 buildout gets rid of alot of them. But there are still some that look to me like deriving from an intranet workflow that I suspect we don't need.

Here's a screen capture of the listing in question on P4 staging:

![p4-states](https://cloud.githubusercontent.com/assets/263285/13728463/b558de7e-e8e7-11e5-9731-cd48dd4783c5.jpg)

**Comment by cguardia** [comment]
This can be tested on staging now.

**Comment by paregorios** [comment]
Re-opening until we're sure this is committed.

**Comment by cguardia** [comment]
Commited.
