### ISSUE TITLE
remove all content rating functionality

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#89]
It's underused, clutters up the interface, and didn't achieve what we wanted.

Removal is likely harder than just yanking the add-on. I think there's code (moribund? commented out? ignored? or not) for sorting names and locations within place listings based on ranking.

**Comment by cguardia** [comment]
I think I covered all the bases. Please test.

**Comment by paregorios** [comment]
Content rating widgets are still visible on name and location pages:

![content-rating-name](https://cloud.githubusercontent.com/assets/263285/14379747/97c254aa-fd49-11e5-8a7f-c2b79036f4b6.png)
![content-rating-location](https://cloud.githubusercontent.com/assets/263285/14379746/97bff0fc-fd49-11e5-8561-3d766ebc5625.png)

Moreover, there is now a related error: #113

**Comment by cguardia** [comment]
Forgot to uninstall the ratings product. Done.

Also, fixed the error in #113.

**Comment by davisagli** [comment]
@cguardia did you uninstall it through the web or add an upgrade step? Remember that anything we do through the web will be wiped out when we run the real migration from production.

**Comment by cguardia** [comment]
I was planning to make a step. In fact, I typed this too early. I was unable to uninstall from the web now that I tried. I get a weird plone.ldap error.

**Comment by davisagli** [comment]
What's the error?

**Comment by cguardia** [comment]
Ok, now it should be working.

**Comment by paregorios** [comment]
Reopening because #123
