### ISSUE TITLE
some control panel icons are broken

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#90]
There's one such broken icon on P3 production ```/plone_control_panel``` (Workflow Policies). It's also broken in P4 staging ```/@@overview-controlpanel```, where one also finds additional broken icons for "Visual Editor" and "Image Handling." No need to fix on production, but should fix in P4 going forward. Is this indicative of potential breakage somewhere else, possibly with respect to general image handling support?

Screen shot from P4 staging:

![controlpanelicons](https://cloud.githubusercontent.com/assets/263285/13728578/fca5aa66-e8ea-11e5-8c0b-4ce52c50a804.jpg)

**Comment by cguardia** [comment]
@paregorios I have an upgrade step to fix this, but it seems I don't have commit permission to pleiades.policy. Can someone give me that please?

My fix for #88 was also not committed because of this (but it's working on the site).

**Comment by paregorios** [comment]
I've just added the "Pleiades team" as admin on the pleiades-policy repository; evidently when alecpm set it up, he didn't add anyone else to it.

**Comment by cguardia** [comment]
Thanks. Committed and ran on staging.
