### ISSUE TITLE
working copy notifications overlap menus

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#91]
The working copy notification blocks that appear on both the working copy and the corresponding baseline item overlap other UI components on P4 staging. Screen shots below show working copy and baseline of a ```Name``` item, but this behavior can be seen after checking out working copies of a ```Place``` or a ```Location``` as well. 

Are there other kinds of notifications that appear in the same slot that might be similarly affected? 

Screen shot of notification on working copy:
![working-copy-overlap](https://cloud.githubusercontent.com/assets/263285/13728605/12dc33d0-e8ec-11e5-887a-7396dfd250d9.jpg)

Screen shot of notification on baseline item:
![working-copy-overlap-baseline](https://cloud.githubusercontent.com/assets/263285/13728607/1ece13ca-e8ec-11e5-80b5-a9c81a19a9cc.jpg)

**Comment by davisagli** [comment]
Fixed
