### ISSUE TITLE
/places frequently slow to load on p4 production

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#92]
I'm routinely seeing this take 3+ seconds to load; sometimes as many as 10. It's noticeable, and I don't understand why.

Could the Pelagios portlet be the culprit?

**Comment by davisagli** [comment]
The Pelagios portlet is loaded via a separate AJAX request after the main page load, so is very unlikely to be the culprit.

It's not obvious to me what the problem is, and I don't see the problem consistently (only on the first page load after starting the instance, which is bound to be slower). I suggest we take a look at this with New Relic once it's set up; it'll make it a lot easier to confirm that there is a problem with this particular page and figure out where it comes from.

**Comment by paregorios** [comment]
Agree on deferring until we have New Relic in place. Pulling out of the P4 upgrade deployment milestone.

**Comment by alecpm** [comment]
I can setup New Relic using my personal account for the time being, and David and I can analyze data there. Then we can switch over to a new New Relic Pro Trial when we do the production launch.

**Comment by davisagli** [comment]
Good idea @alecpm

**Comment by paregorios** [comment]
So, should I add this ticket back to the P4 upgrade deployment milestone and give it a priority?

**Comment by skleinfeldt** [comment]
@paregorios I think you should decide if you want this in the P4 upgrade deployment milestone, and whether it should remain on the #51 checklist. (I sort of lost track of it because it wasn't in the milestone.)

**Comment by paregorios** [comment]
It's not in the milestone now and I'm happy to leave it out, with the understanding we'll see how live performance goes and, if we notice oddities, go poking around with our New Relic powers.

**Comment by paregorios** [comment]
We were noticing this immediately post-deploy on new production, although RAM caching may be mitigating the behavior now from the user perspective. There was some discussion in IRC about how to fix it.

**Comment by davisagli** [comment]
I tracked down the source of this; some code for the display menu was doing an inefficient check that required loading a list of all place ids when it didn't have to, which was slow when the internal structure of the places folder wasn't in the ZODB cache yet. Submitted a pull request to plone.app.contentmenu and updated the Pleiades buildout to use that branch. Deployed to staging.

**Comment by davisagli** [comment]
This is on production
