### ISSUE TITLE
programmatically create a place from a location

### ISSUE THREAD

**Issue by paregorios** [isawnyu/pleiades-gazetteer#99]
We have a large number of ```locations``` that should have been (in the current editorial view) had new ```places``` created to contain them instead of being created inside the ```places``` where they currently reside. How hard would it be to create a mechanism whereby an editor -- ideally through-the-plone -- could force the programmatic creation of a new ```place``` on the basis of the existing ```location``` and transfer of said ```location``` into that new ```place```? Via @atomrab @rmhorne et al.

**Comment by davisagli** [comment]
What information needs to be transferred from the location to the place? Can it be done automatically or are you thinking more of loading the place add form pre-populated with some info from the location?

Do we also need some sort of duplicate check to try to alert you if there's already an existing place similar to the one you're trying to create?

**Comment by paregorios** [comment]
This was implemented as [Story 51 in scrumdo](https://www.scrumdo.com/projects/project/pleiades/iteration/133485#story_1095150). It has been reviewed and deployed to production. Closing as resolved.
